<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/login.css" />
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/site/Login.js"></script>

<input type="hidden" id="login" value="" />
<input type="hidden" id="senha" value="" />

<div id="header-login">
    <a href="<?= $this->baseUrl() ?>/"></a>
</div>
<div class="tablet-notebook" style="margin: 0 1em;">

    <div class="panel panel-default" style="margin: 0 auto; width: 100%; max-width: 25em;">
        <div class="panel-heading">
            <h3>Cadastre-se agora</h3>
        </div>
        <div class="panel-body">
            <form id="form-login-cad" method="post">
                    <input type="hidden" id="rdTipo" name="rdTipo" value="2" />

                    <div class="input-text no-margin">
                        <label for="nome">Nome</label>
                        <input type="text" id="nome" name="nome" value="" placeholder="Informe o nome" class="form-control">
                    </div>
                    <div class="input-text no-margin">
                        <label for="email">E-mail</label>
                        <input type="text" id="email" name="email" value="" placeholder="Ex: contato@gtrainer.com" class="form-control">
                    </div>

                    <div class="input-text">
                        <label for="plano">Plano</label>
                        <select name="cbTipoPlano" id="cbTipoPlano" class="form-control">
                            <option value="1" selected="selected">Experimental - (30 dias GRATUITO)</option>
                            <?php #foreach($this->aPlanos as $plano): ?>
                                    <!--<option value="<?= $plano['id'] ?>"><?= $plano['ds_plano'] ?> - R$ <?= $plano['valor'] ?></option>-->
                            <?php #endforeach; ?>
                        </select>
                    </div>

                    <div class="input-group">
                          <span class="input-group-addon">
                            <input type="checkbox" onclick="mostrarSenha(this)"> &nbsp;
                            <i class="glyphicon glyphicon-eye-open"></i>
                          </span>
                          <input type="password" class="form-control" id="senhaCad" name="senhaCad">
                    </div>
                    <small>Clique no botão acima para ver a senha</small>
                    <br><br>

                    <button type="button" id="btnCadastrar" class="btn btn-primary btn-block btn-lg">Cadastrar</button>
                    <br>
                    <p class="texto"><a href="<?= $this->baseUrl() ?>/index/login">&larr; Voltar para o login</a></p>
                </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var campo = document.getElementById('senhaCad');

    function mostrarSenha(e) {
        campo.type = (e.checked? 'text' : 'password');
    }

    ajustarRodape(); 
    $(window).resize(function () {
        ajustarRodape(); 
    });

    function ajustarRodape() {
        $("#mini-rodape ul.links li").width($("#mini-rodape ul.links").innerWidth() / $("#mini-rodape ul.links li").length);
    }
</script>