<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
<style>
 table tr th { font-size: 35px; }
 table tr td { font-size: 35px; }
</style>
<?php
    $dadosAluno = $this->dadoAluno;    
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);    
    $totalDeFichas = count($this->dadosFicha);
    
   #Utils_Print::printvardie($this->dadoAluno);
?>

<div style="font-size: 40px; font-weight: bold; text-align: center; background: #111; border-top: 1px solid #ddd; padding: 18px; color: #fff;">
    <a href="#" onclick="history.go(-1)" class="btn btn-primary" style="font-size: 35px; float: left;"> < </a>
    Fichas de Treino do Aluno
    <a href="../admin/logout" class="btn btn-primary" style="font-size: 35px; float: right;">Sair</a>
</div>

<div style="text-align: center; margin-top: 3px;">
    <img class="" src="<?php echo $this->baseUrl() ?><?php echo $dadosAluno['foto']; ?>" width="20%" />
 </div>

<div style="margin-top: 5px; font-size: 35px; text-align: center; font-weight: bold;">
    <span style="color: green"><?= ($dadosAluno['nome']); ?></span>
</div>

<br>

<?php if($totalDeFichas == 0): ?> 
    <div class="alert alert-block alert-warning" style="text-align: center;">Nenhuma Ficha de treino foi criada para voc&ecirc;.</div>  
<?php else: ?>

    <table width="100%" class="table table-striped">
        <tr>
            <th>Treinos</th>
            <th>Professor</th>
            <!--<th style="text-align: center;">Data</th>-->
            <th width="10%" style="text-align: center;"></th>
        </tr>
        <?php foreach ($this->dadosFicha as $ficha): ?>
            
            <tr>
                <td><?= utf8_encode($ficha['ds_ficha']) ?></td>
                <td><?= utf8_encode($ficha['nm_professor']) ?></td>
                <!--<td align="center"><?= Utils_Date::formataDataSemHoraToShow($ficha['dt_ini_ficha']) ?></td>-->
                <td align="center">
                    <button class="btn-primary img-rounded" onclick="visualizarTreino(<?= $ficha['aluno_id']; ?>, <?= $ficha['id'] ?>)">
                        <i class="ace-icon fa fa-edit"> </i> ver
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?php endif; ?>

<script>
function visualizarTreino(aluno_id,ficha_id) {
    window.location = '../index/visualizar-treino/matricula/'+aluno_id+'/ficha_id/'+ficha_id;
}    
</script>

