<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>

<?php
    $dadosAluno = $this->dadoAluno;    
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
?>


<div style="text-align: center; margin-top: 3px;">
    <img class="" src="<?php echo $this->baseUrl() ?><?php echo $dadosAluno['thumbnail']; ?>" width="20%" />
 </div>

<div style="margin-top: 5px; font-size: x-large; text-align: center; font-weight: bold;">
    <span style="color: green"><?= ($dadosAluno['nome']); ?></span>
</div>

<br>



<table width="100%" class="table table-striped">
    <tr>
        <td align="center"><a href="../avaliacoes/<?= $dadosAluno['email'] ?>">Avalia&ccedil;&atilde;o F&iacute;sica</a></td>
    </tr>
    <tr>
        <td align="center"><a href="../treinos/<?= $dadosAluno['email'] ?>">Treinos</a></td>
    </tr>
    <tr>
        <td align="center"><a href="../admin/logout">Sair</a></td>
    </tr>
</table>