<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
<style>
 table tr th { font-size: 40px; }
 table tr td { font-size: 40px; padding: 50px; }
</style>
<?php
    $dadosAluno = $this->dadoAluno;    
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
?>

<div style="font-size: 40px; font-weight: bold; text-align: center; background: #111; border-top: 1px solid #ddd; padding: 18px; color: #fff;">
    &Aacute;rea do Aluno
    <a href="../admin/logout" class="btn btn-primary" style="font-size: 35px; float: right;">Sair</a>
</div>
<!--
    <div style="text-align: center; margin-top: 3px;">
       <?php if($dadosAluno['thumbnail']): ?>
          <img class="" src="<?php echo $this->baseUrl() ?><?php echo $dadosAluno['thumbnail']; ?>" width="20%" />
       <?php else : ?>
          <img src="<?= $this->baseUrl().'/images/fotos/default.jpg' ?>" width="20%" />
       <?php endif; ?>        
    </div>
-->    
    <br>
    <div style="font-size: 40px; text-align: center; font-weight: bold; padding: 5px;">
       <span style="color: #000;"><?= ($dadosAluno['nome']); ?></span>
    </div>
    <br><br><br>

    <table width="100%" class="table">
        <tr>
            <td align="center"><a href="../avaliacoes/<?= $dadosAluno['email'] ?>">Avalia&ccedil;&atilde;o F&iacute;sica</a></td>
        </tr>
        <tr>
            <td align="center"><a href="../treinos/<?= $dadosAluno['email'] ?>">Treinos</a></td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
    </table>

