<div id="tip"></div>
    <div id="header-inicio">
        <div id="header">
            <div class="clear">
                <div class="logo-sistema">
                    <a href="index.html"></a>
                </div>
                <div class="nav-hotsite">
                    <ul id="menu">
                        <li class="ativo"><a href='#como-funciona' class="ancora">Como funciona</a></li>
                        <li class="ativo"><a href="#sobre-nos" class="ancora">Sobre nós</a></li>
                        <li class="ativo"><a href='#ver-planos' class="ancora">Planos</a></li>
                        <li class="ativo-cad"><a href='<?= $this->baseUrl() ?>/index/cadastro' class="ancora">Cadastre-se</a></li>
                        <li class="acesse-sua-conta"><a href='<?= $this->baseUrl() ?>/index/login'> Acesse sua conta  </a></li>
                    </ul>
                </div>
            </div>
<!--            <h1>Agora ficou fácil acompanhar os treinos!</h1>-->
            <div id="cadastrar">
                <form method="post">
                    <p class='titulo' style="font-size: 24px;">Bem-vindo ao GTrainer!</p>
                    <p class='subtitulo' style="font-size: 14px; margin: 20px 0px;">
                        O GTrainer é um aplicativo que auxilia os profissionais de academias
                        (Personal Trainer) a realizarem a montagem e acompanhamento dos treinos
                        dos seus alunos, dentro ou fora da academia, permitindo fazer atualizações 
                        na hora do treino como: aumento de carga, troca de exercícios, etc. Acesse o 
                        GTrainer via computador, celular ou tablet.
                    </p>
		    <a href="#como-funciona" class="btn-principal btn-grande btn-cadastrar ancora" style="width: 210px;">Saiba mais!</a> 
                </form>
            </div>
<!--            <div id="banner"></div>-->
        </div>
    </div>
    <div id="como-funciona">
        <div id="informacoes">
            <div class="titulo">
                <div class="azul-1"></div>
                <div class="azul-2"></div>
                <div class="azul-3">
                    <h2>Nunca foi tão <span class='destaque'>rápido</span> e <span class='destaque'>fácil</span> acompanhar os treinos...</h2>
                </div>
            </div>
            
            
            <ul class="step-by-step clear">
                <li class="item">
                    <h3>Cadastre seus alunos</h3>
                    <span class="icon-100 icon-usuario"></span>
                    <p class="descricao">Você cadastra todos os seus alunos pelo site de maneira rápida e prática.</p>
                </li>
                <li class="seta-direita"></li>
                <li class="item">
                    <h3>Monte as fichas de treinos</h3>
                    <span class="icon-100 icon-documentos"></span>
                    <p class="descricao">Monte as fichas de treino e envie para o e-mail dos alunos.</p>
                </li>
                <li class="seta-direita"></li>
                <li class="item">
                    <h3>Faça o acompanhamento</h3>
                    <span class="icon-100 icon-boleto"></span>
                    <p class="descricao">Acompanhe os treinos e atualize na hora os dados da ficha.</p>
                </li>
            </ul>
            
        </div>
        
        <div id="porque-escolher">
            <h2>Como funciona o <img src="<?= $this->baseUrl() ?>/images/site/porque-escolher/logo-sistema.png" alt="ezBill"/> ?</h2>
            <div class="texto-porque-escolher">
                <div class="box tudo-online">
                    <h3>Faça tudo online, sem instalação no PC, celular ou tablet!</h3>
                    <p class="texto">Você que é profissional da área (Personal Trainer ou Instrutor de academias) terá a possibilidade de criar as fichas de treino dos seus alunos e disponibilizar pela internet ou enviar por email, <b>a qualquer horário e qualquer dia</b>. No ausência do professor no treino, há ilustração da execução dos exercícios, caso o aluno tenha dúvidas. </p>
                </div>
                
                <div class="box seguranca">
                    <h3>Segurança em primeiro lugar!</h3>
                    <p class="texto">O acesso ao gerenciador do professor é restrito. <b>É estritamente necessário informar corretamente os campos de login e senha</b> para utilizar o aplicativo. Os critérios de segurança são os mesmo para quem acessa do computador, celular ou tablet, pelo fato de ser um aplicativo web.</p>
                </div>
                
                <div class="box relatorios">
                    <h3>Acompanhe e modifique os treinos do aluno em tempo real.</h3>
                    <p class="texto">Você pode acompanhar os treinos dos seus alunos pelo aplicativo, tendo a <b>possibilidade de fazer alterações em tempo real</b> como: aumentar ou diminuir a carga, adicionar, remover ou editar exercícios, alterar a repetição, intervalo e série do treino, bem como, o controle da frequência do aluno.</p>
                </div>
                
            </div>
        </div>
        
    </div>
    
    <div id="ver-planos"  class="assinatura">
        <div id="interface">            
            <div class="btn-base">
                <h2>Aproveite e conheça o <img src="<?= $this->baseUrl() ?>/images/site/porque-escolher/logo-sistema.png" alt="ezBill"/> gratuitamente.</h2>
                <a class="btn-principal btn-duas-linhas btn-grande" href="<?= $this->baseUrl() ?>/index/cadastro">
                    <!--<p>Cadastre-se por 30 dias Gratuito!</p>-->
                    <p>Cadastre-se já!</p>
                </a>
            </div>
        </div>
        <div id="planos" style="width: 960px; text-align: center; margin: 0 auto;">
            <div class="plano sem-banco" style="border: 1px solid #444; width: 220px; margin-right: 25px;  border-radius: 5px 5px 5px 5px;">
                    <h1 style="font-weight: bold;background: #499FBC; color: #fff; padding: 5px; border-radius: 5px 5px 5px 5px;">Plano Experimental</h1>
                    <br>
                    <h1>Gratuito</h1>
                    <hr>
                    <p style="color: #555; font-family: sans-serif;">30 dias de acesso livre</p>
            </div>
            <div class="plano sem-banco" style="border: 1px solid #444; width: 220px;  border-radius: 5px 5px 5px 5px;">
                <h1 class="nome-plano" style="font-weight: bold;background: #499FBC; color: #fff; padding: 5px; border-radius: 5px 5px 5px 5px;">Plano Semestral</h1>
                <br>
                <h1>Indisponível</h1>
                <hr>
                <p style="color: #555; font-family: sans-serif;">6 meses</p>
            </div>
            <div class="plano com-banco" style="border: 1px solid #444; width: 220px;  border-radius: 5px 5px 5px 5px;">
                <h1 class="nome-plano" style="font-weight: bold;background: #499FBC; color: #fff; padding: 5px; border-radius: 5px 5px 5px 5px;">Plano<br>Anual</h1>
                <br>
                <h1>R$ 99,90</h1>
                <hr>
                <p style="color: #555; font-family: sans-serif;">1 ano de acesso total</p>
            </div>
            
        </div>
    </div>
    <br><br>
    <footer>
    <div id="sobre-nos" class="conteudo">
<!--        <div class="sobre-sistema">
            <p class="titulo">Sobre o GTrainer</p>
            <p class="texto">O GTrainer é um aplicativo que auxilia os profissionais de academias
                        (Personal Trainer) a realizarem a montagem e acompanhamento dos treinos
                        dos seus alunos, dentro ou fora da academia, permitindo fazer atualizações 
                        na hora do treino como: aumento de carga, troca de exercícios, etc. Acesse o 
                        GTrainer via computador, celular ou tablet.
            </p>
        </div>-->
        <!--div class="mapa-site">
            <ul class="mapa">
                <li>
                    <p>Site</p>
                    <a href="../blog.ezbill.com.br/index.html" target="_blank">Blog</a>
                    <a href="como-funciona.html">Como funciona</a>
                    <a href="planos-e-precos.html">Planos e preços</a>
                    <a href="login.html">Acesse sua conta</a>
                    <a href="ajuda/termos-de-uso.html">Termos de uso</a>
                    <a href="ajuda/politica-privacidade.html">Política de privacidade</a>
                    <a href="ajuda/politica-seguranca.html">Política de segurança</a>
                </li>
                <li>
                    <p>Sobre a empresa</p>
                    <a target="_blank" class="conheca-uni4-sistemas">Conheça a UNI4 Sistemas</a>
                    <a href="contato.html">Fale conosco</a>
                    <a href="javascript:fbShare('index.html', 'Indique o ezBill', 'Indique o ezBill a seus amigos!', 'img/logo-sistema-mini.png', 550, 350)">Indique o ezBill</a>
		    <a href="../www.facebook.com/ezBillBrasil.html" target="_blank">Facebook</a>
                    <a href="../plus.google.com/%2bEzbillBrasil.html" rel="publisher" target="_blank">Google+</a>
                </li>
                <li>
                    <p>Suporte</p>
                    <a href="ajuda.html">Ajuda online</a>
                    <a href="../status.ezbill.com.br/index.html" target="_blank">Status do sistema</a>
                    <a href="contato.html">Envie sua dúvida</a>
		    <a href="../mixpanel.com/index5434.html" style="margin-top: 15px;"><img src="../cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>
                </li>
            </ul>
            <div class="ssl">
                <div class="nav_section signs" id="sslblindado">
			        <param id="sslblindado_preload" value="true" />
   		        </div>
		        <script type="text/javascript" src="../selo.siteblindado.com/sslblindado.html"></script>
            </div>
        </div>-->
        <div class="clear">
            <div class="info-blog">
                <div class="informacoes">
                    <div class="telefone">
                        <i class="icon-60 icon-telefone"></i>
                        <p>
                            <span>91</span> 98083-2418
                            <span class="horario-atendimento">Segunda à Sábado: <br />8h às 12h - 13h30 às 18h</span>
                        </p>
                    </div>
                    <div class="email">
                        <i class="icon-60 icon-email"></i>
                        <p>Fale conosco:<br />contato@gtrainer.com.br</p>
                        <a href="contato.html"></a>
                    </div>
                    <div class="localizacao">
                        <i class="icon-60 icon-localizacao"></i>
                        <p>Rua Baião, nº 134<br/>Marambaia - Belém - PA</p>
                    </div>
                </div>
                <div class="blog">
                    <p class="titulo">Sobre o GTrainer</p>
                    <div class="ultimas-postagens">
                        <a href="#" style="text-decoration: none; text-align: justify;">
                                O GTrainer é um aplicativo que auxilia os profissionais de academias
                                (Personal Trainer) a realizarem a montagem e acompanhamento dos treinos
                                dos seus alunos, dentro ou fora da academia, permitindo fazer atualizações 
                                na hora do treino como: aumento de carga, troca de exercícios, etc. Acesse o 
                                GTrainer via computador, celular ou tablet.
                            </a>
                    </div>
                </div>
                <div style="display: inline-block; float: left; margin-top: -185px; padding-top: 25px; padding-left: 25px; margin-left: 650px;">
	                <p style="position: absolute; color: white; font-family: Segoe UI Semibold; font-size: 25px; margin: -50px 0 12px;">Meios de acesso</p>
	                <img src="<?= $this->baseUrl() ?>/images/site/pc-tablet-01.png" style="width: 350px; position: absolute; " />
	         </div>
            </div>
            
            <div class="copyright">
                <p>
                    <!--<img src="img/logo-sistema-01.png" />-->
                </p>
            </div>
        </div>
    </div>
</footer>

<div  id="conheca-uni4-sistemas" class="modal modal-nao-tem-conta" style="display:none;">
    <div class="conteudo">
        <p class="text-grande">Conheça a UNI4 Sistemas</p>
        <p>A UNI4 Sistemas atua no mercado de tecnologia da informação no segmento de softwares empresariais, executando projetos de âmbito nacional em empresas de pequeno, médio e grande porte.</p>
        <p>O ramo de softwares empresariais apresenta potencial capacidade para o desenvolvimento de negócios, sendo que, para conquistar uma posição de destaque, as empresas necessitam de inteligência, criatividade para inovar e a execução de uma boa gestão.</p>
        <p>A UNI4 Sistemas pretende ser reconhecida com uma parceira tecnológica para o desenvolvimento dos negócios de seus clientes, tendo em vista que muitos não possuem sistemas informatizados para gestão de suas empresas ou necessitam de melhorias em seus processos operacionais e administrativos.</p>
        <p>Uma bandeira de trabalho da UNI4 Sistemas é a prestação de atendimento de qualidade focado nas necessidades dos clientes e parceiros, visando ser encarada como uma potencial colaboradora na obtenção dos resultados.</p>
        <p class="destaque">Missão</p>
        <p>Desenvolver soluções de softwares aplicadas ao apoio de atividades e processos organizacionais.</p>
        <p class="destaque">Visão</p>
        <p>Ser reconhecida como uma empresa inovadora em soluções de softwares para negócios.</p>
        <p class="destaque">Valores</p>
        <p>Ética; Verdade e honestidade; Cooperação; Humildade; Iniciativa; Responsabilidade; Aprendizado contínuo; e Compromisso com os resultados.</p>
    </div>    
    <div class="rodape"></div>
</div>

<script type="text/javascript">
$(document).ready(function(){
   $('.ancora').click(function(){
      var alvo = $(this).attr('href').split('#').pop();
      $('html, body').animate({scrollTop: $('#'+alvo).offset().top }, 1000);
      return false;
   });
});
</script>