<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
<style>
 table tr th { font-size: 45px; }
 table tr td { font-size: 45px; }
</style>
<?php
    $dadosAluno = $this->dadoAluno;    
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
    $totalDeAvaliacoes = count($this->aAvaliacao);
?>

<div style="font-size: 55px; font-weight: bold; text-align: center; background: #111; border-top: 1px solid #ddd; padding: 5px; color: #fff;">
    Avalia&ccedil;&otilde;es do Aluno
</div>

    <div style="text-align: center; margin-top: 3px;">
       <?php if($dadosAluno['thumbnail']): ?>
          <img class="" src="<?php echo $this->baseUrl() ?><?php echo $dadosAluno['thumbnail']; ?>" width="20%" />
       <?php else : ?>
          <img src="<?= $this->baseUrl().'/images/fotos/default.jpg' ?>" width="20%" />
       <?php endif; ?>        
    </div>
    
    <div style="font-size: 55px; text-align: center; font-weight: bold; padding: 5px;">
       <span style="color: green"><?= ($dadosAluno['nome']); ?></span>
    </div>

    <?php if($totalDeAvaliacoes == 0): ?>
        <div class="alert alert-block alert-warning" style="text-align: center;">
            <b>Nenhuma avalia&ccedil;&atilde;o foi criada para este aluno.</b>
        </div>
    <?php else: ?>

        <table width="100%" class="table table-striped">
            <tr>
                <th>Avalia&ccedil;&otilde;es</th>
                <th>Peso</th>
                <th>IMC</th>
                <th style="text-align: center;"></th>
            </tr>
            <?php foreach ($this->aAvaliacao as $avaliacao): ?>
                <tr>
                    <td>Avalia&ccedil;&atilde;o em <?= Utils_Date::formataDataSemHoraToShow($avaliacao['data']) ?></td>
                    <td><?= ($avaliacao['peso']) ?></td>
                    <td><?= ($avaliacao['imc']) ?></td>
                    <td align="center">
                        <button class="btn-primary img-rounded" onclick="visualizarAvaliacao(<?= $avaliacao['id']; ?>)">
                            ver
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>

    <?php endif; ?>

<script>
function visualizarAvaliacao(id) {
    window.location = '../index/ver-avaliacao-fisica/avaliacao_id/'+id;
}    
</script>