<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>

<?php
    $dadosAluno = $this->dadoAluno;    
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
    $totalDeAvaliacoes = count($this->aAvaliacao);
?>

<div style="text-align: center; margin-top: 3px;">
    <img class="" src="<?php echo $this->baseUrl() ?><?php echo $dadosAluno['thumbnail']; ?>" width="20%" />
 </div>

<div style="margin-top: 5px; font-size: x-large; text-align: center; font-weight: bold;">
    <span style="color: green"><?= ($dadosAluno['nome']); ?></span>
</div>

<br>

<?php if($totalDeAvaliacoes == 0): ?>
    <div class="alert alert-block alert-warning" style="text-align: center;">
        <b>Nenhuma avalia&ccedil;&atilde;o foi criada para este aluno.
    </div>
<?php else: ?>

    <div style="font-size: 18px; font-weight: bold; text-align: center; background: #F9F9F9; border-top: 1px solid #ddd; padding: 5px;">
        Avalia&ccedil;&otilde;es do Aluno
    </div>

    <table width="100%" class="table table-striped">
        <tr>
            <th>Avalia&ccedil;&otilde;es</th>
            <th>Peso</th>
            <th>IMC</th>
            <th style="text-align: center;">Editar</th>
        </tr>
        <?php foreach ($this->aAvaliacao as $avaliacao): ?>
            <tr>
                <td>Avalia&ccedil;&atilde;o em <?= Utils_Date::formataDataSemHoraToShow($avaliacao['data']) ?></td>
                <td><?= ($avaliacao['peso']) ?></td>
                <td><?= ($avaliacao['imc']) ?></td>
                <td align="center">
                    <button class="btn-primary img-rounded" onclick="visualizarAvaliacao(<?= $avaliacao['id']; ?>)">
                        <i class="ace-icon fa fa-edit"> </i> ver
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?php endif; ?>

<script>
function visualizarAvaliacao(id) {
    window.location = BASE_URL+'index/ver-avaliacao-fisica/avaliacao_id/'+id;
}    
</script>
