<link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/js/jquery/jquery-mobile/css/carousel.css">
<script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-mobile/js/carousel.js"></script>	
<style>
a {
  color : #333;
}
.type-interior {
    background: #111;
}
</style>
	
<div id="content" style="height:100%;width:100%;">
    <div style="height:100%;width:100%;">
        <!-- start carousel widget html -->
        <div style="height:545px;width:312px;">
            <div id="carousel" class="carousel">	
                <div id="carousel_scrollpane" class="carousel-content">
                    <div id="carousel_content" class="carousel-content-scroller"> </div>
                </div>
                <div id="carousel_nav" class="carousel-nav">
                    <div id="carousel_mid" class="carousel-mid"></div>
                </div>
            </div>
        </div><!-- end carousel widget html -->
        <!-- template used for the carousel items -->
        <div id="carousel_template" style="display:none">
            <div class="carousel-item">
                <!--<div style="height:2em;font-size:1.5em;padding-bottom:15px;">@{title}</div>-->
                <div id="carousel_item_@{id}" >
                    <div style="float:left;width:100%"><img src="@{image}" width="100%" /></div>	
                </div>
            </div>
        </div> 
        <script>
            var carousel = new $.widgets.Carousel({
                uuid: "carousel",
                args: {"scrollInterval": 600, "itemWidth": 300
                },
                value: [
                    {"title": "Tron.Legacy",
                        "image": BASE_URL+"images/printgtrainer/img_aluno01.png"
                    },
                    {"title": "Yogi Bear",
                        "image": BASE_URL+"images/printgtrainer/img_aluno02.png"
                    },
                    {"title": "The Chronicles of Narnia: The Voyage of the Dawn Treader",
                        "image": BASE_URL+"images/printgtrainer/img_aluno03.png"
                    },
                    {"title": "The Fighter",
                        "image": BASE_URL+"images/printgtrainer/img_aluno04.png"
                    }
                ]
            });
        </script>                
        <!-- end item template -->
    </div> <!-- content -->
</div>

