<div class="panel panel-default">
  <div class="panel-body">
  	<h3 style="margin: 0 0 30px 0">
  		Solicitação de renovação concluído
  	</h3>

  	<h5>
		<ul style="margin-right: 2em;">
			<li class="text-justify">Caso você tenha efetuado o pagamento no cartão, seu acesso já está liberado, <b><a style="color: green" href="<?= $this->baseUrl().'/index/login' ?>">clique aqui</a></b> para começar a usar</li>
			<hr>
			<li class="text-justify">
				Se você irá efetuar o pagamento via boleto, seu acesso será liberado até 24 horas após o pagamento.
			</li>
		</ul>
  	</h5>
  </div>
</div>

