<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
<style>
    * {font-family: Arial;}
    table th {background: #ccc; font-size: 14px;}
    table tr td {background: #fff; font-size: 14px; padding: 3px;}
    table,th,td { border-collapse:collapse; }
    
    table#tableTitle tr td{ font-size: 14px; padding: 0; }
</style>
<script>
jQuery(function(){
    carregarFrequencia();
})    

function imprimirTreino(ficha_id, aluno_id) {
    
    window.open("<?= $this->baseUrl() ?>/index/impressao?ficha_id="+ficha_id+"&matricula="+aluno_id,"Impressao","location=no,directories=no,scrollbars=yes,menubar=no,statusbar=no,resize=yes,width=600,height=700");
    
}

function carregarFrequencia(){
    $('#showFrequencia').load(BASE_URL+'admin/carregar-frequencia', {ficha_id: $('#ficha_id').val()});
}
</script>

<?php #Utils_Print::printvardie($this->dadosFicha); ?>


<input type="hidden" id="ficha_id" value="<?= $this->ficha_id; ?>" />

<div class="page-content">
            
            <table id="tableTitle" width="100%" style="margin-bottom: 5px;">
                
                <!--
                <tr>
                 <td valign="top" rowspan="6" width="9%">   
                    <img src="<?php echo $this->baseUrl() ?><?php echo $this->dadosFicha['foto']; ?>" width="100" height="100" style="padding-right: 5px;" />  
                 </td>
                </tr>                         
                -->  
                <tr>
                    <td valign="top" width="9%"><b>Descri&ccedil;&atilde;o: </b></td>
                    <td style="padding-left: 5px;"><b><?= utf8_encode($this->dadosFicha['ds_ficha']); ?></b></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Aluno(a): </b></td>
                    <td style="padding-left: 5px;"><?php echo utf8_encode($this->dadosAluno['nome']) ?> - <b>Mat.: </b><?php echo $this->dadosAluno['matricula'] ?></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Professor(a): </b></td>
                    <td style="padding-left: 5px;"><?= utf8_encode($this->dadosFicha['nm_professor']); ?></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Objetivo:</b></td>
                    <td style="padding-left: 5px;">
                        <?php if( isset($this->dadosFicha['objetivo']) && !empty($this->dadosFicha['objetivo']) ): ?>
                            <?= ($this->dadosFicha['objetivo']); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Observação:</b></td>
                    <td style="padding-left: 5px;">
                        <?php if( isset($this->dadosFicha['observacao']) && !empty($this->dadosFicha['observacao']) ): ?>
                            <?= ($this->dadosFicha['observacao']); ?>
                        <?php endif; ?>
                    </td>
                </tr>
                <!--<tr>
                    <td colspan="2" valign="baseline">
                        <a href="<?= $this->baseUrl() ?>/index/impressao?ficha_id=<?= $this->dadosFicha['id'] ?>&matricula=<?= $this->dadosAluno['matricula'] ?>" style="background: #9cf; text-decoration: none; color: #000; border: 1px solid #009ceb; padding: 3px 7px 3px 5px; font-weight: bold;">
                            <img src="<?php echo $this->baseUrl() ?>/images/acao/ico-download.png" /> Download
                        </a>
                    </td>
                </tr>-->
            </table>
            
            
            <div id="gridTreinos">
                <?php if(count($this->aTreinoFicha) > 0 ): ?>                
                
                    <?php if($this->aTreinoFicha){ ?>

                            <?php foreach($this->aTreinoFicha as $treino => $aLista){ ?>
                            <table class="table table-striped" width="100%" border="1" style="margin: 0 auto;">
                                    <tr>
                                        <th colspan="<?= (isset($this->cond[$treino]))? (6+$this->cond[$treino]) : 6; ?>" style="text-align: center; background: #ccc;">TREINO "<?= $treino; ?>"</th>
                                    </tr>
                                    <tr>
                                            <th width="<?= (isset($this->cond[$treino]))? '56%' : '64%'; ?>">Exerc&iacute;cio</th>
                                            <th width="8%" style="text-align: center;">S&eacute;rie</th>
                                            <th width="10%" style="text-align: center;">Repet.</th>
                                            <th width="8%" style="text-align: center;">Carga</th>

                                            <?php if( isset($this->cond[$treino]) ): ?>
                                                    <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                            <th width="8%" style="text-align: center;">Carga</th>
                                                    <?php } ?>
                                            <?php endif; ?>

                                            <th width="10%" colspan="<?= (isset($this->cond[$treino]))? $this->cond[$treino] : 0; ?>" style="text-align: center;">Interv.</th>
                                    </tr>
                                    <?php $j=0; ?>
                                    <?php foreach($aLista as $key => $lista){ ?>

                                            <tr bgColor="<?php echo ($j%2==1)? '#eee' : ''; ?>">
                                                    <td width="<?= (isset($this->cond[$treino]))? '56%' : '64%'; ?>"><?= utf8_encode($lista['exercicio']) ?> <?= ($lista['detalhes']? "({$lista['detalhes']})" : '') ?></td>
                                                    <td width="8%" align="center"><?= $lista['series'] ?></td>
                                                    <td width="10%" align="center"><?= $lista['repeticoes'] ?></td>
                                                    <td width="8%" align="center"><?= $lista['carga1'] ?></td>

                                                    <?php
                                                        if(isset($lista['carga2'])):
                                                                foreach($lista['carga2'] as $lisCarga): ?>
                                                                        <td width="8%" align="center"><?= $lisCarga['carga']; ?></td><?php
                                                                endforeach;

                                                                $totCargaTreinoAtual = count($lista['carga2']);
                                                                $preenche = ($this->cond[$treino] - $totCargaTreinoAtual);


                                                                for($x=1; $x<=$preenche; $x++){ ?>
                                                                        <td width="10%" align="center">-</td>
                                                                <?php }

                                                        else: ?>
                                                                <?php if( isset($this->cond[$treino]) ): ?>
                                                                        <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                                                <td width="10%" align="center">-</td>
                                                                        <?php } 
                                                                endif;
                                                        endif;
                                                    ?>

                                                    <td width="10%" align="center"><?= $lista['intervalo'] ?></td>
                                            </tr>
                                    <?php $j++; ?>    
                                    <?php } ?>    
                            </table>
                            <br>
                            <?php } ?>
                    <?php } ?>    
                    
                    <table width="100%" border="1" class="table table-striped" id="tableDados">
			    <tr>
			        <th style="text-align: center; background: #ccc;" colspan="5">Periodiza&ccedil;&atilde;o</th>
			    </tr>
			    <tr>
			        <th style="background: #ccc;">Sess&atilde;o</th>
			        <th style="background: #ccc;">Descri&ccedil;&atilde;o</th>
			        <th style="background: #ccc; text-align: center;">Dias</th>
			        <th style="background: #ccc; text-align: center;">Data Fim</th>
			    </tr>
			
			    <?php if($this->aPeriodizacao['total'] > 0): ?>
			        <?php $aPeriodizacao = $this->aPeriodizacao['results']; ?>
			
			
			
			            <?php foreach ($aPeriodizacao as $item): ?>
			                <tr>
			                    <td><?= $item['treino'] ?>a Sess&atilde;o</td>
			                    <td><?= $item['descricao'] ?></td>
			                    <td align="center"><?= $item['count'] ?>/<?= $item['dias'] ?></td>
			                    <td align="center"><?= Utils_Date::formataDataSemHoraToShow($item['dt_fim']) ?></td>
			                </tr>
			            <?php endforeach; ?>
			
			    <?php else: ?>
			            <tr>
			                <td align='center' colspan="5">Adicione a periodiza&ccedil;&atilde;o do aluno.</td>
			            </tr>
			    <?php endif; ?>
			
		     </table>  
			
                            
                <?php else: ?>                        
		        <b><?= $this->sessao->nome ?></b>, nenhum exerc&iacute;cio foi adicionado ao treino.			
                <?php endif; ?>            

            </div>
            
            <div id="showFrequencia"></div>
</div>