<link rel='stylesheet' type='text/css' href="<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
        
<style>
    * {font-family: Arial;}
    table tr {background: #ccc; font-size: 35px;}
    table tr td {background: #fff; font-size: 35px; padding: 3px;}
    table,th,td { border-collapse:collapse; }
    
    table#tableTitle tr td{ font-size: 35px; padding: 0; }
</style>
<script>


$(function(){
    $('#showPeriodizacaoPreview').load(BASE_URL+'admin/grid-periodizacao-preview', {ficha_id: $('#ficha_id').val()});
})

function imprimirTreino(ficha_id, aluno_id) {
    
    window.location = BASE_URL+"index/impressao?ficha_id="+ficha_id+"&matricula="+aluno_id;
    
}
</script>
<?php #Utils_Print::printvardie($this->dadosFicha); ?>

<div style="font-size: 40px; font-weight: bold; text-align: center; background: #111; border-top: 1px solid #ddd; padding: 7px; margin: 0 0 5px;">
	
	<table wisth="100%">
	 <tr>
	   <td width="10%" style="background: #111;">
	     <a href="#" onclick="history.go(-1)" class="btn btn-primary" style="font-size: 35px; float: left;"> < </a>
	   </td>
	   <td width="80%" align="center" style="background: #111; color: #fff; font-size: 40px; font-weight: bold;"><?= utf8_encode($this->dadosFicha['ds_ficha']); ?></td>
	   <td width="10%" style="background: #111; padding: 0 10px 0 0;">
               <!--<a href="<?= $this->baseUrl() ?>/index/impressao?ficha_id=<?= $this->dadosFicha['id'] ?>&matricula=<?= $this->dadosAluno['matricula'] ?>">
                 <img src="<?= $this->baseUrl() ?>/images/acao/ico-download2.png" />
              </a>-->
              <a href="">&nbsp;</a>
	   </td>  	   
	 </tr>
	</table>
	
</div>

<div class="page-content">
            <input type="hidden" id="baseUrl" value="<?= $this->baseUrl() ?>" />
            <input type="hidden" id="ficha_id" value="<?= $this->dadosFicha['id'] ?>" />
            
            
            <table id="tableTitle" width="100%" style="margin-bottom: 5px;">
                
                
                <tr>
                 <td valign="top" rowspan="6" width="20%">   
                    <?php if($this->dadosAluno['foto']): ?>
		          <img src="<?= $this->baseUrl() ?><?= $this->dadosAluno['foto']; ?>" width="100%" style="padding-right: 5px;" />
		    <?php else : ?>
		          <img src="<?= $this->baseUrl().'/images/fotos/default.jpg' ?>" width="100%" style="padding-right: 5px;" />
		    <?php endif; ?>   
                      
                 </td>
                </tr>                         
                  
                <tr>
                    <td valign="top" width="9%"><b>Matr&iacute;cula: </b></td>
                    <td valign="top" style="padding-left: 5px;"><?php echo $this->dadosAluno['matricula'] ?></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Aluno(a): </b></td>
                    <td valign="top" style="padding-left: 5px;"><?php echo utf8_encode($this->dadosAluno['nome']) ?></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Professor: </b></td>
                    <td valign="top" style="padding-left: 5px;"><?= utf8_encode($this->dadosFicha['nm_professor']); ?></td>
                </tr>
                <tr>
                    <td valign="top" width="9%"><b>Objetivo:</b></td>
                    <td valign="top" style="padding-left: 5px;">
                        <?php if( $this->dadosFicha ): ?>
                            <?= utf8_encode($this->dadosFicha['objetivo']); ?>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>
            
            
            <div id="gridTreinos">
                <?php if(count($this->aTreinoFicha) > 0 ): ?>                
                
                    <?php if($this->aTreinoFicha){ ?>

                            <?php foreach($this->aTreinoFicha as $treino => $aLista){ ?>
                            <table class="table table-striped" width="100%" border="1" style="margin: 0 auto;">
                                    <tr>
                                        <th colspan="<?= (isset($this->cond[$treino]))? (6+$this->cond[$treino]) : 6; ?>" style="text-align: center; background: #ccc;">TREINO "<?= $treino; ?>"</th>
                                    </tr>
                                    <tr>
                                            <th width="<?= (isset($this->cond[$treino]))? '56%' : '64%'; ?>">Exerc&iacute;cio</th>
                                            <th width="8%" style="text-align: center;">S&eacute;rie</th>
                                            <th width="10%" style="text-align: center;">Rep.</th>
                                            <th width="8%" style="text-align: center;">Kg</th>

                                            <?php if( isset($this->cond[$treino]) ): ?>
                                                    <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                            <th width="8%" style="text-align: center;">Kg</th>
                                                    <?php } ?>
                                            <?php endif; ?>

                                            <th width="10%" colspan="<?= (isset($this->cond[$treino]))? $this->cond[$treino] : 0; ?>" style="text-align: center;">Inter.</th>
                                    </tr>
                                    <?php $j=0; ?>
                                    <?php foreach($aLista as $key => $lista){ ?>

                                            <tr bgColor="<?php echo ($j%2==1)? '#eee' : ''; ?>">
                                                    <td width="<?= (isset($this->cond[$treino]))? '56%' : '64%'; ?>"><a href="<?= $this->baseUrl() ?>/index/ver-exercicio/exercicio_id/<?=  $lista['exercicio_id'] ?>"><?= utf8_encode($lista['exercicio']) ?></a></td>
                                                    <td width="8%" align="center"><?= $lista['series'] ?></td>
                                                    <td width="10%" align="center"><?= $lista['repeticoes'] ?></td>
                                                    <td width="8%" align="center"><?= $lista['carga1'] ?></td>

                                                    <?php
                                                        if(isset($lista['carga2'])):
                                                                foreach($lista['carga2'] as $lisCarga): ?>
                                                                        <td width="8%" align="center"><?= $lisCarga['carga']; ?></td><?php
                                                                endforeach;

                                                                $totCargaTreinoAtual = count($lista['carga2']);
                                                                $preenche = ($this->cond[$treino] - $totCargaTreinoAtual);


                                                                for($x=1; $x<=$preenche; $x++){ ?>
                                                                        <td width="10%" align="center">-</td>
                                                                <?php }

                                                        else: ?>
                                                                <?php if( isset($this->cond[$treino]) ): ?>
                                                                        <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                                                <td width="10%" align="center">-</td>
                                                                        <?php } 
                                                                endif;
                                                        endif;
                                                    ?>

                                                    <td width="10%" align="center"><?= $lista['intervalo'] ?></td>
                                            </tr>
                                    <?php $j++; ?>    
                                    <?php } ?>    
                            </table>
                            <br>
                            <?php } ?>
                    <?php } ?>    
                    
                    <div id="showPeriodizacaoPreview" style="text-align: center; font-size: 16px; font-weight: bold;">
                    <table width="100%" class="table table-striped" border="1" id="tableDados">
			    <tr>
			        <th style="text-align: center; background: #ccc;" colspan="5">Periodiza&ccedil;&atilde;o</th>
			    </tr>
			    <tr>
			        <th style="background: #ccc;">Sess&atilde;o</th>
			        <th style="background: #ccc;">Descri&ccedil;&atilde;o</th>
			        <th style="background: #ccc;">Dias</th>
			    </tr>
			
			    <?php if($this->aPeriodizacao['total'] > 0): ?>
			        <?php $aPeriodizacao = $this->aPeriodizacao['results']; ?>
			
			            <?php foreach ($aPeriodizacao as $item): ?>
			                <tr>
			                    <td height="30"><?= $item['treino'] ?>a Sess&atilde;o</td>
			                    <td><?= $item['descricao'] ?></td>
			                    <td><?= $item['count'] ?>/<?= $item['dias'] ?></td>
			                </tr>
			            <?php endforeach; ?>
			
			    <?php else: ?>
			            <tr>
			                <td align='center' colspan="5">Adicione a periodiza&ccedil;&atilde;o do treino.</td>
			            </tr>
			    <?php endif; ?>
			
			</table> 
                    </div>
                            
                <?php else: ?>                        
		        <b><?= ($this->sessao->nome) ?></b>, nenhum exerc&iacute;cio foi adicionado ao treino.			
                <?php endif; ?>            

            </div>

</div>
<br><br>