<html>
    <head>
        <title>GTrainer- Gerenciador de Treinos</title>
        <link rel='shortcut icon' type='image/png' href="<?php echo $this->baseUrl() ?>/images/icon-gtrainer.png" />
        <link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
        <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
        <script>BASE_URL = '<?php echo $this->baseUrl().'/'; ?>'; </script>
        <style>
            * { font-family: sans-serif; }
        </style>        
        
        <?php //Utils_Print::printvardie($this->baseUrl()); ?>
    </head>
    <body>
        
        
        <div>
            <?php echo $this->layout()->content; ?>
        </div>
        
    </body>
</html>