<!DOCTYPE html>
<html>

<!-- Mirrored from ezbill.com.br/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 05 Nov 2014 23:19:50 GMT -->
<!-- Added by HTTrack --><!-- /Added by HTTrack -->
<head>
    <title>Gtrainer</title>
    <meta property="og:title" content="Gtrainer" />
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta property="og:description" content="Monte e acompanhe o treino dos seus alunos a qualquer hora e em qualquer lugar." />
    <meta property="og:image" content="<?= $this->baseUrl() ?>/images/site/logo-sistema-mini.png" />
    <meta property="og:url" content="www.gtrainer.com.br" />
    <meta property="og:site_name" content="GTrainer" />
    <meta name="description" content="O GTrainer é um aplicativo que auxilia os profissionais de academias (Personal Trainer) a realizarem a montagem e acompanhamento dos treinos dos seus alunos, dentro ou fora da academia." />
    <meta name="author" content="GTrainer" />
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <!--<meta http-equiv="content-type" content="text/html;charset=ISO-8859-1" />-->

    <link rel='shortcut icon' type='image/png' href="<?php echo $this->baseUrl() ?>/images/icon-gtrainer.png" />
    <link rel='stylesheet' type='text/css' href="<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>">
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/fonts.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/plugins.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/icones.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/template.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/jquery.qtip.min.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/Inicio.css" />
    <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/PlanosPrecos.css" />
        
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/site/jquery.qtip.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/site/scripts.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/site/Inicio.js"></script>
    <script>BASE_URL = '<?php echo $this->baseUrl().'/'; ?>'; </script>
</head>
<body>
    
    <?php echo $this->layout()->content; ?>
    
    
</body>

<!-- Mirrored from ezbill.com.br/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 05 Nov 2014 23:21:03 GMT -->
</html>