<?php #Utils_Print::printvardie($_SESSION); ?>
<style>
    .menu-text {font-size: 16px;}
</style>

<div id="sidebar" class="sidebar" style="display: block-inline; width: 20%; float: left; border: 1px solid #ccc;">
    <ul class="nav nav-list" style="top: 0px; background: #F5F5F5; height: 95%;">
        <li class="hsub" onclick="changePage('home')" style="border-top: none;">
            <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-home"></i>
                    <span class="menu-text"> Home </span>
            </a>
        </li>
        <li class="hsub" onclick="changePage('aluno')">
            <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-users"></i>
                    <span class="menu-text"> Alunos </span>
            </a>
        </li>
        <?php if($this->sessao->perfil_id == 1 || $this->sessao->perfil_id == 3): ?>
            <li class="hsub" onclick="changePage('professores')">
                <a class="dropdown-toggle" href="#">
                        <i class="menu-icon fa fa-users"></i>
                        <span class="menu-text"> Professores </span>
                </a>
            </li>
        <?php endif; ?>

        <li class="hsub" onclick="changePage('musculo')">
            <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-sitemap"></i>
                    <span class="menu-text"> Grupos Muscular </span>
            </a>
        </li>
        <li class="hsub" onclick="changePage('exercicio')">
            <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-list-alt"></i>
                    <span class="menu-text"> Exerc&iacute;cios </span>
            </a>
        </li>
        <li class="hsub" onclick="changePage('avaliacao')">
            <a class="dropdown-toggle" href="#">
                <i class="menu-icon fa fa-tags"></i>
                <span class="menu-text"> Avalia&ccedil;&atilde;o F&iacute;sica </span>
            </a>
        </li>
        <li class="hsub" onclick="changePage('montar-treino')">
            <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-edit"></i>
                    <span class="menu-text"> Montar Treino </span>
            </a>
        </li>

        <?php if($this->sessao->perfil_id == 1): ?>
          <li class="hsub" onclick="changePage('academia')">
             <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-tag"></i>
                    <span class="menu-text"> Academia </span>
             </a>
          </li>
        <?php endif; ?>

        <?php if($this->sessao->perfil_id == 1): ?>
          <li class="hsub" onclick="changePage('usuario')">
             <a class="dropdown-toggle" href="#">
                    <i class="menu-icon fa fa-user"></i>
                    <span class="menu-text"> Usu&aacute;rio </span>
             </a>
          </li> 
        <?php endif; ?>               
    </ul>
</div>