<html>
    <head>
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	
        <title>Gtrainer</title> 
        
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        
	<link rel='shortcut icon' type='image/png' href="<?php echo $this->baseUrl() ?>/images/favicon.png" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/js/jquery/jquery-mobile/css/jquery.mobile-1.3.0.css" />        
        <script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-mobile/js/jquery.mobile-1.3.0.min.js"></script>
        <script>BASE_URL = '<?php echo $this->baseUrl() ?>/'; </script>
        
        <style>
            * { font-family: sans-serif; }            
        </style>
        <script type="text/javascript">			
            function changePage(page) {
            	openAguarde();
                window.location = "<?= $this->baseUrl() ?>/admin/"+page;
            }
            
            function openAguarde() {
		     $.mobile.loading( 'show', {
				text: 'Aguarde...',
				textVisible: true,
				theme: 'a',
				html: ""
		     });
	    }
	    
	    function closeAguarde() {
	         $.mobile.loading( "hide" );
	    }
        </script>
    </head>
    <body>
        	
		
        <div data-role="page" class="type-interior">            
                <?php echo $this->layout()->content; ?>            
        </div>
        
    </body>
</html>