<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>

<a class="navbar-brand" href="<?= $this->baseUrl() ?>/admin/index">Gtrainer</a>
</div>

<?php $auth = Zend_Auth::getInstance(); ?>
<?php if($auth->hasIdentity()): ?>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
      <!--<li><a href="<?= $this->baseUrl() ?>/admin/index">Home</a></li>-->
      <li><a href="<?= $this->baseUrl() ?>/admin/aluno">Meus Alunos</a></li>
      <li><a href="<?= $this->baseUrl() ?>/admin/modalidade">Modalidades</a></li>
      <li><a href="<?= $this->baseUrl() ?>/admin/grupo-muscular">Grupo Muscular</a></li>
      <li><a href="<?= $this->baseUrl() ?>/admin/exercicio">Lista de Exercícios</a></li>

      <?php if(isset($_SESSION['usuario']->perfil_id)): ?>
        <?php if($_SESSION['usuario']->perfil_id == 1 || $_SESSION['usuario']->perfil_id == 3): ?>
          <li><a href="<?= $this->baseUrl() ?>/admin/professores">Professor</a></li>
        <?php endif; ?>
      <?php endif; ?>

      <li><a href="<?= $this->baseUrl() ?>/admin/treinos">Treinos</a></li>
      <li><a href="<?= $this->baseUrl() ?>/admin/avaliacao-fisica">Avaliação Física</a></li>
  </ul>

  <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

        <!-- Nome no navbar -->
        <?php if(isset($_SESSION['usuario']->perfil_id)): ?>
          <?php if($_SESSION['usuario']->perfil_id == 3 || $_SESSION['usuario']->perfil_id == 1): ?>
              <span><?php echo utf8_encode($_SESSION['usuario']->academia_nome); ?></span>
          <?php else: ?>
              <span><?php echo utf8_encode($_SESSION['usuario']->nome); ?></span>
          <?php endif; ?>
        <?php endif; ?>

        <!-- Foto do usuário -->
        <?php if(isset($_SESSION['usuario'])): ?>
          <img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$_SESSION['usuario']->id ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle" height="28" width="28">
        <?php endif; ?>
          <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
          <?php if(isset($_SESSION['usuario']->perfil_id)): ?>
            <?php if($_SESSION['usuario']->perfil_id == 1 || $_SESSION['usuario']->perfil_id == 2 || $_SESSION['usuario']->perfil_id == 3): ?>
              <li><a href="<?= $this->baseUrl() ?>/admin/renovar-plano">Meus planos</a></li>
            <?php endif; ?>
          <?php endif; ?>
          <li>
            <a href="#" data-toggle="modal" data-target="#modal-trocar-senha">
                Trocar minha senha
            </a>
          </li>
          <li class="divider"></li>
          <li>
          <a href="<?php echo $this->baseUrl() ?>/admin/logout">
              Sair
          </a>
          </li>
      </ul>
      </li>
  </ul>
  </div><!-- /.navbar-collapse -->
<?php endif; ?>

<div id="modal-trocar-senha" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"><i class="glyphicon glyphicon-key"></i>Trocar senha</h4>
        </div>
        <div class="modal-body">
          <?= $this->render('admin/trocar-senha.phtml') ?>
        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

