<div class="panel panel-default">
  	<div class="panel-body">
	  	<h3 style="margin: 0 0 30px 0">
	  		Criar Ficha de Treino
	  	</h3>
		<form id="form" action="<?= $this->baseUrl().'/admin/salvar-ficha-treino' ?>"  method="POST"  onsubmit="exercicioTreino.salvar(event)">

			<input type="hidden" name="id" id="id" value="<?= isset($this->treino['id'])? $this->treino['id'] : '' ?>">

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
					    <label for="nome">Aluno</label>
					    <select name="aluno" id="aluno" class="form-control" required data-toggle="modal" data-target="#modal-alunos">
							<option value="<?= $this->treino['fk_aluno'] ?>"><?= utf8_encode($this->treino['aluno']) ?></option>
					    	<option value="">Selecione um aluno...</option>
					    </select>
					</div>
				</div>
			</div>
			<div class="row">
			  	<div class="col-xs-12">
			  		<div class="form-group">
					    <label for="objetivo">Início do treino</label>
					    <input type="date" name="dtInicio" id="dtInicio" class="form-control" required value="<?= isset($this->treino['dt_inicio_us'])? $this->treino['dt_inicio_us'] : '' ?>">
				  	</div>
			  	</div>
			  	<!--<div class="col-xs-6">
			  		<div class="form-group">
					    <label for="objetivo">Data de término</label>
					    <input type="date" name="dtTermino" id="dtTermino" class="form-control" value="<?= isset($this->treino['dt_termino_us'])? $this->treino['dt_termino_us'] : '' ?>" required>
				  	</div>
			  	</div>
			  -->
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
						<label for="objetivo">Objetivo resumido</label>
						<textarea name="objetivo" id="objetivo" cols="30" rows="3" class="form-control" placeholder="ganho de massa muscular..." required><?= isset($this->treino['objetivo'])? utf8_encode($this->treino['objetivo']) : '' ?></textarea>
				  	</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
					    <label for="telefone">Observações</label>
					    <textarea name="observacao" id="observacao" cols="30" rows="6" class="form-control" placeholder="mais detalhes do treino..."><?= isset($this->treino['observacao'])? utf8_encode($this->treino['observacao']) : '' ?></textarea>
					</div>
				</div>
			</div>

			<div class="col-md-12">
				<div id="msg-load" class="hidden alert alert-warning">
				  	Aguarde...
		 	    </div>
		 	</div>

			<div class="row">
				<div class="col-md-12">
				  <div class="form-group">
				  	<button type="submit" class="btn btn-primary btn-block">Salvar</button>
					<!--
					<button type="button" id="bt-deletar" onclick="exercicioTreino.deletar(this)" data-url="<?= $this->baseUrl().'/admin/deletar-treino/id/'.$this->treino['id'] ?>" class="btn btn-danger pull-right"><i class="glyphicon glyphicon-trash"></i></button>
					-->
				  	<a href="<?= $this->baseUrl() ?>/admin/treinos" class="btn btn-default btn-block">Cancelar</a>
				  </div>
				</div>
			</div>
		</form>
	</div>
</div>

<div id="modal-alunos" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    	<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Selecione um aluno</h4>
      	</div>
      	<div class="modal-body">
      		<div class="form-group has-default has-feedback" style="margin: 5px 0 0 0">
			  <input type="text" class="form-control" onkeyup="lista.search(this.value)" placeholder="Pesquisar aluno...">
			  <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
			  <span id="inputSuccess2Status" class="sr-only">(success)</span>
			</div>
      		<div class="list-group">
      		<?php if(count($this->alunos)): ?>
				<?php foreach($this->alunos as $key => $value): ?>
				  <?php if($value['situacao'] == 1): ?>    
				  <a href="#!" onclick="exercicioTreino.selecionaAluno(<?= $value['id'] ?>, '<?= $value['nome'] ?>')" class="list-group-item">
				    <img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$value['fk_usuario'] ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle pull-left" height="45" width="40" style="margin-right: 10px" data-toggle="modal" data-target=".fade_<?= $key ?>">
				    <strong><?= utf8_encode($value['nome']) ?></strong><br>
				    <p class="list-group-item-text" style="margin-bottom: 0.7em;">
				    	<?= $value['email'] ?>
				    </p>
				  </a>
				  <?php endif; ?>
				<?php endforeach; ?>
			<?php else: ?>
				<div class="alert alert-warning">Nenhum aluno cadastrado!</div>
			<?php endif; ?>
			</div>
		</div>
	</div>
  </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/app/helpers/ListGroup.js' ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/app/controllers/TreinosController.js' ?>"></script>
<script type="text/javascript">
	var lista = new ListGroup();
	var exercicioTreino = new TreinosController();
</script>