<div class="panel panel-default">
      <div class="panel-body">
	    <h3 style="margin: 0 0 5px 0">Fichas de treinos
		    <a href="<?= $this->baseUrl().'/admin/create-ficha-treino' ?>" class="btn btn-primary btn-lg btn-circulo pull-right btn-flutuante" title="Cadastrar nova ficha de treino"><i class="glyphicon glyphicon-plus"></i></a>
	    </h3>
	    <br>

	    <?php if(isset($this->treinos) && count($this->treinos) > 0): ?>
		    <div class="form-group has-default has-feedback" style="margin: 10px 0 5px 0">
			    <input type="text" class="form-control" onkeyup="lista.search(this.value)" placeholder="Pesquisar por um treino..." style="border-radius: 50px;">
			    <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true" style="margin-top: -1.8em;"></span>
			    <span id="inputSuccess2Status" class="sr-only">(success)</span>
		    </div>

		    <div class="list-group">
			<?php foreach($this->treinos as $value): ?>
			    <a href="<?= $this->baseUrl().'/admin/treino-aluno/id/'.$value['id'] ?>" class="list-group-item">
			      <img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$value['id_usuario'].'/foto_'.$value['filename'] ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle pull-left" height="50" width="45" style="margin-right: 10px">

			      <strong><?= utf8_encode($value['aluno']) ?></strong><br>

			      <p class="list-group-item-text">
				  Iniciado em <?= $value['dt_inicio'] ?>

				  <div class="btn-group pull-right" role="group" style="margin-top: -2em;">
				    <button onclick="window.location=this.dataset.url; return false;" data-url="<?= $this->baseUrl().'/admin/treino-aluno/id/'.$value['id'].'/favoritar/true' ?>" onclick="window.location = this.dataset.url" type="button" class="btn btn-sm btn-circle" title="Favoritar este treino">
					<?php if(isset($this->aAlunosFavoritos) && in_array($value['fk_aluno'], $this->aAlunosFavoritos)): ?>
						<i class="glyphicon glyphicon-star" style="color: darkorange; cursor: pointer;"></i>
		  			<?php else: ?>	
						<i class="glyphicon glyphicon-star-empty" title="Editar treino"></i>
					<?php endif; ?>	
				    </button>
				  </div>
			      </p>
			    </a>
			<?php endforeach; ?>
			</div>
	    <?php else: ?>
	    	<div class="alert alert-warning">Nenhum treino cadastrado!</div>
	    <?php endif; ?>
	</div>
</div>