<div class="panel panel-default">
  <div class="panel-body">
	  	<h3 style="margin: 0 0 30px 0">
	  		Editar carga do exercício
	  	</h3>

	  	<form id="form" action="<?= $this->baseUrl().'/aluno/salvar-exercicio-treino' ?>"
			method="POST"  onsubmit="oController.salvarExercicio(event)">

		  <input type="hidden" name="id" id="id" value="<?= (isset($this->id) && !empty($this->id))? $this->id : '' ?>">

			<div class="row">
			 	<div class="col-md-3">
				  <div class="form-group">
				    <label for="objetivo">Treino *</label>
				    <select name="treino" id="treino" class="form-control" disabled>
				    	<?php if(isset($this->exercicio['treino']) && !empty($this->exercicio['treino'])): ?>
							<option value="<?= $this->exercicio['treino'] ?>">
								<?= utf8_encode($this->exercicio['treino']) ?>
							</option>
				    	<?php endif; ?>
				    </select>
				  </div>
			    </div>

			 	<div class="col-md-offset-3 col-md-6">
				  <div class="form-group">
				    <label for="nome">Exercício *</label>
				    <select name="exercicio" id="exercicio" class="form-control" disabled>
				    <?php if(isset($this->exercicio['fk_exercicio']) && !empty($this->exercicio['fk_exercicio'])): ?>
						<option value="<?= $this->exercicio['fk_exercicio'] ?>"><?= utf8_encode($this->exercicio['exercicio']) ?></option>
				    	<?php endif; ?>
				    </select>
				  </div>
				</div>
			</div>

			<div class="row">
			  <div class="col-md-6 col-xs-5">
				  <div class="form-group">
				    <label for="objetivo">Series *</label>
				    <input type="text" class="form-control" id="series" name="series" value="<?= (isset($this->exercicio['series']) && !empty($this->exercicio['series']))? $this->exercicio['series'] : '' ?>" readonly>
				  </div>
			  </div>
			  <div class="col-md-6 col-xs-7">
				  <div class="form-group">
				    <label for="objetivo">Carga</label>
				    <input type="text" class="form-control" id="carga" name="carga" value="<?= (isset($this->exercicio['carga']) && !empty($this->exercicio['carga']))? $this->exercicio['carga'] : '' ?>">
				  </div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-xs-5">
				  <div class="form-group">
				    <label for="objetivo">Descanso *</label>
				    <input type="text" class="form-control" id="descanso" name="descanso" value="<?= (isset($this->exercicio['descanso']) && !empty($this->exercicio['descanso']))? $this->exercicio['descanso'] : '' ?>" readOnly>
				  </div>
				</div>
				<div class="col-md-6 col-xs-7">
				  <div class="form-group">
				    <label for="objetivo">Repetições/ tempo *</label>
				    <input type="text" class="form-control" id="repeticoesTempo" name="repeticoesTempo" required value="<?= (isset($this->exercicio['repeticoes_tempo']) && !empty($this->exercicio['repeticoes_tempo']))? $this->exercicio['repeticoes_tempo'] : '' ?>" readOnly>
				  </div>
			  	</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
					    <label for="telefone">Detalhes do treino</label>
					    <textarea name="detalhes" id="detalhes" cols="30" rows="2" readonly class="form-control"><?= (isset($this->exercicio['detalhes']) && !empty($this->exercicio['detalhes']))? utf8_encode($this->exercicio['detalhes']) : '' ?></textarea>
				    </div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="form-group">
					  	<button type="submit" class="btn btn-primary">Adicionar</button>
					  	<a type="button" href="<?= $this->baseUrl().'/aluno/treino-view/id/'.$this->id_treino ?>" class="btn btn-default">Voltar</a>
		     		</div>
				</div>
			</div>

		  	<div id="msg-load" class="hidden alert alert-warning">
		  		Aguarde...
		  	</div>

		</form>

	  </div>
</div>

<script type="text/javascript" src="<?= $this->baseUrl().'/js/app/controllers/TreinosController.js' ?>"></script>
<script type="text/javascript">
	var oController = new TreinosController();
</script>
