<div class="panel panel-default">
      <div class="panel-body">
	    <h3 style="margin: 0 0 5px 0">Fichas de treinos</h3>
	    <br>

	    <?php if(isset($this->treinos) && count($this->treinos) > 0): ?>
		    <div class="list-group">
			<?php foreach($this->treinos as $value): ?>
			    <a href="<?= $this->baseUrl().'/aluno/treino-view/id/'.$value['id'] ?>" class="list-group-item">
			      <img src="<?= $this->baseUrl().'/aluno/ver-foto-usuario/id/'.$value['id_usuario'].'/foto_'.$value['filename'] ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle pull-left" height="50" width="45" style="margin-right: 10px">

			      <strong><?= utf8_encode($value['aluno']) ?></strong><br>

			      <p class="list-group-item-text">
				  	<strong>Início do treino:</strong> <?= $value['dt_inicio'] ?> <?= isset($value['dt_termino'])? ' à '.$value['dt_termino'] : '' ?><br>

					<?php if(!$value['fk_professor']): ?>
						<strong>Professor:</strong> <?= utf8_encode($value['personal_academia']) ?>
					<?php endif; ?>

			      </p>
			    </a>
			<?php endforeach; ?>
			</div>
	    <?php else: ?>
	    	<div class="alert alert-warning">Nenhum treino cadastrado!</div>
	    <?php endif; ?>
	</div>
</div>