<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.form.js' ?>"></script>
<script>
jQuery(function(){
    initLoadModal()
    loadAcademias()
})

function loadAcademias() {
    $( "#gridAcademias" ).load(BASE_URL+'admin/grid-academias');
}

function initLoadModal() {
    $('#modalAcademia').dialog({
        autoOpen: false,
        modal: true,
        width: 500,
        height: 500
    })
    $('.ui-dialog-titlebar').hide();
}

function removerAcademia(id) {
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/remover-academia',
            data: { id: id },
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadAcademias();
                    alert(resp.msg);
                }
            }
    })
}

function salvarAcademia() {
    $( "#frmAcademia" ).ajaxSubmit({
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadAcademias();
                    $('#modalAcademia').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}

function alterarAcademia() {
    //$( "#frmAcademia" ).submit();
    
    $( "#frmAcademia" ).ajaxSubmit({
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadAcademias();
                    $('#modalAcademia').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}


function openModalAcademias() {
    
    $('#modalAcademia').load(BASE_URL+'admin/modal-academia').dialog({
        buttons: [
            {
                text: "Salvar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    salvarAcademia();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalAcademia').dialog( "open" );
}

function openModalAcademiaUpdate(id) {
    
    $('#modalAcademia').load(BASE_URL+'admin/modal-academia', {id: id}).dialog({
        buttons: [
            {
                text: "Alterar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    alterarAcademia();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalAcademia').dialog( "open" );
}
</script>


<div id="breadcrumbs" class="breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="#" onclick="changePage('home')">Home</a></li>
        <li class="active">Academia</li>
    </ul>
</div>

<div class="page-content">
    <h3 class="page-header">
        <i class="ace-icon fa fa-users"></i> Academias
    </h3>

    <div class="row">
        <div class="col-xs-12">        
        

            
            <button class="btn btn-success btn-primary" onclick="openModalAcademias()">
                <i class="ace-icon fa fa-plus"></i> Cadastrar Academia
            </button>
            
         <br><br>
            
         <div id="gridAcademias"></div>
         <div id="carregando"></div>
            
        </div>
    </div>

</div>

<div id="modalAcademia"></div>