<style>
  table th {background: #ccc;}
  table,th,td { border-collapse:collapse; }
</style>
<script>
jQuery(function(){
	ini_conteudo();
        ini_scroll();
})

function ini_scroll(){
	
	$(window).scroll(function() { 
	     if(($(window).scrollTop() + $(window).height() + 10) >= $(document).height()) {
	      	   $(window).unbind("scroll");			       
		   ini_conteudo();
	      }		      
	})  
}

function ini_conteudo()	{
	var params = {};	
	params.offset = $("#lista table").find("tr").length; //10;								
			
        loadGridAlunosRolagem(params);        
}
	
	
function loadGridAlunosRolagem(params){
     $.mobile.loading( 'show', {
		text: 'Aguarde...',
		textVisible: true,
		theme: 'a',
		html: ""
     });
     
     $.ajax({
          type: "post",
          url: BASE_URL+"admin/ver-mais-alunos",
          data: params,
          dataType: 'html',
          beforeSend: function() {
            openAguarde();
          },			
          complete: function() {
            ini_scroll();	
            $.mobile.loading( "hide" );	
          },        
          async: false,
          success: function(data) {
            $("#tableAlunos").append(data).show();
            ini_scroll();
          },
          error: function() {
            alert('erro');
          }
     });
}	


function openEditarAluno(id) {
    window.location = BASE_URL+'admin/modal-aluno/id/'+id;
}

function removerAluno(id) {
    openAguarde();
    
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/remover-aluno',
            data: { id: id },
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else {                                   
                    alert(resp.msg);
                    window.location.reload();
                }
            }
    })
}
</script>

<div id="loadDialog" class="show-page-loading-msg" data-textonly="false" data-textvisible="true" data-inline="true"></div>

<div data-role="header">
    <h1>Alunos</h1>
    <a href="<?= $this->baseUrl() ?>/" data-theme="b">
        <
    </a>
    <a href="javascript:changePage('modal-aluno')" data-theme="b">
        Novo
    </a>
</div>


    <!--<button data-theme="b" onclick="openCadastraNovoAluno()">Cadastrar novo aluno</button>-->

    <?php if($this->results['total'] == 0): ?>
        <div id="textAlerta" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
            <b><?= ($this->sessao->nome) ?></b>, nenhum aluno foi cadastrado.
        </div>
    <?php else:
    
        if($this->sessao->perfil_id != 3 && $this->sessao->perfil_id != 4):

	        $totValorSemana = 0;
	        $totValorMes    = 0;
	
	        foreach ($this->results['results'] as $dado):
	            $totValorSemana += ($dado['valor'] * $dado['qtd_aulas']);
	            $totValorMes    += (($dado['valor'] * $dado['qtd_aulas']) * 4 );
	        endforeach; ?>
	
	
	        <div id="textAlerta" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
	            <div style="text-align: left;">Valor a receber/semana: <b>R$ <?php echo Utils_Date::formataMoeda($totValorSemana) ?></b></div>
	            <div style="text-align: left;">Valor a receber/m&ecirc;s: <b>R$ <?php echo Utils_Date::formataMoeda($totValorMes) ?></b></div>
	        </div>
        
        <?php endif; ?>
        
        <div id="lista" style="margin-top: 5px;">
	        <table id="tableAlunos" class="table table-striped" width="100%" border="0"></table>
	</div>
	
    <?php endif; ?>    

