<div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 style="margin: 0">Lista de alunos
            <a href="{{ url('admin/aluno/create') }}" class="btn btn-primary btn-lg btn-circle pull-right" title="Cadastrar novo aluno"><i class="glyphicon glyphicon-plus"></i></a>
        </h3>
        <br>

        <div class="form-group has-default has-feedback" style="margin: 10px 0 0 0">
          <input type="text" class="form-control" onkeyup="lista.search(this.value)" placeholder="Pesquisar por um aluno...">
          <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
          <span id="inputSuccess2Status" class="sr-only">(success)</span>
        </div>

        <?php if(count($this->results) > 0): ?>
            <div class="list-group">
            <?php foreach($this->results as $key => $value): ?>
                  <a href="{{ url('admin/aluno/create/'.$value->id) }}" class="list-group-item">
                    <img src="{{ url('admin/aluno/ver-foto/'.$value->usuario->id) }}" data-error="{{ url('images/foto_default.png') }}" onerror="this.src=this.dataset.error" class="img img-circle pull-left" height="50" width="45" style="margin-right: 10px" data-toggle="modal" data-target=".fade_{{ $key }}">
                    <strong>{{ $value->nome }}</strong><br>
                    <p class="list-group-item-text">
                        <!--{{ $value->telefone }}-->
                        {{ $value->usuario->email }}

                        <div style="position: absolute; text-indent: 4.2em; font-size: 13px; color: #a7a7a7;">
                            {{ $value->telefone }}
                        </div>
                        <!--
                        <div class="btn-group pull-right" role="group" style="margin-top: -2em;">
                          <button data-url="{{ url('admin/aluno/create/'.$value->id) }}" onclick="window.location=this.dataset.url" type="button" class="btn btn-warning btn-sm btn-circle"><i class="glyphicon glyphicon-pencil" title="Editar aluno"></i></button>
                        </div>
                        -->
                    </p>
                  </a>
                  @if(isset($value->usuario->foto) && !empty($value->usuario->foto))
                    <div class="modal fade_{{ $key }}" tabindex="-1" role="dialog">
                      <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">{{ isset($value->nome)? $value->nome : '' }}</h4>
                            </div>
                            <div class="modal-body">
                                <img src="{{ url('admin/aluno/ver-foto/'.$value->usuario->id) }}" width="100%" class="img img-response">
                            </div>
                        </div><!-- /.modal-content -->
                      </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->
                  @endif
            @endforeach
            </div>
        @else
            <div class="alert alert-warning">Nenhum aluno cadastrado!</div>
        @endif
      </div>
    </div>
</div>


<script type="text/javascript" src="{{ url('js/app/helpers/ListGroup.js') }}"></script>
<script type="text/javascript">
    var lista = new ListGroup();
</script>
