<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
<script>
jQuery(function(){
    loadAvaliacao();
});

function loadAvaliacao() {
    $( "#gridAvaliacao" ).load(BASE_URL+'admin/grid-aluno-avaliacao');
}

function listarAvaliacoesAluno(matricula){
    var matricula = (matricula)? matricula : $('#P_matricula').val();

    if(matricula) {
        
        $.ajax({
            type:"post",
            url: BASE_URL+'admin/listar-avaliacoes-aluno',
            data: {matricula: matricula},
            async: false,
            success: function(respHTML){
                $('#contentGeral').html(respHTML).show();
            }
        });
    }

}
</script>

<div id="contentGeral">

    <div id="breadcrumbs" class="breadcrumbs">
        <ul class="breadcrumb">
            <li><a href="#" onclick="changePage('home')">Home</a></li>
            <li class="active">Pesquisar Aluno</li>
        </ul>
    </div>

    <div class="page-content">
        <h3 class="page-header">
            <i class="ace-icon fa fa-search-plus"></i> Pesquisar Aluno
        </h3>

        <div class="row">
            <div class="col-xs-12">


                <div id="gridAvaliacao"></div>
                <div id="carregando"></div>

                <div id="modal"></div>

            </div>
        </div>

    </div>

</div>