<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
<script src="<?php echo $this->baseUrl().'/js/admin/jsFichaAluno.js' ?>"></script>
<style>
  /*.table tr th { font-size: 20px; }
  .table tr td { font-size: 20px; }*/
  table {border-collapse: collapse }
</style>
<div data-role="header">
    <h1>Busque um Aluno</h1>
    <a href="<?= $this->baseUrl() ?>/" data-theme="b">
        <
    </a>
</div>

<div>

	<?php if($this->results['total'] == 0): ?>
		<div class="alert alert-block alert-warning" style="background: #f4dae5; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
			<b><?= ($this->sessao->nome) ?></b>, cadastre primeiro o aluno para depois montar sua Avalia&ccedil;&atilde;o F&iacute;sica.
		</div>
	<?php else: ?>
    
    
    <table class="table table-striped" width="100%" border="0">
	
        <?php foreach ($this->results['results'] as $i => $dado): ?>
            <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">
                <td width="5%">
                    <?php if($dado['foto']): ?>	                            	                
                       <img src="<?= $this->baseUrl() ?><?= $dado['thumbnail'] ?>" width="60" height="60" />
                    <?php else : ?>	 
                       <img src="<?= $this->baseUrl() ?>/images/fotos/default.jpg" width="60" height="60" />                           
                    <?php endif; ?> 
                </td>
                <td valign="top">	                                          
                     <?= ($dado['nome']) ?><br>                       
                     <?= $dado['email'] ?><br>
                     <b>Matr&iacute;cula: </b><?= $dado['matricula'] ?><br>
                </td>
                <td style="text-align: center;">

		<a href="javascript:changePage('listar-avaliacoes-aluno/matricula/<?= $dado['matricula']; ?>')" data-theme="b" data-role="button"  data-icon="search" data-mini="true">ver
		</a>

                </td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php endif; ?>    

</div>