<script type="text/javascript">
jQuery(function(){
    
    $('#ckVerSenha').click(function(){
        var value = $('input[name="ckVerSenha"]:checked').val();

        if(value == 'on'){
            $('#senhaCad').hide();
            $('#hdsenha').val( $('#senhaCad').val() ).show().focus();
        }else {
            $('#hdsenha').hide();
            $('#senhaCad').val( $('#hdsenha').val() ).show().focus();
        }
    })
    
    
    
    $('#btnCadastrar').click(function(){    
    
    	var nome  = $('#nome').val();
    	var email = $('#email').val();
    	var senhaCad = $('#senhaCad').val();
    	var confSenhaCad = $('#confSenhaCad').val();
    	
    	if(!nome){
    	    alert('Informe o seu nome completo'); return false;
    	}else
    	if(!email){
    	    alert('Informe o seu email'); return false;
    	}else
	if(!senhaCad){
    	    alert('Informe a senha'); return false;
    	}else
	if(!confSenhaCad){
    	    alert('Confirme a senha.'); return false;
    	}

	if(senhaCad != confSenhaCad){
	   alert('O confirmacao da senha esta diferente da senha informada.'); return false;
	}
    	
    
        openAguarde();
            
        $('#hdsenha').attr('disabled', true);    
        var params = $('.form-login-cad').serialize();
        
        $.ajax({
            type: 'post',
            url: BASE_URL+'admin/cadastrar-novo-usuario',
            data: params,
            dataType: 'json',
            success: function(resp) {
                if(resp.retorno != 'sucesso'){
                    closeAguarde();
                    $('#textAlerta').html(resp.msg).fadeIn('fast').delay(5000).fadeOut('fast');
                    return false;
                }else
                if(resp.retorno == 'sucesso'){
                    $('#textAlerta').html(resp.msg).fadeIn('fast').css('background', '#E4EFC9').delay(5000).fadeOut('fast');
                    
                    if( resp.url ){
	                window.location = resp.url; 
	            }else {
	            	logar();
	            }                  	  
                    
                    
                    //window.location = 'index';
                }
            }
        })
        
        return false;
    })
})

function logar() {
    openAguarde();
        
    var email = $('#email').val();
    var senha = $('#senhaCad').val();

    $.ajax({
        type: 'post',
        url: BASE_URL+'admin/autenticacao',
        data: {login: email, senha: senha},
        dataType: 'json',
        success: function(resp) {
            if(resp.retorno == 'erro'){
                $('#textAlerta').html(resp.msg).fadeIn('fast').delay(5000).fadeOut('fast');
                window.location = BASE_URL+'admin/login';
                return false;
            }else
            if(resp.retorno == 'info'){         
                $('#textAlerta').html(resp.msg).show();
                window.location = BASE_URL+'admin/login';
            }else
            if(resp.retorno == 'sucesso'){                
                window.location = 'index';
            }else{                    
                $('#textAlerta').html(resp.msg).fadeIn('fast').delay(5000).fadeOut('fast');
                window.location = BASE_URL+'admin/login';
            }
        }
    })
}

</script>
        

<div data-role="header">
    <h1>Gtrainer</h1>
    <a href="javascript:changePage('login')" data-theme="b"><</a>
    <a href="#" data-theme="b" id="btnCadastrar">Salvar</a>
</div>

<div id="textAlerta" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px; display: none;"></div>
<div id="count" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px; display: none;"></div>
		
<div class="main-content" data-role="content">
    <form class="form-login-cad">
    
    	<label>Tipo de usu&aacute;rio:</label>
    	<select name="rdTipo" id="rdTipo" class="form-control">
	        <!--<option value="">Selecione o tipo de usu&aacute;rio... </option>
	        <option value="3">Academia</option>-->
	        <option value="2">Personal</option>
        </select>
        
        <label>Nome:</label>
    	<input name="nome" id="nome" type="text" placeholder="Informe seu nome..." />
    	
    	<label>Plano:</label>
        <select name="cbTipoPlano" id="cbTipoPlano">
	        <option value="">Selecione um plano... </option>
	        <option value="1" selected="selected">Experimental - (30 dias GR&Aacute;TIS)</option>
	        <?php foreach($this->aPlanos as $plano): ?>
				<option value="<?= $plano['id'] ?>"><?= $plano['ds_plano'] ?> - R$ <?= $plano['valor'] ?></option>
			<?php endforeach; ?>
        </select>
        
        <label>Email:</label>
    	<input type="text" name="email" id="email" placeholder="Informe seu e-mail...">

	<label>Senha:</label>
	<input name="senhaCad" id="senhaCad" placeholder="Informe uma senha..." type="password" />
	
	<label>Confirmar a Senha:</label>
	<input name="confSenhaCad" id="confSenhaCad" placeholder="Confirme a senha..." type="password" />
	
	
        <!--<input name="hdsenha" id="hdsenha" style="display: none;" type="text" />

	<label><input type="checkbox" name="ckVerSenha" id="ckVerSenha"> Monstrar senha </label>-->

    </form>
</div>