<?php 
$resTreinos = null;

$treinos = array(1,2,3,4,5,6,7,8,9,10);

if(isset($this->aPeriod['results'])){

    $aPeriod = $this->aPeriod['results'];    
    
    
    $aTreinosBd = array();
    foreach ($aPeriod as $dado):
        $aTreinosBd[] = $dado['treino'];
    endforeach;
    
    $resTreinos = array_diff($treinos, $aTreinosBd);
    if(count($resTreinos)==0){
        $resTreinos = '-';
    }
}
?>

<!--<option selected="selected" value="">Selecione o treino... </option>-->
                    
<?php if($resTreinos==null): ?>
    <?php foreach($treinos as $treino): ?>
        <option value="<?= $treino ?>"><?= $treino ?>º Treino</option>
    <?php endforeach; ?>
<?php elseif($resTreinos=='-'): ?>
        <option value="">-</option>
<?php else: ?>
    <?php foreach ($resTreinos as $treino): ?>  
        <option value="<?= $treino ?>"><?= $treino ?>º Treino</option>
    <?php endforeach; ?>
<?php endif; ?>