<div id="content">

<style>
    table th {background: #ccc; font-size: 13px;}
    table tr td {background: #fff; font-size: 13px; padding: 3px;}
    table,th,td { border-collapse:collapse; }
</style>
<script src="<?= $this->baseUrl() ?>/js/jquery/meiomask.js"></script>
<script>
$(function(){ })

function modalEditarDobras() {
    var avaliacao_id = $('#avaliacao_id').val();
    
    $('#modalAvaliacaoEdit').load(BASE_URL+'admin/modal-avaliacao-dobras-edit', {avaliacao_id: avaliacao_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 700,
        height: 550,
        buttons: [
            {
                text: "Salvar",
                class : "btn btn-primary btn-xs",
                click: function() {
                    alterarAvaliacaoDobras();
                } 
            } ,
            {
                html: "Cancelar",
                class : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}


function modalEditarMedidas() {
    var avaliacao_id = $('#avaliacao_id').val();
    
    $('#modalAvaliacaoEdit').load(BASE_URL+'admin/modal-avaliacao-medidas-edit', {avaliacao_id:avaliacao_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 700,
        height: 540,
        buttons: [
            {
                text: "Salvar",
                class : "btn btn-primary btn-xs",
                click: function() {
                    alterarAvaliacaoMedidas();
                } 
            },
            {
                html: "Cancelar",
                class : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}

function modalEditarMedidasOssea() {
    var avaliacao_id = $('#avaliacao_id').val();
    
    $('#modalAvaliacaoEdit').load(BASE_URL+'admin/modal-avaliacao-diametros-osseos-edit', {avaliacao_id:avaliacao_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 700,
        height: 350,
        buttons: [
            {
                text: "Salvar",
                class : "btn btn-primary btn-xs",
                click: function() {
                    alterarMedidasOsseas();
                } 
            },
            {
                html: "Cancelar",
                class : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}

function alterarAvaliacaoMedidas() {        
    var params = $( "#formAvaliacaoMedidas" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-medidas',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno == 'sucesso'){
                    alert(resp.msg);
                    loadAvaliacaoAluno(resp.avaliacao_id);

                }else if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else  {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    })            
}

function alterarAvaliacaoDobras() {
    if( !$('#peso').val() || $('#peso').val() == '0.00' ){
        alert('Informe o peso do aluno.');
    }else
    if( !$('#altura').val() || $('#altura').val() == '0.00' ){
        alert('Informe a altura do aluno.');
    }else
    if( !$('#dt_reavaliacao').val() ){
        alert('Informe a data da próxima avaliação do aluno.');
    }else {
    
        var params = $( "#formAvaliacao" ).serialize();

        $.ajax({
                type:'post',
                url: BASE_URL+'admin/alterar-dobras',
                data: params,
                dataType: 'json',
                async: false,
                success: function(resp){
                    if(resp.retorno != 'sucesso'){
                        alert(resp.msg); 
                        return false;
                    }else 
                    if(resp.retorno == 'sucesso'){                   
                        alert(resp.msg);
                        gerarResultadoAvaliacaoFisica(resp.avaliacao_id);

                    }else {
                        alert('ERROR: Retorno incorreto.');
                        return false;
                    }
                }
        })
        
    }
}

function alterarMedidasOsseas() {        
    var params = $( "#formAvaliacaoMedidasOsseasEdit" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-medidas-osseas',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno == 'sucesso'){
                    alert(resp.msg);
                    gerarResultadoAvaliacaoFisica(resp.avaliacao_id);

                }else if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else  {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    })            
}


function gerarResultadoAvaliacaoFisica(avaliacao_id) {
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/gerar-resultado-avaliacao',
            data: {avaliacao_id: avaliacao_id},
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else 
                if(resp.retorno == 'sucesso'){              
                    
                    //RENDERIZAR
                    loadAvaliacaoAluno(avaliacao_id);

                }else {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    });
}


function loadAvaliacaoAluno(avaliacao_id) {
    $('#contentAvaliacao').load(BASE_URL+'admin/load-avaliacao-fisica', {avaliacao_id:avaliacao_id});
    
//    $.ajax({
//        type:"post",
//        url: BASE_URL+'admin/load-avaliacao-fisica',
//        data: {avaliacao_id:avaliacao_id},
//        dataType: 'json',
//        async: false,
//        success: function(resp){
//            if(resp.retorno != 'sucesso'){
//                alert(resp.msg); return false;
//            }else {
//                $('#contentAvaliacao').html(resp.html);
//            }
//        }
//    })
}

</script>

<?php
    list($ano) = explode('-', $this->dadosAluno['dt_nascimento']);
    $idade = ( date('Y') - $ano );
    #list($nome, $sobrenome) = explode(" ", $this->dadosAluno['nome']);
    #$nomeAluno = ($nome)." ".($sobrenome);
?>


<div id="breadcrumbs" class="breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="#" onclick="changePage('home')">Home</a></li>
        <li><a href="#" onclick="changePage('montar-treino')">Pesquisar Aluno</a></li>
        <li><a href="#" onclick="changePage('listar-avaliacoes-aluno/matricula/<?= $this->dadosAluno['matricula'] ?>')">Listar Avalia&ccedil;&otilde;es</a></li>
        <li class="active">Avalia&ccedil;&atilde;o F&iacute;sica de <?= $this->dadosAluno['nome'] ?></li>
    </ul>
</div>

<?php #Utils_Print::printvardie($this->aAvaliacao); ?>


<div id="modalAvaliacaoEdit"></div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">            
            <input type="hidden" name="avaliacao_id" id="avaliacao_id" value="<?= $this->aAvaliacao['id'] ?>" />

            <fieldset>
                <legend>Avalia&ccedil;&atilde;o F&iacute;sica de <span style="color: #00a300"><?= $this->dadosAluno['nome'] ?></span></legend>
		    
                
                <div style="text-align: right; margin-top: 7px; margin-bottom: 7px;">
                    <button onclick="modalEditarDobras()" style="background: #87B87F; border: 1px solid #87B87F; color: #fff; padding: 4px 8px 4px 8px; font-weight: bold;">
                        <i class="ace-icon fa fa-edit"></i> Editar Dobras
                    </button>
                    <button onclick="modalEditarMedidas()" style="background: #FE9; border: 1px solid #FFEA07; color: #333; padding: 4px 8px 4px 8px; font-weight: bold;">
                        <i class="ace-icon fa fa-edit"></i> Editar Medidas
                    </button>
                    <button onclick="modalEditarMedidasOssea()" style="background: #0091d9; border: 1px solid #87B87F; color: #fff; padding: 4px 8px 4px 8px; font-weight: bold;">
                        <i class="ace-icon fa fa-edit"></i> Editar Ossos
                    </button>
                    <button onclick="changePage('listar-avaliacoes-aluno/matricula/<?= $this->dadosAluno['matricula'] ?>')" style="background: #ac2925; border: 1px solid #ac2925; color: #fff; padding: 4px 8px 4px 8px; font-weight: bold;">
                        <i class="ace-icon fa fa-backward"></i> Voltar
                    </button>
                </div>
                
                
                <div id="contentAvaliacao">
                
                <div style="border: 1px solid #ccc; padding: 8px;">
                    <table width="100%" border="0">
                        <tr>
                            <td width="5%"><b>Nome:</b></td>
                            <td><?= strtoupper($this->dadosAluno['nome']) ?></td>
                            <td><b>Data:</b> <?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['data']) ?></td>
                            <td>&nbsp;</td>
                            <td><b>Reavalia&ccedil;&atilde;o:</b> <?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['dt_reavaliacao']) ?></td>
                        </tr>
                        <tr>
                            <td><b>Idade:</b></td>
                            <td>
                                <?= $idade ?> anos &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                                <b>Peso:</b> <?= $this->aAvaliacao['peso'] ?> Kg &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                                <b>Altura:</b> <?= $this->aAvaliacao['altura'] ?> m &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                                <b>Sexo:</b> <?= $this->dadosAluno['sexo'] ?>                                
                            </td>
                            <td><b>Protocolo:</b> <?= $this->aAvaliacao['protocolo'] ?></td>
                        </tr>
                    </table>                    
                </div>
                
                <div style="margin: 15px auto; width: 350px; padding: 10px; text-align: center; border: 1px solid #ccc;">
                    <div><b>IMC - &Iacute;ndice de Massa Corporal</b></div>
                    <div><?= $this->aAvaliacao['imc'] ?> - <?= $this->aAvaliacao['situacao'] ?></div>
                </div>
                
                <div>
                    <table width="100%" border="0">
                        <tr>
                            <td width="15%"><b>% de Gordura:</b> </td>
                            <td width="15%"><?= number_format($this->aAvaliacao['percentual_gordura'], 2) ?> %</td>
                            <td with="70%" height="150" align="center" rowspan="8"></td>
                            <td><b>Massa Magra:</b> </td>
                            <td><?= $this->aAvaliacao['massa_magra'] ?> Kg</td>
                        </tr>
                        <tr>             
                            <td><b>Peso Ideal:</b> </td>
                            <td><?= $this->aAvaliacao['peso_ideal'] ?> Kg</td>
                            <td width="15%"><b>Massa Gorda:</b> </td>
                            <td><?= $this->aAvaliacao['massa_gorda'] ?> Kg</td>
                        </tr>
                        <tr>
                            <td><b>Peso em Excesso:</b> </td>
                            <td><?= $this->aAvaliacao['peso_excesso'] ?> Kg</td>                            
                            <td><b>Massa &Oacute;ssea:</b> </td>
                            <td><?= $this->aAvaliacao['massa_ossea'] ?> Kg</td>
                        </tr>
                        <tr>
                            <td><b>Massa Muscular:</b> </td>
                            <td><?= $this->aAvaliacao['massa_muscular'] ?> Kg</td>
                            <td><b>Massa Residual:</b> </td>
                            <td><?= $this->aAvaliacao['massa_residual'] ?> Kg</td>
                        </tr>
                    </table>
                    
                    
                    <br>
                    <table width="25%" border="1" style="float: left; margin-right: 25px;">
                        <thead>
                            <tr>
                                <td style="background: yellow;" colspan="2"><b>Dobras Cut&acirc;neas</b> </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="10%"><b>Triceps:</b> </td>
                                <td width="35%" colspan="2"><?= $this->aAvaliacao['TR'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Subescapular:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['SB'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Axilar Media:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['AX'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Abdomen:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['AB'] ?> cm</td>
                            </tr>                        
                            <tr>
                                <td><b>Coxa:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['CX'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Panturrilha:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['PA'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Biceps:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['BI'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Torax:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['PE'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Supra Iliaca:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['SI'] ?> cm</td>
                            </tr>
                        </tbody>    
                    </table>
                    
                    <table width="30%" border="1" style="float: left; margin-right: 25px;">
                        <thead>
                            <tr>
                                <td style="background: green; color: #fff;" colspan="3"><b>Per&iacute;metros</b> </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="13%"><b>T&oacute;rax:</b> </td>
                                <td width="35%" colspan="2"><?= $this->aAvaliacao['torax'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Pesco&ccedil;o:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['pescoco'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Ombro:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['ombro'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Cintura:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['cintura'] ?> cm</td>
                            </tr>                        
                            <tr>
                                <td><b>Abd&ocirc;men:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['abdomen'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Quadril:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['quadril'] ?> cm</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><b>Direita</b></td>
                                <td><b>Esquerda</b></td>
                            </tr>
                            <tr>
                                <td><b>Bra&ccedil;o contra&iacute;do:</b></td>
                                <td><?= $this->aAvaliacao['braco_direito_contraido'] ?> cm</td>
                                <td><?= $this->aAvaliacao['braco_esquerdo_contraido'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Bra&ccedil;o relaxado:</b></td>
                                <td><?= $this->aAvaliacao['braco_direito_relaxado'] ?> cm</td>
                                <td><?= $this->aAvaliacao['braco_esquerdo_relaxado'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Antebra&ccedil;o:</b></td>
                                <td><?= $this->aAvaliacao['antebraco_direito'] ?> cm</td>
                                <td><?= $this->aAvaliacao['antebraco_esquerdo'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Coxa:</b></td>
                                <td><?= $this->aAvaliacao['coxa_direita'] ?> cm</td>
                                <td><?= $this->aAvaliacao['coxa_esquerda'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Panturrilha:</b></td>
                                <td><?= $this->aAvaliacao['panturrilha_direita'] ?> cm</td>
                                <td><?= $this->aAvaliacao['panturrilha_esquerda'] ?> cm</td>
                            </tr>
                        </tbody>    
                    </table>
                    
                    <table  width="30%" border="1">
                        <thead>
                            <tr>
                                <td style="background: #0091d9; color: #fff;" colspan="3"><b>Medidas &Oacute;sseas</b> </td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td width="20%"><b>Biestilóide (punho):</b> </td>
                                <td width="10%" colspan="2"><?= $this->aAvaliacao['biestiloide'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Biepicondiliano do f&ecirc;mur:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['biepicondiliano_femur'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Biacromial:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['biacromial'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Biileocristal:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['biileocristal'] ?> cm</td>
                            </tr>                        
                            <tr>
                                <td><b>Bitrocanteriano:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['bitrocanteriano'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Biepicondiliano do úmero:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['biepicondiliano_umero'] ?> cm</td>
                            </tr>
                            <tr>
                                <td><b>Bimaleolar:</b> </td>
                                <td colspan="2"><?= $this->aAvaliacao['bimaleolar'] ?> cm</td>
                            </tr>
                        </tbody>    
                    </table>
                </div>
                    
                </div>    
                
            </fieldset>
            
        </div>
    </div>

</div>

</div>