<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
<style>
    table th {background: #ccc; font-size: 13px;}
    table tr td {background: #fff; font-size: 13px; padding: 3px;}
    table,th,td { border-collapse:collapse; }
</style>

<script src="<?= $this->baseUrl() ?>/js/jquery/meiomask.js"></script>
<script>
$(function(){
    
    carregarPeriodizacao();    
    carregarFrequencia();
    
    //if( $('#deviceType').val() == "computer" ){
    //    $( "#dt_ini_treino" ).datepicker({ dateFormat: 'dd/mm/yy' });
    //}
    
    $( '#dt_ini_treino' ).setMask('date');
    
    <?php if( isset($this->msgExpirou) ): ?>
        $('#aviso').fadeIn().delay(5000).fadeOut();
    <?php endif; ?>
})

function carregarPeriodizacao(){
    $('#showPeriodizacaoPreview').load(BASE_URL+'admin/grid-periodizacao-preview', {ficha_id: $('#ficha_id').val()});
}

function carregarFrequencia(){
    $('#showFrequencia').load(BASE_URL+'admin/carregar-frequencia', {ficha_id: $('#ficha_id').val()});
}

function iniciarTreino(){
    var ficha_id = $('#ficha_id').val();
    var dt_ini_treino = $("#dt_ini_treino").val();
    if(!dt_ini_treino) {
       alert("Informe a data do treino."); return false;
    }else {
    	$.ajax({
	        type:'post',
	        url: BASE_URL+'admin/iniciar-treino',
	        data: {ficha_id: ficha_id, dt_ini_treino: dt_ini_treino},
	        dataType:'json',
	        success: function(resp){
	            if(resp.retorno != 'sucesso'){
	                alert(resp.msg); 
	                $("#dt_ini_treino").val("");
	                $("#dt_ini_treino").focus();
	                return false;
	            }else {
	                alert(resp.msg);
	                $('#modal-iniciar-treino').dialog( "destroy" );
	                carregarPeriodizacao();    
    			carregarFrequencia();
	            }
	        }
	 })
    }
}

function modalIniciarTreino(){
     $('#modal-iniciar-treino').dialog({
        autoOpen: true,
        position: 'top',
        modal: true,
        width: 350,
        height: 300,
        buttons: [
            {
                html: "Salvar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    iniciarTreino();                    
                }
            },
            {
                text: "Cancelar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    $( this ).dialog( "destroy" );
                } 
            }
            
        ]
    })
    $('.ui-dialog-titlebar').hide();	
    $("#dt_ini_treino").focus();
}

</script>
<?php
    list($nome, $sobrenome) = explode(" ", $this->dadosAluno['nome']);
    $nomeAluno = ($nome)." ".($sobrenome);
?>

<div id="modal-iniciar-treino" style="display: none;">
	<div data-role="header" data-theme="a" class="ui-corner-top">
	   <h2>Iniciar Treino</h2>
	</div>
	<br>
	<div data-role="content" data-theme="d" class="ui-corner-bottom ui-content">
		<p>Data do Treino:</p>
		<input data-role="date" type="text" name="dt_ini_treino" id="dt_ini_treino" maxlength="10" />   <span style="color: #ccc;">Ex: dd/mm/YYYY</span>
	</div>
</div>

<div id="breadcrumbs" class="breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="#" onclick="changePage('home')">Home</a></li>
        <li><a href="#" onclick="changePage('montar-treino')">Pesquisar Aluno</a></li>
        <li><a href="#" onclick="changePage('listar-treinos-aluno/matricula/<?= $this->aluno_id ?>')">Treinos de <?= $nomeAluno ?></a></li>
        <li class="active">Montar <?= ($this->dadosFicha['ds_ficha']); ?></li>
    </ul>
</div>

<?php #Utils_Print::printvardie($this->dadosFicha); ?>


<div id="modalTreino"></div>
<div id="modalRemove" style="display: none;">
    <h3 class="page-header">
        <i class="ace-icon fa fa-warning"></i> Alerta
    </h3>
    <div>Deseja realmente remover este exerc&iacute;cio do treino?</div>
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            
            <input type="hidden" name="deviceType" id="deviceType" value="<?= $this->deviceType ?>" />
            <input type="hidden" name="P_matricula" id="P_matricula" value="<?= $this->aluno_id ?>" />
            <input type="hidden" name="ficha_id" id="ficha_id" value="<?= $this->ficha_id ?>" />

            <?php //echo $this->render('admin/gridPeriodizacao.phtml'); ?>

            <fieldset>
                    <legend>Ficha do Aluno - <?php echo ($this->dadosAluno['nome']) ?></legend>

		    
			     <div id="aviso" class="alert alert-block alert-danger" style="display: none;">
		                <button type="button" class="close" data-dismiss="alert">
		                    <i class="ace-icon fa fa-times"></i>
		                </button>
		                    <i class="ace-icon fa fa-exclamation-triangle"></i> <?= $this->msgExpirou; ?>
		            </div>	
		    
		    
                    <div style="text-align: center; font-size: 16px; font-weight: bold;"><?= ($this->dadosFicha['ds_ficha']); ?> / <?php echo Utils_Date::formataDataSemHoraToShow($this->dadosFicha['dt_ini_ficha']) ?></div>
                    
                    
            </fieldset>
            
            <div style="text-align: right; margin-top: 7px; margin-bottom: 7px;">
                <button class="btn btn-success btn-sm" onclick="modalAdicionaExercicios(<?= $this->ficha_id ?>, <?= $this->aluno_id ?>)">
                    <i class="ace-icon fa fa-plus"></i> Adicionar Exerc&iacute;cio
                </button>
                <button class="btn btn-warning btn-sm" onclick="openModalTreinoEdit(<?= $this->ficha_id ?>)">
                    <i class="ace-icon fa fa-edit"></i> Editar Ficha
                </button>
                <button class="btn btn-primary btn-sm" onclick="openModalPeriodizacao(<?= $this->ficha_id ?>)">
                    <i class="ace-icon fa fa-edit"></i> Periodiza&ccedil;&atilde;o
                </button>
                <!--<button onclick="imprimirTreino(<?= $this->ficha_id ?>, <?= $this->aluno_id ?>)" style="background: #0091d9; border: 1px solid #0091d9; color: #fff; padding: 4px 8px 4px 8px; font-weight: bold;">
                    <i class="ace-icon fa fa-print"></i> Imprimir Ficha
                </button>-->
                
                <button class="btn btn-default btn-sm" onclick="modalIniciarTreino()">
                    <i class="ace-icon fa fa-calendar"></i> Iniciar Treino
                </button>
                
                <button class="btn btn-danger btn-sm" onclick="changePage('listar-treinos-aluno/matricula/<?= $this->aluno_id ?>')">
                    <i class="ace-icon fa fa-backward"></i> Voltar
                </button>
                
            </div>
            
            <div id="gridTreinos">
                <?php if(count($this->aTreinoFicha) > 0 ): ?>
                
                
                    <?php if($this->aTreinoFicha){ ?>

                            <?php foreach($this->aTreinoFicha as $treino => $aLista){ ?>
                            <table class="table table-striped" width="100%" border="1" style="margin: 0 auto;">
                                    <tr>
                                        <th colspan="<?= (isset($this->cond[$treino]))? (6+$this->cond[$treino]) : 6; ?>" style="text-align: center; background: #ccc;">TREINO "<?= $treino; ?>"</th>
                                    </tr>
                                    <tr>
                                            <th width="39%">Exerc&iacute;cio</th>
                                            <th width="6%" style="text-align: center;">S&eacute;rie</th>
                                            <th width="10%" style="text-align: center;">Repet.</th>
                                            <th width="6%" style="text-align: center;">Carga</th>

                                            <?php if( isset($this->cond[$treino]) ): ?>
                                                    <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                            <th width="6%" style="text-align: center;">Carga</th>
                                                    <?php } ?>
                                            <?php endif; ?>

                                            <th width="6%" style="text-align: center;">Interv.</th>
                                            <th width="<?= (isset($this->cond[$treino]))? ($this->cond[$treino] >= 2)? '21%' : '15%' : '10%'; ?>" style="text-align: center;" colspan="<?= (isset($this->cond[$treino]))? $this->cond[$treino] : 0; ?>">A&ccedil;&atilde;o</th>
                                    </tr>
                                    <?php $j=0; ?>
                                    <?php foreach($aLista as $key => $lista){ ?>

                                            <tr bgColor="<?php echo ($j%2==1)? '#eee' : ''; ?>">
                                                    <td width="39%"><?= ($lista['exercicio']) ?> <?= !empty($lista['detalhes'])? "({$lista['detalhes']})" : '' ?></td>
                                                    <td width="6%" align="center"><?= $lista['series'] ?></td>
                                                    <td width="10%" align="center"><?= $lista['repeticoes'] ?></td>
                                                    <td width="6%" align="center"><?= $lista['carga1'] ?> </td>

                                                    <?php
                                                        if(isset($lista['carga2'])):
                                                                foreach($lista['carga2'] as $lisCarga): ?>
                                                                        <td width="6%" align="center"><?= $lisCarga['carga']; ?> </td><?php
                                                                endforeach;

                                                                $totCargaTreinoAtual = count($lista['carga2']);
                                                                $preenche = ($this->cond[$treino] - $totCargaTreinoAtual);


                                                                for($x=1; $x<=$preenche; $x++){ ?>
                                                                        <td width="6%" align="center">-</td>
                                                                <?php }

                                                        else: ?>
                                                                <?php if( isset($this->cond[$treino]) ): ?>
                                                                        <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                                                <td width="6%" align="center">-</td>
                                                                        <?php } 
                                                                endif;
                                                        endif;
                                                    ?>

                                                    <td width="6%" align="center"><?= $lista['intervalo'] ?></td>
                                                    <td width="<?= (isset($this->cond[$treino]))? ($this->cond[$treino] >= 2)? '21%' : '15%' : '10%'; ?>" align="center">
                                                        <!--<img src="<?php echo $this->baseUrl().'/images/acao/ico-peso3.jpeg' ?>" width="20" height="20" onclick="addCarga(<?= $lista['id']; ?>)" style="border: 1px solid #222; border-radius: 3px 3px 3px 3px;">-->

                                                        <button class="icoButtom" style="background: #0091d9; border: 1px solid #0091d9; font-weight: bold;" onclick="addCarga(<?= $lista['id']; ?>, <?= $this->ficha_id ?>)">
                                                            <i class="ace-icon fa fa-edit"></i>
                                                        </button>

                                                        <button class="icoButtom" style="background: #ac2925; border: 1px solid #ac2925; font-weight: bold;" onclick="removerTreino(<?= $lista['id']; ?>)">
                                                            <i class="ace-icon fa fa-trash-o"></i> 
                                                        </button>
                                                    </td>
                                            </tr>
                                    <?php $j++; ?>    
                                    <?php } ?>    
                            </table>
                            <br>
                            <?php } ?>
                    <?php } ?>      
                    
                    <div id="showPeriodizacaoPreview" style="text-align: center; font-size: 16px; font-weight: bold;"></div>
                    
                    <div id="showFrequencia"></div>
                    
                            
                <?php else: ?>
                        <div class="alert alert-block alert-warning">
                            <button type="button" class="close" data-dismiss="alert">
                                <i class="ace-icon fa fa-times"></i>
                            </button>
                            <b>Prof. <?= $this->sessao->nome ?></b>, nenhum exerc&iacute;cio foi adicionado &agrave; ficha do aluno.
                        </div>
                <?php endif; ?>            

            </div>

        </div>
    </div>

</div>

