<style>
  .table tr th { font-size: 20px; }
  .table tr td { font-size: 20px; }
</style>
<script>

function openEditarExercicio(id) {
    openAguarde();
    window.location = BASE_URL+'admin/modal-exercicio/id/'+id;
}

function removerExercicio(id) {
    var r = confirm("Deseja realmente remover este exercicio?");
    if (r == true) {
	    openAguarde();
	        
	    $.ajax({
	            type:'post',
	            url: BASE_URL+'admin/remover-exercicio',
	            data: { id: id },
	            success: function(resp){
	                if(resp.retorno != 'sucesso'){
	                    alert(resp.msg); 
	                    return false;
	                }else {
	                    alert(resp.msg);
						window.location.reload();
	                }
	            }
	    })
    }
}
</script>


<?php 
      $aResults = array();	

      foreach ($this->results['results'] as $key => $dado){
	$aResults[$dado['musculo']][] = $dado;
      }
?>


<div data-role="header">
    <h1>Exerc&iacute;cios</h1>
    <a href="<?= $this->baseUrl() ?>/" data-theme="b">
        <
    </a>
    <a href="javascript:changePage('modal-exercicio')" data-theme="b">
        Novo
    </a>
</div>

<div>

	<?php if(($this->results['total']) == 0): ?>
		<div class="alert alert-block alert-warning" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
			<b><?= ($this->sessao->nome) ?></b>, nenhum exerc&iacute;cio foi cadastrado.
		</div>
	<?php else: ?>

		<table class="table table-striped">			
			<?php foreach ($aResults as $musculo => $dado): ?>
				<tr align="center" bgColor="orange">
				   <td colspan="3" style="padding: 4px;"><b><?= utf8_encode($musculo); ?></b></td>
				</tr>
				<?php foreach($dado as $i => $exercicio): ?>
				   <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">    
				        <td width="5%" onclick="openEditarExercicio(<?= $exercicio['id'] ?>)">					        
				           <?php if($exercicio['thumbnail']): ?>
				             <img src="<?= $this->baseUrl() ?><?= $exercicio['thumbnail'] ?>" width="60" height="60" />
				           <?php else: ?>
				             <div style="border: 1px solid #ccc; width: 60px; height: 60px;">&nbsp;</div>
				           <?php endif; ?>
				        </td>
					<td onclick="openEditarExercicio(<?= $exercicio['id'] ?>)"><?= utf8_encode($exercicio['exercicio']) ?></td>
					<td align="center">                 
					   <a href="#" data-role="button" data-mini="true" onclick="removerExercicio(<?= $exercicio['id'] ?>)">
					      <img src="<?= $this->baseUrl() ?>/images/acao/ico_delete.gif" />
					   </a>						
					</td>
				   </tr>
				<?php endforeach; ?>
			<?php endforeach; ?>
		</table>
		
	<?php endif; ?>    
	
</div>	