<table width="100%" border="1" class="table table-striped" id="tableDados">
    <tr>
        <th style="text-align: center; background: #ccc;" colspan="5">Periodiza&ccedil;&atilde;o</th>
    </tr>
    <tr>
        <th style="background: #ccc;">Sess&atilde;o</th>
        <th style="background: #ccc;">Descri&ccedil;&atilde;o</th>
        <th style="background: #ccc; text-align: center;">Dias</th>
        <th style="background: #ccc; text-align: center;">Data Fim</th>
    </tr>

    <?php if($this->aPeriodizacao['total'] > 0): ?>
        <?php $aPeriodizacao = $this->aPeriodizacao['results']; ?>



            <?php foreach ($aPeriodizacao as $item): ?>
                <tr>
                    <td><?= $item['treino'] ?>º Sess&atilde;o</td>
                    <td><?= $item['descricao'] ?></td>
                    <td align="center"><?= $item['count'] ?>/<?= $item['dias'] ?></td>
                    <td align="center"><?= Utils_Date::formataDataSemHoraToShow($item['dt_fim']) ?></td>
                </tr>
            <?php endforeach; ?>

    <?php else: ?>
            <tr>
                <td align='center' colspan="5">Adicione a periodiza&ccedil;&atilde;o do aluno.</td>
            </tr>
    <?php endif; ?>

</table>  
