<table width="100%" class="table table-striped" border="1" id="tableDados">
    <tr>
        <th style="text-align: center; background: #ccc;" colspan="5">Periodiza&ccedil;&atilde;o</th>
    </tr>
    <tr>
        <th style="background: #ccc;">Sess&atilde;o</th>
        <th style="background: #ccc;">Descri&ccedil;&atilde;o</th>
        <th align="center" style="background: #ccc;">Dias</th>
        <th align="center" style="background: #ccc;">A&ccedil;&atilde;o</th>
    </tr>

    <?php if($this->aPeriodizacao['total'] > 0): ?>
        <?php $aPeriodizacao = $this->aPeriodizacao['results']; ?>

            <?php foreach ($aPeriodizacao as $item): ?>
                <tr>
                    <td><?= $item['treino'] ?>º Sess&atilde;o</td>
                    <td><?= $item['descricao'] ?></td>
                    <td align="center"><?= $item['count'] ?>/<?= $item['dias'] ?></td>
                    
                    <td align="center">                    
                    	<input type="button" class="icoButtom" value=" X " style="background: #ac2925; border: 1px solid #ac2925;font-weight: bold;color:#FFF;" onclick="removePeriodizacao(<?= $item['id']; ?>)">
                    	</td>
                </tr>
            <?php endforeach; ?>

    <?php else: ?>
            <tr>
                <td align='center' colspan="5">Adicione aqui a periodiza&ccedil;&atilde;o.</td>
            </tr>
    <?php endif; ?>

</table>  
