<script>
  function pagination(page) {
  	$( "#gridExercicio" ).load(BASE_URL+'admin/grid-exercicios/pagina/'+page);
  }
</script>
  
<?php if( count($this->results) == 0): ?>
    <div class="alert alert-block alert-warning">
        <button type="button" class="close" data-dismiss="alert">
            <i class="ace-icon fa fa-times"></i>
        </button>
        <b><?= utf8_encode($this->sessao->nome) ?></b>, nenhum exerc&iacute;cio foi cadastrado.
    </div>
<?php else: ?>

    	<?php echo $this->paginationControl($this->results, 'Sliding', 'admin/paginacao-topo.phtml'); ?>
    
        <table class="table table-striped">
            <tr>
                <th>Cod.</th>
                <th>M&uacute;sculos</th>
                <th>Exerc&iacute;cios</th>
                <th style="text-align: center;">A&ccedil;&atilde;o</th>
            </tr>
                <?php foreach ($this->results as $dado): ?>
                    <tr>
                        <td><?= $dado['id'] ?></td>
                        <td><?= utf8_encode($dado['musculo']) ?></td>
                        <td><?= utf8_encode($dado['exercicio']) ?></td>
                        <td align="center">
                            <button class="btn btn-sm btn-primary" onclick="openModalExercicioUpdate(<?= $dado['id'] ?>)">
                                <i class="ace-icon fa fa-edit"></i>
                            </button>
                            <button class="btn btn-sm btn-danger" onclick="removerExercicio(<?= $dado['id'] ?>)">
                                <i class="ace-icon fa fa-trash-o"></i>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
         </table>
    	 
    	 <?php echo $this->paginationControl($this->results, 'Sliding', 'admin/paginacao.phtml'); ?>
    	 
<?php endif; ?>    