<script>
  function pagination(page) {
  	$( "#gridAlunos" ).load(BASE_URL+'admin/grid-alunos/pagina/'+page);
  }
</script>

<?php if(count($this->results) == 0): ?>
    <div class="alert alert-block alert-warning">
        <button type="button" class="close" data-dismiss="alert">
            <i class="ace-icon fa fa-times"></i>
        </button>
        <b><?= utf8_encode($this->sessao->nome) ?></b>, nenhum aluno foi cadastrado.
    </div>
<?php else:

    if($this->sessao->perfil_id != 3 && $this->sessao->perfil_id != 4):
	    
	    $totValorSemana = 0;
	    $totValorMes    = 0;
	    
	    foreach ($this->results as $dado):
	        $totValorSemana += ($dado['valor'] * $dado['qtd_aulas']);
	        $totValorMes    += (($dado['valor'] * $dado['qtd_aulas']) * 4 );
	    endforeach; ?>
	    
	    
	    <div style="font-size: 15px; text-align: left;">
	    	Valor a receber por semana: <b>R$ <?php echo Utils_Date::formataMoeda($totValorSemana) ?></b>
	    </div>
	    <div style="font-size: 15px; text-align: left;">
	    	Valor a receber por m&ecirc;s: <b>R$ <?php echo Utils_Date::formataMoeda($totValorMes) ?></b>
	    </div>
    
    <?php endif; ?>
    
    <?php echo $this->paginationControl($this->results, 'Sliding', 'admin/paginacao-topo.phtml'); ?>
    
    <table class="table table-striped">
        <tr>
            <th>Matr&iacute;cula</th>
            <th>Aluno</th>
            <th style="text-align: center;">Hora/aula</th>
            <th style="text-align: center;">Aulas/semana</th>
            <th style="text-align: center;">Vl/semana</th>
            <th style="text-align: center;">Vl/m&ecirc;s</th>
            <th style="text-align: center;">A&ccedil;&atilde;o</th>
        </tr>
        
        <?php foreach ($this->results as $dado): ?>
            <tr>
                <td><?= $dado['matricula'] ?></td>
                <td>
                    <?php if($dado['foto']): ?>
                        <img src="<?= $this->baseUrl(). ($dado['thumbnail']) ?>" width="50" height="50" style="float: left; padding: 0 8px 0 0;" />
                     <?php else : ?>
                        <img src="<?= $this->baseUrl().'/images/fotos/default.jpg' ?>" width="50" height="50" style="float: left; padding: 0 8px 0 0;" />
                     <?php endif; ?> 
                        
                    <?= ($dado['nome']) ?><br>
                    <span style="font-size: 12px;"><?= ($dado['email']) ?></span>
                </td>
                <td align="center"><?= $dado['valor'] ?></td>
                <td align="center"><?= $dado['qtd_aulas'] ?></td>
                <td align="center"><?= Utils_Date::formataMoeda($dado['valor'] * $dado['qtd_aulas']) ?></td>
                <td align="center"><?= Utils_Date::formataMoeda(($dado['valor'] * $dado['qtd_aulas']) * 4 ) ?></td>
                <td align="center">
                    <button class="btn btn-sm btn-primary" onclick="openModalAlunoUpdate(<?= $dado['matricula'] ?>)">
                        <i class="ace-icon fa fa-edit"></i>
                    </button>
                    <button class="btn btn-sm btn-danger" onclick="removerAluno(<?= $dado['matricula'] ?>)">
                        <i class="ace-icon fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    
    <?php if(count($this->results) > 15): 
       echo $this->paginationControl($this->results, 'Sliding', 'admin/paginacao.phtml');
    endif; ?>
<?php endif; ?>    