<style>
    table th {background: #ccc; font-size: 12px;}
    table tr td {background: #fff; font-size: 12px;}
    table,th,td { border-collapse:collapse; }
</style>


    
<?php #Utils_Print::printvardie(); ?>


<div id="gridTreinos">
    <?php if($this->aTreinoFicha){ ?>

            <?php foreach($this->aTreinoFicha as $treino => $aLista){ ?>
            <table width="100%" border="1" style="margin: 0 auto;">
                    <tr>
                            <th colspan="8" align="center">TREINO "<?= $treino; ?>"</th>
                    </tr>
                    <tr>
                            <th width="26%">Exerc&iacute;cio</th>
                            <th width="10%" align="center">S&eacute;rie</th>
                            <th width="10%" align="center">Repeti&ccedil;&otilde;es</th>
                            <th width="10%" align="center">Carga</th>

                            <?php if( isset($this->cond[$treino]) ): ?>
                                    <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                            <th width="10%" align="center">Carga</th>
                                    <?php } ?>
                            <?php endif; ?>

                            <th width="10%" align="center" >Intervalo</th>
                    </tr>
                    <?php $j=0; ?>
                    <?php foreach($aLista as $key => $lista){ ?>

                            <tr bgColor="<?php echo ($j%2==1)? '#eee' : ''; ?>">
                                    <td width="26%"><?= ($lista['exercicio']) ?></td>
                                    <td width="10%" align="center"><?= $lista['series'] ?></td>
                                    <td width="10%" align="center"><?= $lista['repeticoes'] ?></td>
                                    <td width="10%" align="center"><?= $lista['carga1'] ?> Kg</td>

                                    <?php
                                        if(isset($lista['carga2'])):
                                                foreach($lista['carga2'] as $lisCarga): ?>
                                                        <td width="10%" align="center"><?= $lisCarga['carga']; ?> Kg</td><?php
                                                endforeach;

                                                $totCargaTreinoAtual = count($lista['carga2']);
                                                $preenche = ($this->cond[$treino] - $totCargaTreinoAtual);


                                                for($x=1; $x<=$preenche; $x++){ ?>
                                                        <td width="10%" align="center">-</td>
                                                <?php }

                                        else: ?>
                                                <?php if( isset($this->cond[$treino]) ): ?>
                                                        <?php for($i=1; $i<=$this->cond[$treino]; $i++){ ?>
                                                                <td width="10%" align="center">-</td>
                                                        <?php } 
                                                endif;
                                        endif;
                                    ?>

                                    <td width="10%" align="center"><?= $lista['intervalo'] ?></td>
                            </tr>
                    <?php $j++; ?>    
                    <?php } ?>    
            </table>
            <br>
            <?php } ?>
    <?php }  ?>        

</div>
