<script>
jQuery(function(){
    initLoadModal()
})

function initLoadModal() {
    $('#modalTreinoAdd').dialog({
        autoOpen: false,
        position: 'top',
        modal: true,
        width: 700,
        height: 400
    })
    $('.ui-dialog-titlebar').hide();
}


function salvarNovoTreino() {
    var params = $( "#frmNovoTreino" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-novo-treino',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else if(resp.retorno === 'sucesso'){
                    var matricula = $('#aluno_id').val();
                    
                    pesquisarFichaAluno(matricula, resp.ficha_id)
                    
                    //$('#modalTreinoAdd').dialog( "close" );
                    
                    modalAdicionaExercicios(resp.ficha_id, matricula);
                    //$('#modalMusculo').dialog( "close" );
                    //alert(resp.msg);
                }else {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    })
}


function alterarFichaTreino(ficha_id) {
    var params = $( "#frmNovoTreino" ).serialize();
    
    //console.log(params);

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-ficha-treino?ficha_id='+ficha_id,
            data: params,
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    var matricula = $('#aluno_id').val();
                    
                    alert(resp.msg);
                    
                    $('#modalTreinoAdd').dialog( "close" );
                    
                    pesquisarFichaAluno(matricula, resp.ficha_id);
                    
                    
                    //modalAdicionaExercicios(resp.ficha_id, matricula);
                    
                    
                }
            }
    })
}


function openModalTreinoAdd() {
    
    $('#modalTreinoAdd').load(BASE_URL+'admin/modal-treino-add', {aluno_id: $('#aluno_id').val()}).dialog({
    	position: 'top',
        buttons: [
            {
                text: "Salvar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    salvarNovoTreino();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalTreinoAdd').dialog( "open" );
}


function openModalTreinoEdit(ficha_id) {
    
    $('#modalTreinoAdd').load(BASE_URL+'admin/modal-treino-edit', {ficha_id: ficha_id}).dialog({
        position: 'top',
        buttons: [
            {
                text: "Alterar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    alterarFichaTreino(ficha_id);
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalTreinoAdd').dialog( "open" );
}

function modalAdicionaExercicios(ficha_id, aluno_id) {
    $( "#modalTreinoAdd" ).dialog( "option", "title", "Adicionar Exercicios" );
    $( "#modalTreinoAdd" ).dialog( "option", "width", 650 );
    $( "#modalTreinoAdd" ).dialog( "option", "height", 250 );
    $( "#modalTreinoAdd" ).dialog( "option", "buttons", [{
                                                text: "Adicionar", 
                                                "class" : "btn btn-primary btn-xs",
                                                click: function() { 
                                                    
                                                    adicionaExercicioFicha(ficha_id, aluno_id)
                                                    
                                                } 
                                                },{
                                                    text: "Fechar", 
                                                    "class" : "btn btn-danger btn-xs",
                                                    click: function() { 
                                                        $( "#modalTreinoAdd" ).dialog( "option", "width", 700 );
                                                        $( "#modalTreinoAdd" ).dialog( "option", "height", 400 );
                                                        $( this ).dialog( "close" ); 
                                                    } 
                                                }]);
    $('.ui-dialog-titlebar').hide();                                            

    $( "#modalTreinoAdd" ).load(BASE_URL+"admin/modal-montar-treino-aluno", {ficha_id: ficha_id, aluno_id: aluno_id}).dialog( "open" );
}

function adicionaExercicioFicha(ficha_id, aluno_id) {
    var params = $('#frmExercicioFicha').serialize();

    $.ajax({
        type:'post',
        url: BASE_URL+'admin/salvar-exercicio-ficha',
        data: params,
        dataType: 'json',
        success: function(resp) {
            if(resp.retorno === 'sucesso') {
                pesquisarFichaAluno(aluno_id, ficha_id)
                inicializar();
                alert(resp.msg);
            }else {
                alert(resp.msg);
                return false;
            }
        },
        error: function (xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            alert(thrownError);
        }
    })
}

function openModalPeriodizacao(ficha_id) {
    $( "#modalTreinoAdd" ).dialog( "option", "title", "Periodização" );
    $( "#modalTreinoAdd" ).dialog( "option", "width", 650 );
    $( "#modalTreinoAdd" ).dialog( "option", "height", 630 );
    $( "#modalTreinoAdd" ).dialog( "option", "buttons", [{
                                                    text: "Fechar", 
                                                    "class" : "btn btn-danger btn-xs",
                                                    click: function() { 
                                                        $( "#modalTreinoAdd" ).dialog( "option", "width", 700 );
                                                        $( "#modalTreinoAdd" ).dialog( "option", "height", 400 );
                                                        $( this ).dialog( "close" ); 
                                                        
                                                        
                                                    } 
                                                }]);
    $('.ui-dialog-titlebar').hide();                                            

    $( "#modalTreinoAdd" ).load(BASE_URL+"admin/modal-periodizacao", {ficha_id: ficha_id}).dialog( "open" );
}

function loadPeriodizacao(){
    $('#showPeriodizacaoPreview').load(BASE_URL+'admin/grid-periodizacao-ficha', {ficha_id: $('#ficha_id').val()});
}
</script>

<?php
    $dadosAluno = $this->dadoAluno;
    #Utils_Print::printvardie($dadosAluno);

    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
    $nomeAluno = utf8_encode($nome)." ".utf8_encode($sobrenome);
    
    $totalDeFichas = count($this->dadosFicha);
?>

<div id="contentGeral">
    
    <div id="breadcrumbs" class="breadcrumbs">
        <ul class="breadcrumb">
            <li><a href="#" onclick="changePage('home')">Home</a></li>
            <li><a href="#" onclick="changePage('montar-treino')">Pesquisar Aluno</a></li>
            <li class="active">Treinos de <?= $nomeAluno ?></li>
        </ul>
    </div>

    <div id="modal"></div>
    <div id="modalTreinoAdd"></div>

    <div class="page-content">

        <div class="row">
            <div class="col-xs-12">

                <h3 class="page-header">
                    <i class="ace-icon fa fa-users"></i> Treinos de <span style="color: #00a300"><?= $nomeAluno ?></span>
                </h3>

                <button class="btn btn-success btn-primary" onclick="openModalTreinoAdd()">
                    <i class="ace-icon fa fa-plus"></i> Novo Treino
                </button>
                <button class="btn btn-danger" onclick="changePage('montar-treino')">
                    <i class="ace-icon fa fa-backward"></i> Voltar
                </button>
                <br><br>

                <input type="hidden" name="aluno_id" id="aluno_id" value="<?php echo $dadosAluno['matricula']; ?>" />

                <?php if($totalDeFichas == 0): ?>
                    <div class="alert alert-block alert-warning">
                        <button type="button" class="close" data-dismiss="alert">
                            <i class="ace-icon fa fa-times"></i>
                        </button>
                        <b><?= utf8_encode($this->sessao->nome) ?></b>, nenhuma treino foi criada para este aluno.
                    </div>
                <?php else: ?>

                    <div style="font-size: 16px; font-weight: bold; text-align: right;"><?= $totalDeFichas ?> treinos cadastrados</div>
                    
                    <table class="table table-striped">
                        <tr>
                            <th>N&uacute;mero</th>
                            <th>Ficha</th>
                            <th>Professor</th>
                            <th>Data</th>
                            <th>A&ccedil;&atilde;o</th>
                        </tr>
                        <?php foreach ($this->dadosFicha as $ficha): ?>
                            <tr>
                                <td><?= $ficha['id'] ?></td>
                                <td><?= utf8_encode($ficha['ds_ficha']) ?></td>
                                <td><?= utf8_encode($ficha['nm_professor']) ?></td>
                                <td><?= Utils_Date::formataDataToShow($ficha['dt_ini_ficha']) ?></td>
                                <td>
                                    <button class="btn btn-primary" onclick="pesquisarFichaAluno(<?= $ficha['aluno_id']; ?>, <?= $ficha['id'] ?>)">
                                        <i class="ace-icon fa fa-edit"></i>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                <?php endif; ?>
            </div>
        </div>
    </div>

</div>
    