<script>

function salvarAvaliacaoPasso1() {
    if( !$('#peso').val() || $('#peso').val() == '0.00' ){
        alert('Informe o peso do aluno.');
    }else
    if( !$('#altura').val() || $('#altura').val() == '0.00' ){
        alert('Informe a altura do aluno.');
    }else
    if( !$('#dt_reavaliacao').val() ){
        alert('Informe a data da próxima avaliação do aluno.');
    }else {
    
        var params = $( "#formAvaliacao" ).serialize();

        $.ajax({
                type:'post',
                url: BASE_URL+'admin/salvar-avaliacao-passo1',
                data: params,
                dataType: 'json',
                async: false,
                success: function(resp){
                    if(resp.retorno !== 'sucesso'){
                        alert(resp.msg); 
                        return false;
                    }else 
                    if(resp.retorno === 'sucesso'){
                        var matricula = $('#aluno_id').val();

                        openModalAvaliacaoPasso1_2(resp.avaliacao_id, matricula);

                    }else {
                        alert('ERROR: Retorno incorreto.');
                        return false;
                    }
                }
        })
        
    }
}

function salvarAvaliacaoPasso2() {        
    var params = $( "#formAvaliacaoMedidas" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-avaliacao-passo2',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else 
                if(resp.retorno === 'sucesso'){
                    var matricula = $('#aluno_id').val();

                    openModalAvaliacaoPasso1_3(resp.avaliacao_id, matricula);

                }else {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    })            
}

function salvarAvaliacaoPasso3() {
    var params = $( "#formAvaliacaoMedidasOsseas" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-avaliacao-passo3',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else 
                if(resp.retorno === 'sucesso'){
                    var matricula = $('#aluno_id').val();

                    gerarResultadoAvaliacaoFisica(resp.avaliacao_id);

                }else {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    });
}

function gerarResultadoAvaliacaoFisica(avaliacao_id) {
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/gerar-resultado-avaliacao',
            data: {avaliacao_id: avaliacao_id},
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else 
                if(resp.retorno === 'sucesso'){
                    alert(resp.msg);
                    $('#modalAvaliacaoAdd').dialog('close');
                    
                    //RENDERIZAR
                    editarAvaliacaoAluno(avaliacao_id);

                }else {
                    alert('ERROR: Retorno incorreto.');
                    return false;
                }
            }
    });
}


function editarAvaliacaoAluno(avaliacao_id) {
    //$('#contentGeral').load(BASE_URL+'admin/edit-avaliacao-fisica', {avaliacao_id:avaliacao_id});
    
    $.ajax({
        type:"post",
        url: BASE_URL+'admin/edit-avaliacao-fisica',
        data: {avaliacao_id:avaliacao_id},
        dataType: 'json',
        async: false,
        success: function(resp){
            if(resp.retorno != 'sucesso'){
                alert(resp.msg); return false;
            }else {
                $('#contentGeral').html(resp.html);
            }
        }
    })
}

function openModalAvaliacaoPasso1_3(avaliacao_id, aluno_id) {    
    $('#modalAvaliacaoAdd').load(BASE_URL+'admin/modal-avaliacao-diametros-osseos', {avaliacao_id:avaliacao_id, aluno_id: aluno_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 700,
        height: 340,
        buttons: [
            {
                text: "Finalizar",
                class : "btn btn-primary btn-xs",
                click: function() {
                    salvarAvaliacaoPasso3();
                } 
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}

function openModalAvaliacaoPasso1_2(avaliacao_id, aluno_id) {
    $('#modalAvaliacaoAdd').load(BASE_URL+'admin/modal-avaliacao-medidas', {avaliacao_id:avaliacao_id, aluno_id: aluno_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 800,
        height: 590,
        buttons: [
            {
                text: "Próximo",
                class : "btn btn-primary btn-xs",
                click: function() {
                    salvarAvaliacaoPasso2();
                } 
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}

function openModalAvaliacaoPasso1_1() {
    var aluno_id = $('#aluno_id').val();
    
    $('#modalAvaliacaoAdd').load(BASE_URL+'admin/modal-avaliacao-dobras', {aluno_id: aluno_id}).dialog({
        autoOpen: true,
        modal: true,
        width: 700,
        height: 630,
        buttons: [
            {
                text: "Próximo",
                class : "btn btn-primary btn-xs",
                click: function() {
                    salvarAvaliacaoPasso1();
                } 
            } ,
            {
                html: "Cancelar",
                class : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    });
    
    $('.ui-dialog-titlebar').hide();
}

function closeModalAvaliacao() {
    $('#modalAvaliacaoAdd').dialog( "close" );
}


function editAvaliacaoAluno(avaliacao_id){        
    $.ajax({
        type:"post",
        url: BASE_URL+'admin/edit-avaliacao-fisica',
        data: { avaliacao_id: avaliacao_id },
        dataType: 'json',
        async: false,
        success: function(resp){
            if(resp.retorno != 'sucesso'){
                alert(resp.msg);
                return false;
            }else{
                $('#contentGeral').html(resp.html).show();
            }
        },
        error: function (xhr, ajaxOptions, thrownError) {
            //alert(xhr.status);
            alert(thrownError);
        }
    })
}

function removerAvaliacaoAluno(avaliacao_id){        
    $.ajax({
        type:"post",
        url: BASE_URL+'admin/remover-avaliacao-fisica',
        data: { avaliacao_id: avaliacao_id },
        dataType: 'json',
        async: false,
        success: function(resp){
            if(resp.retorno != 'sucesso'){
                alert(resp.msg);
                return false;
            }else{
                alert(resp.msg);
                var matricula =  $('#aluno_id').val();
                listarAvaliacoesAluno(matricula);
            }
        },
        error: function (xhr, ajaxOptions, thrownError) {
            //alert(xhr.status);
            alert(thrownError);
        }
    })
}

function listarAvaliacoesAluno(matricula){

    if(matricula) {
        
        $.ajax({
            type:"post",
            url: BASE_URL+'admin/listar-avaliacoes-aluno',
            data: {matricula: matricula},
            async: false,
            success: function(respHTML){
                $('#contentGeral').html(respHTML).show();
            }
        });
    }else {
        alert('Falha ao carregar as avaliações do aluno. Recarregue a página por favor.')
    }

}

</script>

<?php
    $dadosAluno = $this->dadoAluno;
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
    $nomeAluno = utf8_encode($nome)." ".utf8_encode($sobrenome);
    #Utils_Print::printvardie($dadosAluno);
    
    $totalDeAvaliacoes = count($this->aAvaliacao);
?>

<div id="contentGeral">
    
    <div id="breadcrumbs" class="breadcrumbs">
        <ul class="breadcrumb">
            <li><a href="#" onclick="changePage('home')">Home</a></li>
            <li><a href="#" onclick="changePage('avaliacao')">Pesquisar Aluno</a></li>
            <li class="active">Listar Avalia&ccedil;&otilde;es</li>
        </ul>
    </div>

    <div id="modal"></div>
    <div id="modalAvaliacaoAdd"></div>

    <div class="page-content">

        <div class="row">
            <div class="col-xs-12">

                <h3 class="page-header">
                    <i class="ace-icon fa fa-tags"></i> Listar Avalia&ccedil;&otilde;es de <span style="color: #00a300"><?= utf8_encode($dadosAluno['nome']); ?></span>
                </h3>

                <button class="btn btn-success btn-primary" onclick="openModalAvaliacaoPasso1_1()">
                    <i class="ace-icon fa fa-plus"></i> Nova Avalia&ccedil;&atilde;o
                </button>
                <button class="btn btn-danger" onclick="changePage('avaliacao')">
                    <i class="ace-icon fa fa-backward"></i> Voltar
                </button>
                <br><br>

                <input type="hidden" name="aluno_id" id="aluno_id" value="<?php echo $dadosAluno['matricula']; ?>" />

                <?php if($totalDeAvaliacoes == 0): ?>
                    <div class="alert alert-block alert-warning">
                        <button type="button" class="close" data-dismiss="alert">
                            <i class="ace-icon fa fa-times"></i>
                        </button>
                        <b><?= utf8_encode($this->sessao->nome) ?></b>, nenhuma avalia&ccedil;&atilde;o foi criada para este aluno.
                    </div>
                <?php else: ?>

                    <div style="font-size: 16px; font-weight: bold; text-align: right;"><?= $totalDeAvaliacoes ?> avalia&ccedil;&otilde;es cadastradas</div>
                    
                    <table class="table table-striped">
                        <tr>
                            <th>Avalia&ccedil;&otilde;es</th>
                            <th>Reavalia&ccedil;&atilde;o</th>
                            <th>Peso</th>
                            <th>%Gordura</th>
                            <th>Editar</th>
                        </tr>
                        <?php foreach ($this->aAvaliacao as $avaliacao): ?>
                            <tr>
                                <td>Avalia&ccedil;&atilde;o em <?= Utils_Date::formataDataSemHoraToShow($avaliacao['data']) ?></td>
                                <td><?= Utils_Date::formataDataSemHoraToShow($avaliacao['dt_reavaliacao']) ?></td>
                                <td><?= utf8_encode($avaliacao['peso']) ?></td>
                                <td><?= utf8_encode($avaliacao['percentual_gordura']) ?></td>
                                <td>
                                    <button class="btn btn-primary" onclick="editAvaliacaoAluno(<?= $avaliacao['id'] ?>)">
                                        <i class="ace-icon fa fa-edit"></i>
                                    </button>
                                    <button class="btn btn-danger" onclick="removerAvaliacaoAluno(<?= $avaliacao['id'] ?>)">
                                        <i class="ace-icon fa fa-edit"></i>
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                <?php endif; ?>
            </div>
        </div>
    </div>

</div>
    