<style>
table { border-collapse: collapse;} 
table tr th { background: #333; color: #fff; padding: 4px 0 4px 0; }
</style>
<script>
function removerAvaliacaoAluno(avaliacao_id){     
    var r = confirm("Deseja realmente remover esta avaliacao?");
    if (r == true) {
  
	    openAguarde();
	     
	    $.ajax({
	        type:"post",
	        url: BASE_URL+'admin/remover-avaliacao-fisica',
	        data: { avaliacao_id: avaliacao_id },
	        dataType: 'json',
	        async: false,
	        success: function(resp){
	            if(resp.retorno != 'sucesso'){
	                alert(resp.msg);
	                closeAguarde();
	                return false;
	            }else{
	                alert(resp.msg);
	                var matricula =  $('#aluno_id').val();
	                window.location.reload();
	            }
	        },
	        error: function (xhr, ajaxOptions, thrownError) {
	            //alert(xhr.status);
	            alert(thrownError);
	            closeAguarde();
	        }
	    })
    }
}

function editAvaliacaoAluno(avaliacao_id){
   window.location = BASE_URL+'admin/load-avaliacao-fisica/avaliacao_id/'+avaliacao_id;
}
</script>
<?php
    $dadosAluno = $this->dadoAluno;
    list($nome, $sobrenome) = explode(" ", $dadosAluno['nome']);
    $nomeAluno = utf8_encode($nome)." ".utf8_encode($sobrenome);
    #Utils_Print::printvardie($dadosAluno);
    
    $totalDeAvaliacoes = count($this->aAvaliacao);
?>

<div data-role="header">
    <h1>Avalia&ccedil;&otilde;es </h1>
    <a href="javascript:changePage('avaliacao')" data-theme="b">
        <
    </a>
    <a href="javascript:changePage('modal-avaliacao-dobras/aluno_id/<?= $this->aluno_id ?>')" data-theme="b">
        Novo
    </a>
</div>

<div>

<div id="contentGeral">

    <div class="page-content">

        <div class="row">
            <div class="col-xs-12">

                
                <input type="hidden" name="aluno_id" id="aluno_id" value="<?php echo $dadosAluno['matricula']; ?>" />

                <?php if($totalDeAvaliacoes == 0): ?>
                    <div class="alert alert-block alert-warning" style="background: #f4dae5; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
                        <b><?= utf8_encode($this->sessao->nome) ?></b>, nenhuma avalia&ccedil;&atilde;o foi criada para este aluno.
                    </div>
                <?php else: ?>
                    
                    <table class="table table-striped" width="100%">
                        <tr bgColor="#333333">
                            <th>Avalia&ccedil;&otilde;es</th>
                            <th>Peso</th>
                            <th>IMC</th>
                            <th></th>
                        </tr>
                        <?php foreach ($this->aAvaliacao as $i => $avaliacao): ?>
                            <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">
                                <td onclick="editAvaliacaoAluno(<?= $avaliacao['id'] ?>)"><?= Utils_Date::formataDataSemHoraToShow($avaliacao['data']) ?></td>
                                <td onclick="editAvaliacaoAluno(<?= $avaliacao['id'] ?>)" align="center"><?= utf8_encode($avaliacao['peso']) ?></td>
                                <td onclick="editAvaliacaoAluno(<?= $avaliacao['id'] ?>)" align="center"><?= utf8_encode($avaliacao['imc']) ?></td>
                                <td width="5%">
                                    <button class="btn btn-danger" onclick="removerAvaliacaoAluno(<?= $avaliacao['id'] ?>)">
                                        <img src="<?= $this->baseUrl() ?>/images/acao/ico_delete.gif" />
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>

                <?php endif; ?>
            </div>
        </div>
    </div>

</div>
</div>