<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery-validation/jquery.validation-1.0.1.min.js' ?>"></script>
<script type="text/javascript">
jQuery(function(){
    //$('.form-login').validate()
    
    $('#rdAcademia').click(function(){
        $('#labelNome').text('Nome da Academia');
        $('#nome').attr('placeholder', 'Informe o nome da Academia');
    });
    
    $('#rdPersonal').click(function(){
        $('#labelNome').text('Nome do Personal');
        $('#nome').attr('placeholder', 'Informe o nome do Personal');
    });
    
    $('#ckVerSenha').click(function(){
        var value = $('input[name="ckVerSenha"]:checked').val();

        if(value == 'on'){
            $('#senhaCad').hide().attr('disabled', true);
            $('#hdsenha').val( $('#senhaCad').val() ).show().attr('disabled', false);
        }else {
            $('#hdsenha').hide().attr('disabled', true);
            $('#senhaCad').show().attr('disabled', false);
        }
    })
    
    $('#btnEntrar').click(function(){
        var params = $('.form-login').serialize();
        
        $.ajax({
            type: 'post',
            url: 'autenticacao',
            data: params,
            dataType: 'json',
            success: function(resp) {
                if(resp.retorno == 'erro'){                    
                    if(resp.url){
                        window.location = resp.url;
                    }else {
                        modalMsg(resp.msg); 
                    }
                    return false;
                }else
                if(resp.retorno == 'info'){
                    modalMsgInfo(resp.msg);                    
                }else
                if(resp.retorno == 'sucesso'){
                    window.location = 'index';
                }else{
                    modalMsg(resp.msg);
                    return false;
                }
            }
        })
        
        return false;
    })
    
    
    $('#btnCadastrar').click(function(){        
        var params = $('.form-login-cad').serialize();
        
        $.ajax({
            type: 'post',
            url: 'cadastrar-novo-usuario',
            data: params,
            dataType: 'json',
            success: function(resp) {
                if(resp.retorno != 'sucesso'){
                    modalMsg(resp.msg);                     
                    return false;
                }else
                if(resp.retorno == 'sucesso'){
                    //modalMsg(resp.msg); 
                    
                    if( !resp.url ){
                        $('#login').val( $('#email').val() );
                        $('#senha').val( $('#senhaCad').val() )

                        $('#btnEntrar').trigger('click');
                    }else {
                        window.location = resp.url;
                    }
                }else{
                    modalMsg(resp.msg);                    
                    return false;
                }
            }
        })
        
        return false;
    })
})

function modalMsgInfo(msg) {
    $('#textAlerta').html(msg).css('color', 'red');
    $('#modalAlerta').dialog({
        autoOpen: true,
        modal: true,
        width: 300,
        height: 200,
        buttons: [{
            html: "Ok",
            "class" : "btn btn-danger btn-xs",
            click: function() {
                window.location = 'index';
                $( this ).dialog( "close" );
            }
        }]
    })
    $('.ui-dialog-titlebar').hide();
}

function modalMsg(msg) {
    $('#textAlerta').html(msg).css('color', '#000');
    $('#modalAlerta').dialog({
        autoOpen: true,
        modal: true,
        width: 300,
        height: 200,
        buttons: [{
            html: "Ok",
            "class" : "btn btn-danger btn-xs",
            click: function() {
                $( this ).dialog( "close" );
            }
        }]
    })
    $('.ui-dialog-titlebar').hide();
}
</script>
<?php
	#Utils_Print::printvardie($this->aPlanos);
?>
<div style="width: 750px; margin: 0 auto;">
    <div class="page-content" style="display: inline-block; width: 350px; margin: 10% auto 0; background: #F2F6F9; border-radius: 8px 8px 8px 8px;">

        <form class="form-login">
            <fieldset>
                <legend><i class="ace-icon fa fa-lock"></i> Autentica&ccedil;&atilde;o do usu&aacute;rio</legend>

                <div class="control-group">
                    <label class="control-label" for="inputEmail">Login:</label>
                    <div class="controls">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="ace-icon fa fa-user"></i>
                            </span>
                            <input name="login" id="login" class="form-control" type="text" placeholder="Login"> 
                        </div>
                    </div>
                </div>

                <br>

                <div class="control-group">
                    <label class="control-label" for="inputPassword">Senha:</label>
                    <div class="controls">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="ace-icon fa fa-lock"></i>
                            </span>
                            <input name="senha" id="senha" class="form-control" placeholder="Senha" type="password"> 
                        </div>
                    </div>
                </div>


                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox" style="font-weight: normal;">
                            <input type="checkbox"> Lembrar da senha
                        </label>
                        <br>
                        <button type="submit" class="btn btn-primary" id="btnEntrar"><i class="ace-icon fa fa-key"></i>Entrar</button>
                        <button type="button" class="btn btn-danger" id="btnCancelar">Cancelar</button>
                    </div>
                </div>
            </fieldset>
        </form>

    </div>

    <div class="page-content" style="display: inline-block; float: right; width: 350px; margin: 10% auto 0; background: #F2F6F9; border-radius: 8px 8px 8px 8px;">
        <form class="form-login-cad">
            <fieldset>
                <legend><i class="ace-icon fa fa-user"></i> Quero me cadastrar</legend>

                <div class="control-group">
                    <label class="control-label" for="inputTipo">Tipo de usu&aacute;rio:</label>
                     <div class="controls">
                        <div class="input-group">
                            <label class="btn btn-yellow">
                                <input type="radio" name="rdTipo" id="rdAcademia" value="3" /> 
                                Academia &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </label>
                            <label class="btn btn-primary">
                                <input type="radio" name="rdTipo" id="rdPersonal" value="2" /> 
                                Personal &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </label>
                        </div>
                    </div>
                </div>
                
                <br>
                
                <div class="control-group">
                    <label class="control-label" for="inputNome" id="labelNome">Nome:</label>
                    <div class="controls">
                        <div class="input-group">
                            <span class="input-group-addon">
                                <i class="ace-icon fa fa-user"></i>
                            </span>
                            <input name="nome" id="nome" class="form-control" type="text" placeholder="Selecione o tipo de usu&aacute;rio acima..."> 
                        </div>
                    </div>
                </div>
                
                <br>
                
                <div class="control-group">
                    <label class="control-label" for="inputPlano">Plano:</label>
                    <div class="controls">
                        <div class="input-group">
                            <select name="cbTipoPlano" id="cbTipoPlano" class="form-control">
                                <option value="">Selecione um plano... </option>
                                <option value="1" selected="selected">Experimental - (30 dias GRATUITO)</option>
								<?php foreach($this->aPlanos as $plano): ?>
									<option value="<?= $plano['id'] ?>"><?= $plano['ds_plano'] ?> - R$ <?= $plano['valor'] ?></option>
								<?php endforeach; ?>
                            </select>
                            <!--<b style="color: green;">30 dias - GRATUITO</b>-->
                        </div>
                    </div>
                </div>
                
                <br>
                
                <div class="control-group">
                    <label class="control-label" for="inputEmail">Email:</label>
                    <div class="controls">
                        <div class="input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" name="email" id="email" class="form-control" placeholder="Informe seu e-mail">
                        </div>
                    </div>
                </div>

                <br>

                <div class="control-group">
                    <label class="control-label" for="inputPassword">Senha:</label>
                    <div class="controls">
                        <div class="input-group">
                            <span class="input-group-addon"><input type="checkbox" id="ckVerSenha" name="ckVerSenha" /></span>
                            <input name="senhaCad" id="senhaCad" style="width: 100%" class="form-control" placeholder="Informe uma senha " type="password">                     
                            <input name="senhaCad" id="hdsenha" disabled="true" style="width: 100%; display: none;" class="form-control" placeholder="Informe uma senha" type="text">                     
                        </div>
                    </div>
                </div>


                <div class="control-group">
                    <div class="controls">                        
                        <br>
                        <button class="btn btn-success" id="btnCadastrar"><i class="ace-icon fa fa-save"></i>Cadastrar</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

</div>

<div id="modalAlerta" style="display: none;">
    <h3 class="page-header" style="margin: 5px 2px; padding: 0;">
        <i class="ace-icon fa fa-warning"> </i> Alerta
    </h3>
    <div id="textAlerta" style="margin-top: 25px;"></div>
</div>