<script type="text/javascript">
jQuery(function(){
    
    $('#btnEntrar').click(function(){
        openAguarde();
        
        var params = $('.form-login').serialize();
        
        $.ajax({
            type: 'post',
            url: BASE_URL+'admin/autenticacao',
            data: params,
            dataType: 'json',
            success: function(resp) {
                if(resp.retorno == 'erro'){
                    closeAguarde();
                    //$('#textAlerta').html(resp.msg).fadeIn('fast').delay(5000).fadeOut('fast');
                    $('#textAlerta').html(resp.msg).fadeIn('fast');
                    return false;
                }else
                if(resp.retorno == 'info'){
                    closeAguarde();
                    
                    $('#textAlerta').html(resp.msg).show();
                    
                    var count = 7;
    
                    countdown = setInterval(function(){    
                        if(count > 0) {
                            $('#count').html("Ir para o menu principal em <b>"+count + " segundos</b>").show();      
                            count--;
                        }else {
                             $('#count').html("Ir para o menu principal em <b>"+count-- + " segundos</b>").show();
                            window.location = 'index';
                        }
                    }, 2000);
                    
                }else
                if(resp.retorno == 'sucesso'){
                    if(resp.url){
                        window.location = resp.url;
                    }else {                    
                        window.location = 'index';
                    }
                }else{
                    $('#textAlerta').html(resp.msg).fadeIn('fast').delay(5000).fadeOut('fast');
                    return false;
                }
            }
        })
        
        return false;
    })
    
    
    $('#btnCadastrar').click(function(){    
        openAguarde();
            
        var params = $('.form-login-cad').serialize();
        
        $.ajax({
            type: 'post',
            url: 'cadastrar-novo-usuario',
            data: params,
            dataType: 'json',
            success: function(resp) {
                if(resp.retorno != 'sucesso'){
                    closeAguarde();
                    modalMsg(resp.msg); 
                    return false;
                }else
                if(resp.retorno == 'sucesso'){
                    if( !resp.url ){
                        $('#login').val( $('#email').val() );
                        $('#senha').val( $('#senhaCad').val() );

                        $('#btnEntrar').trigger('click');
                    }else {
                        window.location = resp.url;
                    }
                    
                    //modalMsg(resp.msg); 
                    
                    //$('#login').val( $('#email').val() );
                    //$('#senha').val( $('#senhaCad').val() )
                    
                    //$('#btnEntrar').trigger('click');
                    
                    //window.location = 'index';
                }else{
                    modalMsg(resp.msg);
                    closeAguarde();
                    return false;
                }
            }
        })
        
        return false;
    })
})

</script>
        

<div data-role="header">
    <h1>GTainer</h1>
    <a href="javascript:changePage('cadastro')" data-theme="b" style="background: green;">
        Cadastre-se
    </a>
</div>

<div id="textAlerta" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px; display: none;"></div>
<div id="count" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px; display: none;"></div>
		
<div class="main-content" data-role="content">
<div style="text-align: center; margin: 0 0 15px;">
  <img src="<?= $this->baseUrl() ?>/images/site/logo-sistema-01.png" width="200px" />
</div>

	<form class="form-login">
		
		<div data-role="fieldcontain">
				<label for="login">Login:</label>
				<input type="text" name="login" id="login" value="" placeholder="Login"/>
				<br>
				<label for="login">Senha:</label>
				<input type="password" name="senha" id="senha" value="" placeholder="Senha"/>
				<br>
				<button type="button" id="btnEntrar" data-theme="b">Entrar</button>
				<!--<button type="button" onclick="changePage('cadastro')" style="background: green;">Cadastre-se</button>-->
				
				<div style="text-align: center; width: ">
				     <div style="font-weight: bold; font-size: 12px; margin: 5px 0 5px;">Acesse pelos navegadores abaixo para ter um melhor desemplenho:</div>
				     
				     <table border="0" width="60%" style="margin: 0 auto;">
				        <tr>
				           <td><img src="<?= $this->baseUrl() ?>/images/firefox.png" width="80" /></td>
				           <td><img src="<?= $this->baseUrl() ?>/images/chrome.png" width="80" /></td>
				        </td>
				        <tr>
				           <th style="font-size: 12px;">Firefox</th>
				           <th style="font-size: 12px;">Chrome</th>
				        </td>
				     </table>
				     
				</div>
		</div>
		
	</form>
</div>
