<script>
jQuery(function(){
     $('#btSalvar').click(function(){
            openAguarde();
    
	    var params = $( "#frmMusculo" ).serialize();
	
	    $.ajax({
	            type:'post',
	            url: BASE_URL+'admin/salvar-musculo',
	            data: params,
	            dataType: 'json',
	            success: function(resp){
	                if(resp.retorno != 'sucesso'){
	                    alert(resp.msg); 
	                    return false;
	                }else {
	                    alert(resp.msg);
			    window.location = BASE_URL+'admin/musculo';
	                }
	            }
	    })
	    return false;
     })
     
     $('#btAlterar').click(function(){
            openAguarde();
    
	    var params = $( "#frmMusculo" ).serialize();
	
	    $.ajax({
	            type:'post',
	            url: BASE_URL+'admin/alterar-musculo',
	            data: params,
	            dataType: 'json',
	            success: function(resp){
	                if(resp.retorno != 'sucesso'){
	                    alert(resp.msg); 
	                    return false;
	                }else {
	                    alert(resp.msg);
			    window.location = BASE_URL+'admin/musculo';
	                }
	            }
	    })
	    return false;
     })     
})

/*
function salvarMusculo() {
    openAguarde();
    
    var params = $( "#frmMusculo" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-musculo',
            data: params,
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    alert(resp.msg);
		    window.location = BASE_URL+'admin/musculo';
                }
            }
    })
}

function alterarMusculo() {
    openAguarde();
    
    var params = $( "#frmMusculo" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-musculo',
            data: params,
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    alert(resp.msg);
		    window.location = BASE_URL+'admin/musculo';
                }
            }
    })
}
*/
</script>

<div data-role="header">
    <h1>Cadastrar M&uacute;sculo</h1>
    <a href="<?= $this->baseUrl() ?>/admin/musculo" data-theme="b">
        <
    </a>
	
	<?php if( !isset($this->aMusculo) ): ?>
        <a href="#" id="btSalvar" data-theme="b">Salvar</a>
    <?php else: ?>
        <a href="#" id="btAlterar" data-theme="b">Alterar</a>
    <?php endif; ?>
	
</div>

<div class="main-content" data-role="content">

	<form id="frmMusculo" method="post">
		
		<input type="hidden" name="id" id="id" value="<?= (isset($this->aMusculo))? $this->aMusculo['id'] : '' ?>" />
		
		<p>
			<label>M&uacute;sculo: </label>
			<input type="text" name="ds_musculo" id="ds_musculo" placeholder="Informe um m&uacute;sculo" value="<?= (isset($this->aMusculo))? utf8_encode($this->aMusculo['musculo']) : '' ?>" style="width: 100%" />
		</p>
	</form>
	
</div>	