<?php #Utils_Print::printvardie($this->aExercicio['musculo_id']); ?>
<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/jasny-bootstrap.css' ?>'> 
<script type="text/javascript" src="<?php echo $this->baseUrl().'/bootstrap/js/jasny-bootstrap.js' ?>"></script>

<h3 class="page-header">
    <?php if( !isset($this->aExercicio) ): ?>
        <i class="ace-icon"></i> Adicionar Exerc&iacute;cio
    <?php else: ?>
        <i class="ace-icon fa fa-edit"></i> Alterar Exerc&iacute;cio
    <?php endif; ?>
</h3>

<div>
    
    <?php if( !isset($this->aExercicio) ): ?>
        <form id="frmExercicio" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/admin/salvar-exercicio">
    <?php else: ?>
        <form id="frmExercicio" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/admin/alterar-exercicio">
    <?php endif; ?>
        
        <input type="hidden" name="id" id="id" value="<?= (isset($this->aExercicio))? $this->aExercicio['id'] : '' ?>" />
        <input type="hidden" name="url" id="url" value="<?= (isset($this->aExercicio))? $this->aExercicio['url'] : '' ?>" />
        <input type="hidden" name="thumbnail" id="thumbnail" value="<?= (isset($this->aExercicio))? $this->aExercicio['thumbnail'] : '' ?>" />
        
        <p>
            <label>M&uacute;sculos: </label>
            <select name="musculo_id" id="musculo_id" style="width: 100%;">
                <option value="">Selecione um m&uacute;sculo</option>
                <?php foreach($this->aMusculos['results'] as $musculo): ?>
                
                    <?php if( isset($this->aExercicio) ): ?>
                        <?php if($this->aExercicio['musculo_id'] == $musculo['id']): ?>
                            <option selected="selected" value="<?= $musculo['id'] ?>"><?= utf8_encode($musculo['musculo']) ?></option>
                        <?php endif; ?>    
                    <?php endif; ?>
                
                    <option value="<?= $musculo['id'] ?>"><?= utf8_encode($musculo['musculo']) ?></option>
                    
                <?php endforeach; ?>
            </select>
        </p>
        
        <p>
            <label>Exerc&iacute;cio: </label>
            <input type="text" name="ds_exercicio" id="ds_exercicio" placeholder="Informe um exerc&iacute;cio" value="<?= (isset($this->aExercicio))? utf8_encode($this->aExercicio['exercicio']) : '' ?>" style="width: 100%" />
        </p>
        
        <div class="widget-body">
            <div class="widget-main">
                <div class="fileinput fileinput-new" data-provides="fileinput">


                    <div style="display: inline-block;">
                        <span class="btn btn-default btn-file">
                            <span class="fileinput-new">
                                <i class="ace-icon fa fa-camera"> </i> Adicionar Imagem
                            </span>
                            <span class="fileinput-exists">Modificar</span>
                            <input type="file" name="fileImage" id="fileImage" />
                        </span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>

                        <br>
                        <span style="font-size: 12px; color: #333;">
                            Arquivo de imagem nos formatos: jpg, png, gif  <br>
                            Tamanho m&aacute;ximo: 5M
                        </span>
                    </div>
                    <div style="width: 90%; height: 180px;" class="ace-file-input ace-file-multiple fileinput-preview thumbnail" data-trigger="fileinput">
                        <?php if($this->aExercicio['thumbnail']): ?>
                            <img src="<?php echo $this->baseUrl().$this->aExercicio['thumbnail'] ?>" />
                        <?php else: ?>
                            <span data-title="Clique aqui para adicionar uma imagem" class="ace-file-container">
                                <span data-title="Sem arquivo ..." class="ace-file-name">
                                    <i class=" ace-icon ace-icon fa fa-cloud-upload"></i>
                                </span>
                            </span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- End Modal Confirm -->