<link rel='stylesheet' type='text/css' href="<?php echo $this->baseUrl().'/bootstrap/css/jasny-bootstrap.css' ?>"> 
<script type="text/javascript" src="<?php echo $this->baseUrl().'/bootstrap/js/jasny-bootstrap.js' ?>"></script>
<script>
jQuery(function(){

    var files;

    // Add events
    $('input[type="file"]').on('change', prepareUpload);

    // Grab the files and set them to our variable
    function prepareUpload(event)
    {
      files = event.target.files;
    }

    $('#btSalvar').on('click', uploadFiles);

    // Catch the form submit and upload the files
    function uploadFiles(event)
    {
      openAguarde(); 

      event.stopPropagation(); // Stop stuff happening
      event.preventDefault(); // Totally stop stuff happening

        // START A LOADING SPINNER HERE

        // Create a formdata object and add the files
        var data = new FormData(); 
        if(files) {                               
            $.each(files, function(key, value) {                
                data.append(key, value);
            });
        }

        var params = $( "#frmExercicio" ).serialize();

        var fileImage = $('input[type=file]').val();
        if( fileImage ) {
            params += '&files='+fileImage;
        }

        <?php if( !isset($this->aAluno) ): ?>
            salvarExercicio(params, data);
        <?php else: ?>
            alterarExercicio(params, data);
        <?php endif; ?>

    }        
    
});

function salvarExercicio(params, data) {
    openAguarde();
    
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-exercicio-mobile?'+params,
            data: data,
            cache: false,
            dataType: 'json',
            processData: false, // Dont process the files
        contentType: false, // Set content type to false as jQuery will tell the server its a query string request
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else {
                    alert(resp.msg);
                    window.location = BASE_URL+'admin/exercicio';
                }
            }
    })
}

function alterarExercicio(params, data) {
    openAguarde();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-exercicio-mobile?'+params,
            data: data,
            cache: false,
            dataType: 'json',
            processData: false, // Dont process the files
        contentType: false, // Set content type to false as jQuery will tell the server its a query string request
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else {
                    alert(resp.msg);
                    window.location = BASE_URL+'admin/exercicio';
                }
            }
    })
}
</script>

<div data-role="header">
    <h1>Exerc&iacute;cio</h1>
    <a href="javascript:changePage('exercicio')" data-theme="b">
        <
    </a>
    
    <?php if( !isset($this->aExercicio) ): ?>
        <a href="#" id="btSalvar" data-theme="b">Salvar</a>
    <?php else: ?>
        <a href="#" id="btSalvar" data-theme="b">Alterar</a>
    <?php endif; ?>
	
</div>

<div class="main-content" data-role="content">
    
    <form id="frmExercicio" method="post" enctype="multipart/form-data">
        
        <input type="hidden" name="id" id="id" value="<?= (isset($this->aExercicio))? $this->aExercicio['id'] : '' ?>" />
        
        <p>
            <label>M&uacute;sculos: </label>
            <select name="musculo_id" id="musculo_id" style="width: 100%;">
                <option value="">Selecione um m&uacute;sculo</option>
                <?php foreach($this->aMusculos['results'] as $musculo): ?>
                
                    <?php if( isset($this->aExercicio) ): ?>
                        <?php if($this->aExercicio['musculo_id'] == $musculo['id']): ?>
                            <option selected="selected" value="<?= $musculo['id'] ?>"><?= ($musculo['musculo']) ?></option>
                        <?php endif; ?>    
                    <?php endif; ?>
                
                    <option value="<?= $musculo['id'] ?>"><?= ($musculo['musculo']) ?></option>
                    
                <?php endforeach; ?>
            </select>
        </p>
        
        <p>
            <label>Exerc&iacute;cio: </label>
            <input type="text" name="ds_exercicio" id="ds_exercicio" placeholder="Informe um exerc&iacute;cio" value="<?= (isset($this->aExercicio))? ($this->aExercicio['exercicio']) : '' ?>" style="width: 100%" />
        </p>
        
        <label>Imagem do Exerc&iacute;cio: </label>
        
        <div class="widget-body" style="padding-left: 2px;">
                <div class="widget-main">
                    <div class="fileinput fileinput-new" data-provides="fileinput">
                        <div style="width: 300px;">
                            <span class="btn btn-default btn-file">             
                                <input type="file" name="fileImage" id="fileImage" />
                            </span>

                            <span style="font-size: 12px; color: #333;">
                                Arquivo de imagem nos formatos: jpg, png, gif  <br>
                                Tamanho m&aacute;ximo: 10M
                            </span>
                        </div>
                        <div style="width: 90%; height: 180px; border: 3px solid #ddd;" class="ace-file-input ace-file-multiple fileinput-preview thumbnail" data-trigger="fileinput">
                            <?php if($this->aExercicio['thumbnail']): ?>
                                <img src="<?php echo $this->baseUrl().$this->aExercicio['thumbnail'] ?>" />
                            <?php else: ?>
                                <div class="ace-file-container" style="margin: 25% 0; font-weight: bold;">Imagem do Exerc&iacute;cio</div>
                            <?php endif; ?>
                        </div>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput" data-role="button"  data-icon="delete">Remove foto</a>
                    </div>
                </div>
        </div> 
        
    </form>
</div>
<!-- End Modal Confirm -->