<script>
$(function(){
    loadPeriodizacao();
    changeComboTreino();
    
    $('#btnEntrar').click(function(){
        var params = $('#form-periodizacao').serialize();
        
        $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-periodizacao',
            data: params,
            success: function(resp) {
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); return false;
                }else {
                    loadPeriodizacao();
                    changeComboTreino();
                    carregarPeriodizacao();
                }
            }
        });
        //$('#showPeriodizacao').load(BASE_URL+'admin/salvar-periodizacao', params);
    });
    
});

function removePeriodizacao(periodizacao_id) {
    $.ajax({
        type:'post',
        url: BASE_URL+'admin/excluir-periodizacao',
        data: {periodizacao_id: periodizacao_id},
        dataType:'json',
        success: function(resp){
            if(resp.retorno !== 'sucesso'){
                alert(resp.msg); return false;
            }else {
                loadPeriodizacao();
                changeComboTreino();
                carregarPeriodizacao();
            }
        }
    });
}

function loadPeriodizacao(){
    $('#showPeriodizacao').load(BASE_URL+'admin/grid-periodizacao-ficha', {ficha_id: $('#ficha_id').val()});
}

function changeComboTreino() {
    $('#cbTreinoPer').load(BASE_URL+'admin/change-combo-treino', {ficha_id: $('#ficha_id').val()});    
}
</script>
<h3 class="page-header">
    <i class="ace-icon fa fa-cogs"> </i> Periodiza&ccedil;&atilde;o
</h3>

<?php 
$resTreinos = null;

$treinos = array(1,2,3,4,5,6,7,8,9,10);

$dias = array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30); 

if(isset($this->aPeriod['results'])){

    $aPeriod = $this->aPeriod['results'];    
    
    
    $aTreinosBd = array();
    foreach ($aPeriod as $dado):
        $aTreinosBd[] = $dado['treino'];
    endforeach;
    
    $resTreinos = array_diff($treinos, $aTreinosBd);
    //Utils_Print::printvardie($resTreinos); 
}
?>

<form id="form-periodizacao">
    <input type="hidden" name="ficha_id" id="ficha_id" value="<?php echo $this->ficha_id ?>" />
    
    <div class="control-group">
        <label class="control-label" for="inputTreino">Sess&atilde;o:</label>
        <div class="controls">
            <div class="input-group">
                <select name="cbTreinoPer" id="cbTreinoPer" class="form-control">
                </select>
            </div>
        </div>
    </div>
    <br>
    
    <div class="control-group">
        <label class="control-label" for="inputDescricao" id="inputDescricao">Descricao:</label>
        <div class="controls">
            <div class="input-group">                
                <input name="txtDescricao" id="txtDescricao" type="text" value="<?php ?>" placeholder="Ex: 3 x 10">
            </div>
        </div>
    </div>

    <br>

    <div class="control-group">
        <label class="control-label" for="inputDias">Dias:</label>
        <div class="controls">
            <div class="input-group">
                <!--<input type="text" name="txtDias" class="col-md-4" id="txtDias" value="<?php ?>" class="form-control" placeholder="">-->
                <select name="txtDias" id="txtDias">
                  <?php foreach($dias as $dia): ?>	
                     <option value="<?= $dia ?>"><?= $dia ?></option>
                  <?php endforeach; ?>                  
                </select> &nbsp;
                <button type="button" class="btn btn-primary" id="btnEntrar"><i class="ace-icon fa fa-adn"></i>Adicionar</button>
            </div>
        </div>
    </div>
    
    <br>
    <div id="showPeriodizacao"></div>
</form>