<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/jasny-bootstrap.css' ?>'> 
<script type="text/javascript" src="<?php echo $this->baseUrl().'/bootstrap/js/jasny-bootstrap.js' ?>"></script>

<script type="text/javascript">
jQuery(function(){    
    
    $('#ckVerSenha').click(function(){
        var value = $('input[name="ckVerSenha"]:checked').val();

        if(value == 'on'){
            $('#senhaCad').hide().attr('disabled', true);
            $('#hdsenha').val( $('#senhaCad').val() ).show().attr('disabled', false);
        }else {
            $('#hdsenha').hide().attr('disabled', true);
            $('#senhaCad').show().attr('disabled', false);
        }
    })
    
    $('#senhaCad').keyup(function(){
        var senha = $(this).val();
        $('#hdsenha').val( senha );
    })
})
</script>

<?php #Utils_Print::printvardie($this->aProfessor['results']); ?>


<h3 class="page-header">
    <?php if( !isset($this->aProfessor) ): ?>
    <i class="ace-icon fa fa-users"></i> Cadastrar Professor
    <?php else: ?>
        <i class="ace-icon fa fa-edit"></i> Editar Professor
    <?php endif; ?>
        
</h3>

<div>
    
    <?php if( !isset($this->aProfessor) ): ?>
        <form id="frmProfessor" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/admin/salvar-professor">
     <?php else: ?>
        <form id="frmProfessor" method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/admin/alterar-professor">
    <?php endif; ?>
            
        <input type="hidden" name="id" id="id" value="<?= (isset($this->aProfessor))? $this->aProfessor['results']['id'] : '' ?>" />
        <input type="hidden" name="url" id="url" value="<?= (isset($this->aProfessor))? $this->aProfessor['results']['url'] : '' ?>" />
        <input type="hidden" name="thumbnail" id="thumbnail" value="<?= (isset($this->aProfessor))? $this->aProfessor['results']['thumbnail'] : '' ?>" />
        
    
        <div class="form-group">
            <label class="" >Nome do professor:</label>
            <br>
            <input id="nm_professor" name="nm_professor" style="width: 100%" class="form-control" value="<?php echo utf8_encode($this->aProfessor['results']['nm_professor']) ?>" placeholder="Informe o nome do professor" type="text"> 
        </div>
        
        <div class="form-group">
            <label class="control-label" for="inputEmail">Email do professor:</label>
            <div class="controls">
                <div class="input-group">
                    <span class="input-group-addon">@</span>
                    <input type="text" name="email" id="email" class="form-control" placeholder="E-mail do professor" value="<?php echo $this->aProfessor['results']['email'] ?>">
                    <input type="hidden" name="emailCompara" id="emailCompara" value="<?php echo $this->aProfessor['results']['email'] ?>">
                </div>
            </div>
        </div>
        
        <?php if(!isset($this->aProfessor['results']['id'])): ?>
            <div class="form-group">
                <label class="control-label" for="inputEmail">Senha provis&oacute;ria: <span style="color: red; font-size: 11px;">(Senha para o Prof. entrar no sistema)</span></label>
                <div class="controls">
                    <div class="input-group">
                        <span class="input-group-addon"><input type="checkbox" id="ckVerSenha" name="ckVerSenha" /></span>
                        <input name="senhaCad" id="senhaCad" style="width: 100%" class="form-control" placeholder="Informe uma senha provis&oacute;ria" type="password">                     
                        <input name="senhaCad" id="hdsenha" style="width: 100%; display: none;" class="form-control" placeholder="Informe a senha provis&oacute;ria do professor" type="text">                     
                    </div>
                </div>
            </div>
        <?php endif; ?>
        
        
        <div class="widget-body">
            <div class="widget-main" style="margin: 15px 0; padding: 0;">
                <div class="fileinput fileinput-new" data-provides="fileinput">


                    <div style="display: inline-block; width: 340px;">
                        <span class="btn btn-default btn-file">
                            <span class="fileinput-new">
                                <i class="ace-icon fa fa-camera"> </i> Adicionar Imagem
                            </span>
                            <span class="fileinput-exists">Modificar</span>
                            <input type="file" name="fileImage" id="fileImage" />
                        </span>
                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>

                        <br>
                        <span style="font-size: 12px; color: #333;">
                            Arquivo de imagem nos formatos: jpg, png, gif  <br>
                            Tamanho m&aacute;ximo: 5M
                        </span>
                    </div>
                    <div  style="width: 100%; height: 140px;" class="ace-file-input ace-file-multiple fileinput-preview thumbnail" data-trigger="fileinput">
                        <?php if($this->aProfessor['results']['thumbnail']): ?>
                            <img src="<?php echo $this->baseUrl().$this->aProfessor['results']['thumbnail'] ?>" />
                        <?php else: ?>
                            <span data-title="Clique aqui para adicionar uma imagem" class="ace-file-container">
                                <span data-title="Sem arquivo ..." class="ace-file-name">
                                    <i class=" ace-icon ace-icon fa fa-cloud-upload"></i>
                                </span>
                            </span>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        
    </form>
</div>
<!-- End Modal Confirm -->