<script>
function alterarMedidasOsseas() {        
    openAguarde();
    
    if( !$('#peso').val() || $('#peso').val() == '0.00' ){
        alert('Informe o peso do aluno.');
        closeAguarde();
        return false;
    }else
    if( !$('#altura').val() || $('#altura').val() == '0.00' ){
        alert('Informe a altura do aluno.');
        closeAguarde();
        return false;        
    }else
    if( !$('#dt_reavaliacao').val() ){
        alert('Informe a data da próxima avaliação do aluno.');
        closeAguarde();
        return false;
    }   
    
    var params = $( "#formAvaliacao" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-avaliacao-mobile',
            data: params,
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno == 'sucesso'){
                    alert(resp.msg);
                    gerarResultadoAvaliacaoFisica( $('#avaliacao_id').val() );

                }else if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else  {
                    alert('ERROR: Retorno incorreto.');
                    closeAguarde();
                    return false;
                }
            }
    })            
}


function gerarResultadoAvaliacaoFisica(avaliacao_id) {
    $.ajax({
            type:'post',
            url: BASE_URL+'admin/gerar-resultado-avaliacao',
            data: {avaliacao_id: avaliacao_id},
            dataType: 'json',
            async: false,
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg);
                    closeAguarde(); 
                    return false;
                }else 
                if(resp.retorno == 'sucesso'){              
                    
                    //RENDERIZAR
                    window.location = BASE_URL+'admin/ver-avaliacao-fisica/avaliacao_id/'+avaliacao_id;

                }else {
                    alert('ERROR: Retorno incorreto.');
                    closeAguarde();
                    return false;
                }
            }
    });
}
</script>
<?php 
    
    $data = list($ano, $mes, $dia) = explode('-', $this->dadosAluno['dt_nascimento']);
    $dtAtual = date('Y');    
    $idade = ( $dtAtual - $ano );    
    $sexo = ($this->dadosAluno['sexo']=='M')? 'MASCULINO' : 'FEMININO';
    
    foreach($this->aAvaliacao as $key => $item) {    
	    if($item == '0.00'){
	        $this->aAvaliacao[$key] = '';
	    }else
	    if($key != 'id' && $key != 'academia_id' && $key != 'aluno_id' && $key != 'data' && $key != 'dt_reavaliacao' && $key != 'protocolo' && $key != 'situacao') {
	        $this->aAvaliacao[$key] = Utils_Date::formataMoeda($item);
	    }
    }
    
   #Utils_Print::printvardie($this->aAvaliacao);
    
    
?>

<div data-role="header">
    <h1>Avalia&ccedil;&atilde;o</h1>
    <a href="#" onclick="window.location='<?= $this->baseUrl() ?>/admin/listar-avaliacoes-aluno/matricula/<?= $this->aAvaliacao['aluno_id'] ?>'" data-theme="b">
        <
    </a>
</div>

<div>

<div id="contentGeral">

    <div class="page-content">

        <div class="row">
            <div class="col-xs-12">

            <form id="formAvaliacao">    
                <input type="hidden" name="avaliacao_id" id="avaliacao_id" value="<?= $this->aAvaliacao['id']; ?>" />
                <input type="hidden" name="aluno_id" id="aluno_id" value="<?= $this->aAvaliacao['aluno_id']; ?>" />                
                <input type="hidden" name="sexo" id="sexo" size="8" readonly="true" value="<?= $sexo; ?>" style="background: #eee; color: #444; cursor: no-drop;" />

                <table width="100%" style="margin: 0 auto;" border="0">
                <tbody>
                    <tr>
                        <td>Peso:<br><input type="text" name="peso" id="peso" size="5" value="<?= $this->aAvaliacao['peso'] ?>" /></td>
                        <td>Altura:<br><input type="text" name="altura" id="altura" size="5" value="<?= $this->aAvaliacao['altura'] ?>" /></td>             
                        <td>Idade:<br><input type="text" name="idade" id="idade" size="5" readonly="true" value="<?= $idade ?>" style="background: #eee; color: #444; cursor: no-drop;" /></td>
                    </tr>
                    <tr>
                        
                    </tr>
                    <tr>
                       <td width="38%">Data Avalia&ccedil;&atilde;o:</td><td colspan="2"><input type="text" name="data" id="data" size="8" readonly="true" value="<?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['data']) ?>" style="background: #eee; color: #444; cursor: no-drop;" /> </td>
                    </tr>
                    <tr>
                        <td>Data Reavalia&ccedil;&atilde;o:</td><td colspan="2"><input type="text" name="dt_reavaliacao" id="dt_reavaliacao" size="8" value="<?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['dt_reavaliacao']) ?>" placeholder="dd/mm/YYYY" /></td>
                    </tr>
                    <tr>
                        <td>Protocolo:</td>
                        <td colspan="2">
                           <select id="protocolo" name="protocolo">
                                <option value="<?= $this->aAvaliacao['protocolo'] ?>"><?= $this->aAvaliacao['protocolo'] ?></option>
                                <option value="pollock3dobras">Pollock 3 dobras</option>
                                <option value="pollock7dobras">Pollock 7 dobras</option>
                                <option value="guedes">Guedes</option>
                                <option value="petroski">Petroski</option>
                                <option value="durnin">Durnin</option>
                                <option value="durnin">Mcardle</option> 
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            
           <br>	
            
            <table width="100%" border="0">
                <thead>
                    <tr>
                        <td style="background: #222; padding: 8px; color: #fff;" colspan="2" align="center"><b>Dobras Cut&acirc;neas</b> </td>
                    </tr>
                </thead>
                <tbody>       
                    <tr>
                        <td style="color: #666;">Medidas em: mm</td>                        
                    </tr>	             
                    <tr>
                        <td><input type="text" name="PE" id="PE" size="5" value="<?= $this->aAvaliacao['PE'] ?>" placeholder="T&oacute;rax" /></td>                        
                    </tr>
                    <tr>
                        <td><input type="text" name="BI" id="BI" size="5" value="<?= $this->aAvaliacao['BI'] ?>" placeholder="B&iacute;ceps" /></td>
                    </tr>
                    <tr>
                        <td><input type="text" name="TR" id="TR" size="5" value="<?= $this->aAvaliacao['TR'] ?>" placeholder="Tr&iacute;ceps" /></td>                        
                    </tr>
                    <tr>
                        <td><input type="text" id="AX" name="AX" size="5" value="<?= $this->aAvaliacao['AX'] ?>" placeholder="Axilar M&eacute;dia" /></td>
                    </tr>
                    <tr>    
                        <td><input type="text" id="SB" name="SB" size="5"  value="<?= $this->aAvaliacao['SB'] ?>" placeholder="Subescapular" /></td>
                    </tr>
                    <tr>    
                        <td><input type="text" name="AB" id="AB" size="5"  value="<?= $this->aAvaliacao['AB'] ?>" placeholder="Abdome" /></td>
                    </tr>
                    <tr>    
                        <td><input type="text" name="SI" id="SI" size="5" value="<?= $this->aAvaliacao['SI'] ?>" placeholder="Supra Il&iacute;aca" /></td>
                    </tr>
                    <tr>    
                        <td><input type="text" name="CX" id="CX" size="5" value="<?= $this->aAvaliacao['CX'] ?>" placeholder="Coxa" /></td>
                    </tr>
                    <tr>    
                        <td colspan="3"><input type="text" name="PA" id="PA" size="5" value="<?= $this->aAvaliacao['PA'] ?>" placeholder="Panturrilha" /></td>
                    </tr>
                </tbody>
            </table>
            
            
            <br>	
            
    <table width="100%" border="0">
        <thead>
            <tr>
                <td style="background: #222; padding: 8px; color: #fff;" colspan="2" align="center"><b>Medidas Lineares</b> </td>
            </tr>
        </thead>
        <tbody>       
            <tr>
                <td style="color: #666;">Medidas em: mm</td>                        
            </tr>	             
            <tr>
                <td colspan="2"><input type="text" name="torax" id="torax" size="5" value="<?= $this->aAvaliacao['torax'] ?>" placeholder="T&oacute;rax" /></td>                        
            </tr>
            <tr>
                <td colspan="2"><input type="text" name="abdomen" id="abdomen" size="5" value="<?= $this->aAvaliacao['abdomen'] ?>" placeholder="Abdome" /></td>
            </tr>
            <tr>
                <td colspan="2"><input type="text" name="cintura" id="cintura" size="5" value="<?= $this->aAvaliacao['cintura'] ?>" placeholder="Cintura" /></td>                        
            </tr>
            <tr>
                <td colspan="2"><input type="text" id="quadril" name="quadril" size="5" value="<?= $this->aAvaliacao['quadril'] ?>" placeholder="Quadril" /></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="ombro" id="ombro" size="5" value="<?= $this->aAvaliacao['ombro'] ?>" placeholder="Ombros"/></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="pescoco" id="pescoco" size="5" value="<?= $this->aAvaliacao['pescoco'] ?>" placeholder="Pesco&ccedil;o"/></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="punho" id="punho" size="5" value="<?= $this->aAvaliacao['punho'] ?>" placeholder="Punho"/></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="joelho" id="joelho" size="5" value="<?= $this->aAvaliacao['joelho'] ?>" placeholder="Joelho"/></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="tornozelo" id="tornozelo" size="5" value="<?= $this->aAvaliacao['tornozelo'] ?>" placeholder="Tornozelo"/></td>
            </tr>
            <tr>    
                <td colspan="2"><input type="text" name="escapular" id="escapular" size="5" value="<?= $this->aAvaliacao['escapular'] ?>" placeholder="Escapular"/></td>
            </tr>
            <tr>    
                <td width="50%"><input type="text" id="braco_direito_contraido" name="braco_direito_contraido" size="5"  value="<?= $this->aAvaliacao['braco_direito_contraido'] ?>" placeholder="Bra&ccedil;o direto contraido" /></td>
                <td><input type="text" name="braco_esquerdo_contraido" id="braco_esquerdo_contraido" size="5"  value="<?= $this->aAvaliacao['braco_esquerdo_contraido'] ?>" placeholder="Bra&ccedil;o esquerdo contraido" /></td>
            </tr>
            <tr>    
                <td><input type="text" id="braco_direito_relaxado" name="braco_direito_relaxado" size="5"  value="<?= $this->aAvaliacao['braco_direito_relaxado'] ?>" placeholder="Bra&ccedil;o direito relaxado" /></td>
                <td><input type="text" name="braco_esquerdo_relaxado" id="braco_esquerdo_relaxado" size="5"  value="<?= $this->aAvaliacao['braco_esquerdo_relaxado'] ?>" placeholder="Bra&ccedil;o esquerdo relaxado" /></td>
            </tr>
            <tr>    
                <td><input type="text" id="antebraco_direito" name="antebraco_direito" size="5"  value="<?= $this->aAvaliacao['antebraco_direito'] ?>" placeholder="Antebra&ccedil;o direito" /></td>
                <td><input type="text" name="antebraco_esquerdo" id="antebraco_esquerdo" size="5"  value="<?= $this->aAvaliacao['antebraco_esquerdo'] ?>" placeholder="Antebra&ccedil;o esquerdo" /></td>
             </tr>
            <tr>    
                <td><input type="text" name="coxa_direita" id="coxa_direita" size="5" value="<?= $this->aAvaliacao['coxa_direita'] ?>" placeholder="Coxa medial direita" /></td>
                <td><input type="text" name="coxa_esquerda" id="coxa_esquerda" size="5" value="<?= $this->aAvaliacao['coxa_esquerda'] ?>" placeholder="Coxa medial esquerda" /></td>
            </tr>
            <tr>    
                <td><input type="text" name="panturrilha_direita" id="panturrilha_direita" size="5" value="<?= $this->aAvaliacao['panturrilha_direita'] ?>" placeholder="Panturrilha direita" /></td>
                <td><input type="text" name="panturrilha_esquerda" id="panturrilha_esquerda" size="5" value="<?= $this->aAvaliacao['panturrilha_esquerda'] ?>" placeholder="Panturrilha esquerda" /></td>
            </tr>
        </tbody>
    </table>
            <br>	
            
    <table width="100%" border="0">
        <thead>
            <tr>
                <td style="background: #222; padding: 8px; color: #fff;" colspan="2" align="center"><b>Diametros Osseos</b> </td>
            </tr>
        </thead>
        <tbody>       
            <tr>
                <td style="color: #666;">Medidas em: mm</td>                        
            </tr>	             
            <tr>
                <td><input type="text"  name="biestiloide" id="biestiloide" size="5" value="<?= $this->aAvaliacao['biestiloide'] ?>" placeholder="Biestil&oacute;ide (punho)" /></td>                        
            </tr>
            <tr>
                <td><input type="text" name="biepicondiliano_femur" id="biepicondiliano_femur" size="5" value="<?= $this->aAvaliacao['biepicondiliano_femur'] ?>" placeholder="Biepicondiliano do f&ecirc;mur" /></td>
            </tr>
            <tr>
                <td><input type="text" name="biacromial" id="biacromial" size="5" value="<?= $this->aAvaliacao['biacromial'] ?>" placeholder="Biacromial"  /></td>                        
            </tr>
            <tr>
                <td><input type="text" id="biileocristal" name="biileocristal" size="5" value="<?= $this->aAvaliacao['biileocristal'] ?>" placeholder="Biileocristal" /></td>
            </tr>
            <tr>    
                <td><input type="text" id="bitrocanteriano" name="bitrocanteriano" size="5"  value="<?= $this->aAvaliacao['bitrocanteriano'] ?>" placeholder="Bitrocanteriano" /></td>
            </tr>
            <tr>    
                <td><input type="text" id="biepicondiliano_umero" name="biepicondiliano_umero" size="5"  value="<?= $this->aAvaliacao['biepicondiliano_umero'] ?>" placeholder="Biepicondiliano do &uacute;mero"/></td>
            </tr>
            <tr>    
                <td><input type="text" name="bimaleolar" id="bimaleolar" size="5"  value="<?= $this->aAvaliacao['bimaleolar'] ?>" placeholder="Bimaleolar"/></td>
            </tr>
            <tr>
                <td>
                    <button type="button" onclick="alterarMedidasOsseas()" data-theme="b">Alterar</button>                             
                </tr>
            </tr>
        </tbody>
    </table>
            
            </form>
                
            </div>
        </div>
    </div>

</div>
</div>