<style>
    .ui-dialog{background: #fff;}
    #frmNovoTreino tr th {background: #ccc; padding: 3px 3px 3px 3px;}
    #frmNovoTreino tr td { padding: 4px; }
    #frmNovoTreino table,th,td { border-collapse:collapse;}
    #frmNovoTreino img {cursor: pointer;}
</style>


<?php #echo'<pre>'; print_r($this->dadosFicha); die; ?>

<form id="frmNovoTreino">
    
    <input type="hidden" name="aluno_id" id="aluno_id" value="<?= $this->aluno_id; ?>" />
    
    <fieldset>
            <legend>Dados da Ficha</legend>

            <table width="100%">
                <tr>
                    <td width="14%"><b>Aluno: </b></td>
                    <td><?php echo $this->dadosAluno['matricula'] ?> - <?php echo utf8_encode($this->dadosAluno['nome']) ?></td>
                </tr>
                <tr>
                    <td><b>Professor: </b></td>                    
                    <td>
                    <?php if($this->sessao->perfil_id != 2 && $this->sessao->perfil_id != 4): ?>    
                        <select name="cbProfessor" id="cbProfessor" class="form-control">                                                        
                            <option value="">Selecione um professor...</option>                            
                                
                            <?php foreach ($this->aProfessores['results'] as $professor): ?>
                                <option <?php echo ($this->dadosFicha['professor_id'] == $professor['id']? 'selected' : '') ?> value="<?php echo $professor['id'] ?>"><?php echo utf8_encode($professor['nm_professor']) ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php elseif($this->sessao->perfil_id == 4): ?>
                        <select name="cbProfessor" id="cbProfessor" class="form-control">
                            <?php foreach ($this->aProfessores['results'] as $professor): ?>
                                <?php if( $professor['email'] == $this->sessao->email ): ?>
                                    <option selected="selected" value="<?php echo $professor['id'] ?>"><?php echo utf8_encode($professor['nm_professor']) ?></option>
                                <?php endif; ?>                            
                            <?php endforeach; ?>                        
                        </select>
                    <?php else: ?>
                        <select name="cbProfessor" id="cbProfessor" class="form-control">
                            <option value="" selected="selected"><?php echo $this->sessao->nome; ?></option>
                        </select>
                    <?php endif; ?>    
                    </td>
                </tr>
                <tr>
                    <td><b>Descri&ccedil;&atilde;o: </b></td>  
                    <td>
                        <input type="text" name="descricao" class="form-control" id="descricao" style="font-size: 16px;" value="<?php echo utf8_encode($this->dadosFicha['ds_ficha']) ?>" placeholder="Ex: Treino m&ecirc;s de Janeiro de 2014" />
                    </td>
                </tr>
                <tr>
                    <td valign="top"><b>Objetivo:</b></td>
                    <td>
                        <textarea name="objetivo" id="objetivo" class="form-control" rows="5"><?php echo ($this->dadosFicha['objetivo'])? utf8_encode($this->dadosFicha['objetivo']) : '' ?></textarea>
                    </td>
                </tr>
                <tr>
                    <td valign="top"><b>Observação:</b></td>
                    <td>
                        <textarea name="observacao" id="observacao" class="form-control" rows="5"><?php echo ($this->dadosFicha['observacao'])? utf8_encode($this->dadosFicha['observacao']) : '' ?></textarea>
                    </td>
                </tr>
            </table>
    </fieldset>

</form>
		
		
