
<h3 class="page-header">
    <i class="ace-icon fa fa-lock"> </i> Trocar Senha
</h3>

<form id="form-trocar-senha" method="post">

    <div class="form-group">
        <label class="control-label" for="inputPassword">Senha atual:</label>
        <div class="controls">
            <div class="input-group">
                <span class="input-group-addon"><i class="ace-icon fa fa-key"> </i></span>
                <input name="senhaAtual" id="senhaAtual" style="width: 100%" class="form-control" placeholder="Informe a senha atual" type="password" />
            </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="control-label" for="inputPassword">Nova Senha:</label>
        <div class="controls">
            <div class="input-group">
                <span class="input-group-addon"><i class="ace-icon fa fa-key"> </i></span>
                <input name="novaSenha" id="novaSenha" style="width: 100%" class="form-control" placeholder="Informe a nova senha" type="password" />
            </div>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="inputPassword">Confirma nova Senha:</label>
        <div class="controls">
            <div class="input-group">
                <span class="input-group-addon"><i class="ace-icon fa fa-key"> </i></span>
                <input name="confirmaNovaSenha" id="confirmaNovaSenha" style="width: 100%" class="form-control" placeholder="Confirme a nova senha" type="password" />
            </div>
        </div>
    </div>
    
</form>