<style>
    .ui-dialog{background: #fff;}
    #formAvaliacaoMedidasOsseas tr th {background: #ccc; padding: 3px 0 3px 0;}
    #formAvaliacaoMedidasOsseas tr td { padding: 4px 0; }
    #formAvaliacaoMedidasOsseas table,th,td { border-collapse:collapse;}
    #formAvaliacaoMedidasOsseas img {cursor: pointer;}
    
    .medidas {font-size: 12px; color: green;}
</style>
<script src="<?= $this->baseUrl() ?>/js/jquery/meiomask.js"></script>
<script>
jQuery(function(){
    $('#biacromial').setMask('decimal-us');
    $('#biileocristal').setMask('decimal-us');
    $('#biestiloide').setMask('decimal-us');
    $('#biepicondiliano_femur').setMask('decimal-us');
    $('#biepicondiliano_umero').setMask('decimal-us');
    $('#bimaleolar').setMask('decimal-us');
    $('#bitrocanteriano').setMask('decimal-us');
});
</script>

<?php 
    
    $data = list($ano, $mes, $dia) = explode('-', $this->dadosAluno['dt_nascimento']);
    $dtAtual = date('Y');    
    $idade = ( $dtAtual - $ano );    
    $sexo = ($this->dadosAluno['sexo']=='M')? 'MASCULINO' : 'FEMININO';
?>

<form name="formAvaliacaoMedidasOsseas" id="formAvaliacaoMedidasOsseas">
    
    <input type="hidden" name="aluno_id" id="aluno_id" value="<?= $this->aluno_id; ?>" />
    <input type="hidden" name="avaliacao_id" id="avaliacao_id" value="<?= $this->avaliacao_id; ?>" />
    
    <fieldset>
        <legend>Avalia&ccedil;&atilde;o F&iacute;sica - <span style="color: #0088CC;">Di&acirc;metros Osseos</span> <span style="float: right;">Passo 3 de 3</span></legend>

            <table width="600" border="0" style="margin: 0 auto;">
                <tbody>                    
                    <tr>
                        <td width="170">Biestil&oacute;ide (punho):</td><td  width="150"><input type="text" name="biestiloide" id="biestiloide" size="5" value="<?= isset($_GET['biestiloide'])? $_GET['biestiloide'] : '' ?>" /> <span class="medidas">cm</span></td>
                        <td>Biepicondiliano do f&ecirc;mur:</td><td><input type="text" name="biepicondiliano_femur" id="biepicondiliano_femur" size="5" value="<?= isset($_GET['biepicondiliano_femur'])? $_GET['biepicondiliano_femur'] : '' ?>" /> <span class="medidas">cm</span></td>
                    </tr>
                    <tr>
                        <td>Biacromial:</td><td><input type="text" name="biacromial" id="biacromial" size="5" value="<?= isset($_GET['biacromial'])? $_GET['biacromial'] : '' ?>" /> <span class="medidas">cm</span></td>
                        <td>Biileocristal:</td><td><input type="text" id="biileocristal" name="biileocristal" size="5" value="<?= isset($_GET['biileocristal'])? $_GET['biileocristal'] : '' ?>" /> <span class="medidas">cm</span></td>
                    </tr>
                    <tr>    
                        <td>Bitrocanteriano:</td><td><input type="text" id="bitrocanteriano" name="bitrocanteriano" size="5"  value="<?= isset($_GET['bitrocanteriano'])? $_GET['bitrocanteriano'] : '' ?>" /> <span class="medidas">cm</span></td>
                        <td>Biepicondiliano do &uacute;mero:</td><td><input type="text" id="biepicondiliano_umero" name="biepicondiliano_umero" size="5"  value="<?= isset($_GET['biepicondiliano_umero'])? $_GET['biepicondiliano_umero'] : '' ?>" /> <span class="medidas">cm</span></td>                                                
                    </tr>
                    <tr>    
                        <td>Bimaleolar:</td><td><input type="text" name="bimaleolar" id="bimaleolar" size="5"  value="<?= isset($_GET['bimaleolar'])? $_GET['bimaleolar'] : '' ?>" /> <span class="medidas">cm</span></td>
                    </tr>                    
                </tbody>
            </table>
    </fieldset>

</form>
		
		
