<style>
    table th {background: #ccc;}
    table tr td {background: #fff; padding: 3px; font-size: 13px;}
    table,th,td { border-collapse:collapse; font-size: 13px; }    
</style>
<script>
$(function(){
    loadPeriodizacao();
    changeComboTreino();
    
    $(document).ajaxStart(function() {
            $( "#carregando" ).show();
    })
    $(document).ajaxComplete(function() {
            $( "#carregando" ).hide();
    })
    
    $('#btnEntrar').click(function(){
        var params = $('#form-periodizacao').serialize();
        
        $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-periodizacao',
            data: params,
            success: function(resp) {
                if(resp.retorno !== 'sucesso'){
                    alert(resp.msg); return false;
                }else {                    
                    loadPeriodizacao();
                    changeComboTreino();
                    $('#cbTreinoPer, #txtDescricao, #txtDias').val('');
                    
                    window.location.reload();
                }
            }
        });
        //$('#showPeriodizacao').load(BASE_URL+'admin/salvar-periodizacao', params);
    });
    
});

function removePeriodizacao(periodizacao_id) {    
    $.ajax({
        type:'post',
        url: BASE_URL+'admin/excluir-periodizacao',
        data: {periodizacao_id: periodizacao_id},
        dataType:'json',
        success: function(resp){
            if(resp.retorno !== 'sucesso'){
                alert(resp.msg); return false;
            }else {
                loadPeriodizacao();
                changeComboTreino();
            }
        }
    });
}

function loadPeriodizacao(){
    $('#showPeriodizacao').load(BASE_URL+'admin/grid-periodizacao-ficha', {ficha_id: $('#ficha_id').val()});
}

function changeComboTreino() {
    $('#cbTreinoPer').load(BASE_URL+'admin/change-combo-treino', {ficha_id: $('#ficha_id').val()});    
}
</script>

<?php $dias = array(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30); ?>
<?php //Utils_Print::printvardie($this->aPeriod['total']); ?>

<div data-role="header">
    <h1>Periodiza&ccedil;&atilde;o</h1>
    <a href="javascript:changePage('edit-treino-aluno/matricula/<?= $this->aluno_id ?>/ficha_id/<?= $this->ficha_id ?>')" data-theme="b">
		<
    </a>	
</div>

<div class="main-content" data-role="content">

<form id="form-periodizacao">
    <input type="hidden" name="ficha_id" id="ficha_id" value="<?php echo $this->ficha_id ?>" />
    
    <div class="control-group">
        <label class="control-label" for="inputTreino">Sess&atilde;o:</label>
        <div class="controls">
            <div class="input-group">
                <select name="cbTreinoPer" id="cbTreinoPer" class="form-control">
                    
                </select>
            </div>
        </div>
    </div>
    <br>
    
    
    <div class="control-group">
        <label class="control-label" for="inputDescricao" id="inputDescricao">Descricao:</label>
        <div class="controls">
            <div class="input-group">                
                <input name="txtDescricao" id="txtDescricao" type="text" placeholder="Ex: 3 x 10">
            </div>
        </div>
    </div>

    <br>

    <div class="control-group">
        <label class="control-label" for="inputDias">Dias:</label>
        <div class="controls">
            <div class="input-group">
                <!--<input type="text" name="txtDias" class="col-md-4" id="txtDias" value="<?php ?>" class="form-control" placeholder=""> &nbsp;-->
                <select name="txtDias" id="txtDias">
                  <?php foreach($dias as $dia): ?>	
                     <option value="<?= $dia ?>"><?= $dia ?></option>
                  <?php endforeach; ?>                  
                </select>
                &nbsp;
                <button type="button" class="btn btn-primary" id="btnEntrar" style="background: green;"><i class="ace-icon fa fa-adn"></i>Adicionar</button>
            </div>
        </div>
    </div>
    
    <br>
    <div id="carregando" style="display: none; background: yellow; padding: 5px; margin: 0 0 15px;">Aguarde...</div>
    <div id="showPeriodizacao"></div>
</form>
	
</div>	