<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.form.js' ?>"></script>
<link rel='stylesheet' type='text/css' href="<?php echo $this->baseUrl().'/bootstrap/css/jasny-bootstrap.css' ?>"> 
<script type="text/javascript" src="<?php echo $this->baseUrl().'/bootstrap/js/jasny-bootstrap.js' ?>"></script>

<script type="text/javascript">
jQuery(function(){

     	var files;
 
	// Add events
	$('input[type="file"]').on('change', prepareUpload);
	 
	// Grab the files and set them to our variable
	function prepareUpload(event)
	{
	  files = event.target.files;
	}
	
	$('#btSalvar').on('click', uploadFiles);
 
	// Catch the form submit and upload the files
	function uploadFiles(event)
	{
	  openAguarde(); 
	  
	  event.stopPropagation(); // Stop stuff happening
	  event.preventDefault(); // Totally stop stuff happening
	 
	    // START A LOADING SPINNER HERE
	 
	    // Create a formdata object and add the files
            var data = new FormData(); 
            if(files) {                               
                $.each(files, function(key, value) {                
                    data.append(key, value);
                });
            }
            
            var params = $( "#frmAluno" ).serialize();
            
            var fileImage = $('input[type=file]').val();
            if( fileImage ) {
                params += '&files='+fileImage;
            }
	    
            <?php if( !isset($this->aAluno) ): ?>
                salvarAluno(params, data);
            <?php else: ?>
                alterarAluno(params, data);
            <?php endif; ?>
	    
	}
        
//        $('#ckVerSenha').click(function(){
//            var value = $('input[name="ckVerSenha"]:checked').val();
//
//            if(value == 'on'){
//                $('#senhaCad').hide().attr('disabled', true);
//                $('#hdsenha').val( $('#senhaCad').val() ).show().attr('disabled', false);
//            }else {
//                $('#hdsenha').hide().attr('disabled', true);
//                $('#senhaCad').show().attr('disabled', false);
//            }
//        })
//
//        $('#senhaCad').keyup(function(){
//            var senha = $(this).val();
//            $('#hdsenha').val( senha );
//        })
    
})


function salvarAluno(params, data) {
    $.ajax({
        url: BASE_URL+'admin/salvar-aluno-mobile?'+params,
        type: 'post',
        data: data,
        cache: false,
        dataType: 'json',
        processData: false, // Dont process the files
        contentType: false, // Set content type to false as jQuery will tell the server its a query string request
        success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else {
                    alert(resp.msg);
                    window.location = BASE_URL+'admin/aluno';
                }
        }
    });
}

function alterarAluno(params, data) {    
    $.ajax({
        url: BASE_URL+'admin/alterar-aluno-mobile?'+params,
        type: 'post',
        data: data,
        cache: false,
        dataType: 'json',
        processData: false, // Dont process the files
        contentType: false, // Set content type to false as jQuery will tell the server its a query string request
        success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    closeAguarde();
                    return false;
                }else {
                    alert(resp.msg);
                    window.location = BASE_URL+'admin/aluno';
                }
        }
    });
}

/*function verificaUsuarioExistente() {
    var email = $('#email').val();
    
    if(email) {
    
	    $.ajax({
	        type:'post',
	        url: BASE_URL+'admin/verifica-usuario-existente',
	        data: {email: email},
	        dataType: 'json',
	        success: function(resp) {
	            if(resp.retorno === 'sucesso'){
	                alert(resp.msg);
	                $('#nm_aluno').val(resp.dados.nome);
                    
	                $('#showSenha').hide();
	                
	                if(resp.dados.foto){    
	                    $('.ace-file-container').attr('data-title', '');
	                    $('.ace-file-container').html('<img src="'+BASE_URL+resp.dados.foto+'" height="180" />');
	                }    
	                return false;
	            }else
                    if(resp.retorno === 'cancelar'){
	                    alert(resp.msg);
	                    $('#nm_aluno').val('');
	                    $('#email').val('').focus();
	                    $('#valor').val('');
                    }else {
	                $('#showSenha').show();
	            }
	        }
	    })
    }
}*/

</script>

<div data-role="header">
    
    <?php if( !isset($this->aAluno) ): ?>
       <h1>Cadastrar Aluno</h1>
    <?php else: ?>
       <h1>Editar Aluno</h1>
    <?php endif; ?>
    
    
    <a data-direction="reverse" href="<?= $this->baseUrl() ?>/admin/aluno" data-theme="b">
        <
    </a>
     <?php if( !isset($this->aAluno) ): ?>
       <a href="#" id="btSalvar" data-theme="b">Salvar</a>
       <!--<input type="submit" value="Send" name="submit" class="btn">-->
    <?php else: ?>
       <a href="#" id="btSalvar" data-theme="b">Alterar</a>
    <?php endif; ?>
</div>

<div data-role="content">
    
        <?php if( !isset($this->aAluno) ): ?>
            <form id="frmAluno" method="post" enctype="multipart/form-data">
         <?php else: ?>
            <form id="frmAluno" method="post" enctype="multipart/form-data">
        <?php endif; ?>

            <input type="hidden" name="id" id="id" value="<?= (isset($this->aAluno))? $this->aAluno['matricula'] : '' ?>" />
            <input type="hidden" name="url" id="url" value="<?= (isset($this->aAluno))? $this->aAluno['foto'] : '' ?>" />
            <input type="hidden" name="thumbnail" id="thumbnail" value="<?= (isset($this->aAluno))? $this->aAluno['thumbnail'] : '' ?>" />


            <div class="form-group">            	
		   
		<label>Nome: </label>
		<input id="nm_aluno" name="nm_aluno" value="<?php echo ($this->aAluno['nome']) ?>" placeholder="Informe o nome do aluno" type="text">
		
		<label>Email do aluno: </label>
		<input type="text" name="email" id="email" onblur="verificaUsuarioExistente()" class="form-control" placeholder="E-mail do aluno" value="<?php echo $this->aAluno['results']['email'] ?>">
             
			 
		<?php if($this->sessao->perfil_id != 3 && $this->sessao->perfil_id != 4): ?>  
		<label>Valor hora/aula: </label>
		
		<input id="valor" name="valor" value="<?php echo $this->aAluno['valor'] ?>" type="text">
		
		<label>N. de Aulas: </label>
		<select name="qtd_aulas" id="qtd_aulas" style="font-size: 25px;">
	                <?php if(isset($this->aAluno)): ?>
	                    <option selected="selected" value="<?= $this->aAluno['qtd_aulas'] ?>"><?= $this->aAluno['qtd_aulas'] ?></option>
	                <?php endif; ?>
	                <option value="1">1</option>
	                <option value="2">2</option>
	                <option value="3" <?= (isset($this->aAluno))? '' : 'selected="selected"' ?>>3</option>
	                <option value="4">4</option>
	                <option value="5">5</option>
	                <option value="6">6</option>
	                <option value="7">7</option>
	        </select>
	        <?php endif; ?>
                
                
                
<!--                <div id="showSenha">
                    <label>Senha provis&oacute;ria: </label>
                    <input name="senhaCad" id="senhaCad" style="width: 100%" class="form-control" placeholder="Informe uma senha provis&oacute;ria" type="password">                     
                    <input name="senhaCad" id="hdsenha" style="width: 100%; display: none;" class="form-control" placeholder="Informe a senha provis&oacute;ria do professor" type="text">
                    
                    <label>
                      <input type="checkbox" id="ckVerSenha" name="ckVerSenha" /> Mostrar senha
                    </label>
                    
                </div>-->
                
                <label>Foto do aluno: </label>
                <div class="widget-body" style="padding-left: 2px;">
	                <div class="widget-main">
	                    <div class="fileinput fileinput-new" data-provides="fileinput">
	                        <div style="width: 300px;">
	                            <span class="btn btn-default btn-file">             
	                                <input type="file" name="fileImage" id="fileImage" />
	                            </span>
	
	                            <span style="font-size: 12px; color: #333;">
	                                Arquivo de imagem nos formatos: jpg, png, gif  <br>
	                                Tamanho m&aacute;ximo: 5M
	                            </span>
	                        </div>
	                        <div style="width: 90%; height: 180px; border: 3px solid #ddd;" class="ace-file-input ace-file-multiple fileinput-preview thumbnail" data-trigger="fileinput">
	                            <?php if($this->aAluno['thumbnail']): ?>
	                                <img src="<?php echo $this->baseUrl().$this->aAluno['thumbnail'] ?>" />
	                            <?php else: ?>
	                                <div class="ace-file-container" style="margin: 25% 0; font-weight: bold;">Foto do aluno</div>
	                            <?php endif; ?>
	                        </div>
	                        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput" data-role="button"  data-icon="delete">Remove foto</a>
	                    </div>
	                </div>
                </div>            
            </div>

        </form>
        
        
<!-- End Modal Confirm -->
</div>