<link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/montar-treino.css' ?>">
<script src="<?php echo $this->baseUrl().'/js/admin/jsFichaAluno.js' ?>"></script>
<style>
  /*.table tr th { font-size: 20px; }
  .table tr td { font-size: 20px; }*/
</style>

<div data-role="header">
    <h1>Montar treino</h1>
    <a href="<?= $this->baseUrl() ?>/" data-theme="b">
        <
    </a>
</div>

<div>

	<?php if($this->results['total'] == 0): ?>
		<div class="alert alert-block alert-warning" style="background: #f4dae5; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">
			<b><?= ($this->sessao->nome) ?></b>, cadastre primeiro o aluno para depois montar seu treino.
		</div>
	<?php else: ?>
    
    <br>
    <table class="table table-striped" width="100%">
	<tr style="background: #333; color: #fff; border-radius: 5px 5px 5px 5px;">
	    <td colspan="2" style="padding: 6px 5px 6px;">Alunos</td>
	    <td align="center">Treinos</td>
	</tr>
        <?php foreach ($this->results['results'] as $i => $dado): ?>
            <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">
                <td width="5%" onclick="changePage('modal-aluno/id/<?= $dado['matricula'] ?>')">
                    <?php if($dado['foto']): ?>	                            	                
                       <img src="<?= $this->baseUrl() ?><?= $dado['thumbnail'] ?>" width="60" height="60" />
                    <?php else : ?>	 
                       <img src="<?= $this->baseUrl() ?>/images/fotos/default.jpg" width="60" height="60" />                           
                    <?php endif; ?> 
                </td>
                <td valign="top">	                                          
                     <?= ($dado['nome']) ?><br>  
                     <b>Matr&iacute;cula: </b><?= $dado['matricula'] ?><br>
                     <a target="_blank" style="color: blue; font-size: 12px; text-decoration:none;" href="http://gtrainer.com.br/treino/<?= $dado['matricula'] ?>">www.gtrainer.com.br/treino/<?= $dado['matricula'] ?></a>
                </td>
                <td style="text-align: center;">

		<a href="javascript:changePage('listar-treinos-aluno/matricula/<?= $dado['matricula']; ?>')" data-theme="b" data-role="button"  data-icon="search" data-mini="true">ver
		</a>

                </td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php endif; ?>    

</div>