<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.form.js' ?>"></script>
<script>
jQuery(function(){
    loadMusculo()
    initLoadModal()
})

function loadMusculo() {
    $( "#gridMusculo" ).load(BASE_URL+'admin/grid-musculos');
}

function initLoadModal() {
    $('#modalMusculo').dialog({
        autoOpen: false,
        modal: true,
        width: 500,
        height: 250
    })
    $('.ui-dialog-titlebar').hide();
}

function removerMusculo(id) {
    var r = confirm("Deseja realmente remover este Grupo Muscular?");
    if (r == true) {
	    $.ajax({
	            type:'post',
	            url: BASE_URL+'admin/remover-musculo',
	            data: { id: id },
	            success: function(resp){
	                if(resp.retorno != 'sucesso'){
	                    alert(resp.msg); 
	                    return false;
	                }else {
	                    loadMusculo();
	                    alert(resp.msg);
	                }
	            }
	    })
    }
}

function salvarMusculo() {
    var params = $( "#frmMusculo" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/salvar-musculo',
            data: params,
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadMusculo();
                    $('#modalMusculo').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}

function alterarMusculo() {
    var params = $( "#frmMusculo" ).serialize();

    $.ajax({
            type:'post',
            url: BASE_URL+'admin/alterar-musculo',
            data: params,
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadMusculo();
                    $('#modalMusculo').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}


function openModalMusculo() {
    
    $('#modalMusculo').load(BASE_URL+'admin/modal-musculo').dialog({
        buttons: [
            {
                text: "Salvar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    salvarMusculo();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalMusculo').dialog( "open" );
}

function openModalMusculoUpdate(id) {
    
    $('#modalMusculo').load(BASE_URL+'admin/modal-musculo', {id: id}).dialog({
        buttons: [
            {
                text: "Alterar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    alterarMusculo();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalMusculo').dialog( "open" );
}
</script>


<div id="breadcrumbs" class="breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="#" onclick="changePage('home')">Home</a></li>
        <i class="ace-icon fa fa-sitemap"></i> Grupo Muscular
    </ul>
</div>

<div class="page-content">
    <h3 class="page-header">
        <i class="ace-icon fa fa-users"></i> M&uacute;sculo
    </h3>

    <div class="row">
        <div class="col-xs-12">
            
            <button class="btn btn-success btn-primary" onclick="openModalMusculo()">
                <i class="ace-icon fa fa-plus"></i> Cadastrar M&uacute;sculo
            </button>
            <br><br>
            
            <div id="gridMusculo"></div>
            <div id="carregando"></div>
            
            <div id="modalMusculo"></div>
            
        </div>
    </div>

</div>
