<style>
  .table tr th { font-size: 20px; }
  .table tr td { font-size: 20px; }
</style>
<script>
function openCadastraNovoMusculo() {
    window.location = BASE_URL+'admin/modal-musculo';
}

function openEditarMusculo(id) {
    window.location = BASE_URL+'admin/modal-musculo/id/'+id;
}

function removerMusculo(id) {
    var r = confirm("Deseja realmente remover este Grupo Muscular?");
    if (r == true) {
    	    openAguarde();
    	    
	    $.ajax({
	            type:'post',
	            url: BASE_URL+'admin/remover-musculo',
	            data: { id: id },
	            success: function(resp){
	                if(resp.retorno != 'sucesso'){
	                    alert(resp.msg); 
	                    return false;
	                }else {
	                    alert(resp.msg);
			    window.location.reload();
	                }
	            }
	    })
    }
}
</script>


<div data-role="header">
    <h1>Grupo Muscular</h1>
    <a href="<?= $this->baseUrl() ?>/" data-theme="b"><</a>
    <a href="<?= $this->baseUrl() ?>/admin/modal-musculo" data-theme="b">Novo</a>    
</div>

<div>
    <!--<button data-theme="b" onclick="openCadastraNovoMusculo()">Cadastrar novo m&uacute;sculo</button>-->


	<?php if($this->results['total'] == 0): ?>
		<div id="textAlerta" style="background: #FFC; color: #000; padding: 10px; border-radius: 5px 5px 5px 5px;">			
			<b><?= ($this->sessao->nome) ?></b>, nenhum grupo muscular foi criado.
		</div>
	<?php else: ?>

		<table class="table table-striped" width="100%">
			<!--<tr>
				<th width="10%" align="left">Cod.</th>
				<th width="80%">M&uacute;sculos</th>
				<th width="10%">A&ccedil;&atilde;o</th>
			</tr>-->
			
			<?php foreach ($this->results['results'] as $i => $dado): ?>
			   <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">
				<td valign="top" onclick="openEditarMusculo(<?= $dado['id'] ?>)">
				   <?= ($dado['musculo']) ?>
				</td>
				<td valign="center" align="center" width="10%">
		                    <a href="#" onclick="removerMusculo(<?= $dado['id'] ?>)">
		                    <img src="<?= $this->baseUrl() ?>/images/acao/ico_delete.gif" width="20" height="20" style="border: 1px solid #ccc; padding: 5px;" data-role="button" class="show-page-loading-msg" data-textonly="false" data-textvisible="true" data-msgtext="Aguarde, removendo..." data-inline="true" />
		                    </a>
		                </td>
			   </tr>
			<?php endforeach; ?>
		</table>
		
	<?php endif; ?>    
	
</div>	