<div class="pagination">
    <!-- Link para a primeira página -->
    <?php if (isset($this->previous)): ?>
        <a title="Primeira Página" onclick="pagination(<?= $this->first ?>)" href="#">&laquo; Primeira</a>|
    <?php else: ?>
        <!--<a class="current" title="Primeira Página" onclick="pagination(<?= $this->first ?>)" href="#">&laquo; Primeira</a>|-->
    <?php endif; ?>

    <!-- Link para a página anterior -->
    <?php if (isset($this->previous)): ?>
        <a title="Página Anterior" onclick="pagination(<?= $this->previous ?>)" href="#">&laquo; Anterior</a>|
    <?php else: ?>
        <!--<a  class="current" title="Página Anterior" onclick="pagination(<?= $this->previous ?>)" href="#">&laquo; Anterior</a>|-->
    <?php endif; ?>

    <!-- Links numerados -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a title="<?php echo $page; ?>" onclick="pagination(<?= $page ?>)"  href="#"><?php echo $page; ?></a>|
        <?php else: ?>
            <a class="current" title="<?php echo $page; ?>" onclick="pagination(<?= $page ?>)" href="#"><b><?php echo $page; ?></b></a>|
        <?php endif; ?>
    <?php endforeach; ?>

    
    <!-- Link para a Próxima página -->
    <?php if (isset($this->next)): ?>
        <a title="Próxima Página" onclick="pagination(<?= $this->next ?>)" href="#">Próxima &raquo;</a>|
    <?php else: ?>
        <!--<a class="current" title="Próxima Página" onclick="pagination(<?= $this->next ?>)" href="#">Próxima &raquo;</a>|-->
    <?php endif; ?>

    <!-- Última página -->
    <?php if (isset($this->next)): ?>
        <a title="Última Página" onclick="pagination(<?= $this->last ?>)" href="#">Última &raquo;</a>
    <?php else: ?>
        <!--<a class="current" title="Última Página" onclick="pagination(<?= $this->last ?>)" href="#">Última &raquo;</a>-->
    <?php endif; ?>
</div>