<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.form.js' ?>"></script>
<script>
jQuery(function(){
    initLoadModal()
    loadProfessores()
})

function loadProfessores() {
    $( "#gridProfessores" ).load(BASE_URL+'admin/grid-professores');
}

function initLoadModal() {
    $('#modalProfessor').dialog({
        autoOpen: false,
        modal: true,
        width: 500,
        height: 610
    })
    $('.ui-dialog-titlebar').hide();
}

function removerProfessor(id, email) {
    $('#modalRemove').dialog({
        autoOpen: true,
        modal: true,
        width: 300,
        height: 230,
        buttons: [
            {
                html: "Sim",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    var sucesso = false;
                    
                    $.ajax({
                            type:'post',
                            url: BASE_URL+'admin/remover-professor',
                            data: { id: id, email: email },
                            async: false,
                            success: function(resp){
                                if(resp.retorno != 'sucesso'){
                                    alert(resp.msg); 
                                    return false;
                                }else {
                                    sucesso = true;
                                    loadProfessores();
                                    alert(resp.msg);
                                }
                            }
                    })
                    
                    if(sucesso) $( this ).dialog( "close" );
                    
                }
            },
            {
                text: "Não",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                } 
            }
            
        ]
    })
    $('.ui-dialog-titlebar').hide();    
}

function salvarProfessor() {
    $( "#frmProfessor" ).ajaxSubmit({
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadProfessores();
                    $('#modalProfessor').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}

function alterarProfessor() {
    $( "#frmProfessor" ).ajaxSubmit({
            dataType: 'json',
            success: function(resp){
                if(resp.retorno != 'sucesso'){
                    alert(resp.msg); 
                    return false;
                }else {
                    loadProfessores();
                    $('#modalProfessor').dialog( "close" );
                    alert(resp.msg);
                }
            }
    })
}


function openModalProfessores() {
    
    $('#modalProfessor').load(BASE_URL+'admin/modal-professor').dialog({
        buttons: [
            {
                text: "Salvar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    salvarProfessor();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalProfessor').dialog( "open" );
}

function openModalProfessorUpdate(id) {
    
    $('#modalProfessor').load(BASE_URL+'admin/modal-professor', {id: id}).dialog({
        buttons: [
            {
                text: "Alterar",
                "class" : "btn btn-primary btn-xs",
                click: function() {
                    alterarProfessor();
                } 
            } ,
            {
                html: "Cancelar",
                "class" : "btn btn-danger btn-xs",
                click: function() {
                    $( this ).dialog( "close" );
                }
            }
        ]
    })
    $('#modalProfessor').dialog( "open" );
}
</script>


<div id="breadcrumbs" class="breadcrumbs">
    <ul class="breadcrumb">
        <li><a href="#" onclick="changePage('home')">Home</a></li>
        <li class="active">Professores</li>
    </ul>
</div>

<div class="page-content">
    <h3 class="page-header">
        <i class="ace-icon fa fa-users"></i> Professores
    </h3>

    <div class="row">
        <div class="col-xs-12">
            
            <button class="btn btn-success btn-primary" onclick="openModalProfessores()">
                <i class="ace-icon fa fa-plus"></i> Cadastrar Professor
            </button>
            <br><br>
            
            <div id="gridProfessores"></div>
            <div id="carregando"></div>
            
        </div>
    </div>

</div>

<div id="modalProfessor"></div>

<div id="modalRemove" style="display: none;">
    <h3 class="page-header">
        <i class="ace-icon fa fa-warning"></i> Alerta
    </h3>
    <div>Deseja realmente remover este professor do sistema?</div>
</div>