<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl().'/bootstrap/css/bootstrap.min.css' ?>'>
<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery/jquery.js' ?>"></script>
<style>
table {background: #fff;}
 table tr th { font-size: 15px; }
 table tr td { font-size: 15px; }
 table tr { border-bottom: 1px solid #ccc; }
</style>

<?php
    list($ano) = explode('-', $this->dadosAluno['dt_nascimento']);
    $idade = ( date('Y') - $ano );
?>

<div data-role="header">
    <h1>Avalia&ccedil;&atilde;o</h1>
    <a href="#" onclick="window.location=BASE_URL+'admin/listar-avaliacoes-aluno/matricula/<?= $this->dadosAluno['matricula'] ?>'" data-theme="b"> 
        <
    </a>
</div>
    

<table width="100%" border="0">
    <tr>
        <td><b>Aluno:</b></td>
        <td><?= ($this->dadosAluno['nome']); ?></td>
    </tr>
    <tr>
        <td width="30%"><b>Idade:</b></td>
        <td><?= $idade ?> anos</td>
    </tr>
    <tr>
        <td><b>Peso:</b></td>
        <td><?= $this->aAvaliacao['peso'] ?> Kg</td>
    </tr>
    <tr>
        <td><b>Altura:</b></td>
        <td><?= $this->aAvaliacao['altura'] ?> m</td>
    </tr>
    <tr>    
        <td><b>Protocolo:</b> </td>
        <td><?= $this->aAvaliacao['protocolo'] ?></td>
    </tr>
    <tr>
        <td><b>Data:</b>
        <td><?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['data']) ?></td>
    </tr>
    <tr>
        <td><b>Reavalia&ccedil;&atilde;o:</b></td>
        <td><?= Utils_Date::formataDataSemHoraToShow($this->aAvaliacao['dt_reavaliacao']) ?></td>
    </tr>
    <tr>
        <td colspan="10" align="center">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="10" align="center"><b>IMC: <?= $this->aAvaliacao['imc'] ?> - <?= $this->aAvaliacao['situacao'] ?></b></td>
    </tr>
    <tr>
        <td colspan="10" align="center">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10">
         <table id="resultado" width="100%" border="0" style="background: #fff;">
            <tr>
                <td colspan="5" align="center" style="background: #C40C0C; color: #fff;">Resultato</td>
            </tr>
            <tr>
                <td width="26%" ><b>% Gordura:</b> </td>
                <td width="25%"><?= number_format($this->aAvaliacao['percentual_gordura'], 2) ?> %</td>
                <td height="150" align="center" rowspan="8"></td>
                <td ><b>M. Magra:</b> </td>
                <td><?= $this->aAvaliacao['massa_magra'] ?> Kg</td>
            </tr>
            <tr>             
                <td ><b>Peso Ideal:</b> </td>
                <td><?= $this->aAvaliacao['peso_ideal'] ?> Kg</td>
                <td width="25%" ><b>M. Gorda:</b> </td>
                <td width="25%"><?= $this->aAvaliacao['massa_gorda'] ?> Kg</td>
            </tr>
            <tr>
                <td ><b>Excesso:</b> </td>
                <td><?= $this->aAvaliacao['peso_excesso'] ?> Kg</td>                            
                <td ><b>Osso:</b> </td>
                <td><?= $this->aAvaliacao['massa_ossea'] ?> Kg</td>
            </tr>
            <tr>
                <td ><b>Musculo:</b> </td>
                <td><?= $this->aAvaliacao['massa_muscular'] ?> Kg</td>
                <td ><b>Residual:</b> </td>
                <td><?= $this->aAvaliacao['massa_residual'] ?> Kg</td>
            </tr>
        </table>
      </td>      
    </tr>
    <tr>
        <td colspan="10" align="center">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="10">
        <table width="100%" border="1">
            <thead>
                <tr>
                    <td style="background: yellow;" colspan="2" align="center"><b>Dobras Cut&acirc;neas</b> </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="10%"><b>Triceps:</b> </td>
                    <td width="35%" colspan="2"><?= $this->aAvaliacao['TR'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Subescapular:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['SB'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Axilar Media:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['AX'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Abdomen:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['AB'] ?> cm</td>
                </tr>                        
                <tr>
                    <td><b>Coxa:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['CX'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Panturrilha:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['PA'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Biceps:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['BI'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Torax:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['PE'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Supra Iliaca:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['SI'] ?> cm</td>
                </tr>
            </tbody>    
        </table>
      </td>  
    </tr>
    <tr>
        <td colspan="10" align="center">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="10">
            <table width="100%" border="1">
            <thead>
                <tr>
                    <td style="background: green; color: #fff;" colspan="3" align="center"><b>Per&iacute;metros</b> </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="13%"><b>T&oacute;rax:</b> </td>
                    <td width="35%" colspan="2"><?= $this->aAvaliacao['torax'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Pesco&ccedil;o:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['pescoco'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Ombro:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['ombro'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Cintura:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['cintura'] ?> cm</td>
                </tr>                        
                <tr>
                    <td><b>Abd&ocirc;men:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['abdomen'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Quadril:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['quadril'] ?> cm</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td><b>Direita</b></td>
                    <td><b>Esquerda</b></td>
                </tr>
                <tr>
                    <td><b>Bra&ccedil;o contra&iacute;do:</b></td>
                    <td><?= $this->aAvaliacao['braco_direito_contraido'] ?> cm</td>
                    <td><?= $this->aAvaliacao['braco_esquerdo_contraido'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Bra&ccedil;o relaxado:</b></td>
                    <td><?= $this->aAvaliacao['braco_direito_relaxado'] ?> cm</td>
                    <td><?= $this->aAvaliacao['braco_esquerdo_relaxado'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Antebra&ccedil;o:</b></td>
                    <td><?= $this->aAvaliacao['antebraco_direito'] ?> cm</td>
                    <td><?= $this->aAvaliacao['antebraco_esquerdo'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Coxa:</b></td>
                    <td><?= $this->aAvaliacao['coxa_direita'] ?> cm</td>
                    <td><?= $this->aAvaliacao['coxa_esquerda'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Panturrilha:</b></td>
                    <td><?= $this->aAvaliacao['panturrilha_direita'] ?> cm</td>
                    <td><?= $this->aAvaliacao['panturrilha_esquerda'] ?> cm</td>
                </tr>
            </tbody>    
        </table>
        </td>
    </tr>
    <tr>
        <td colspan="10" align="center">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="10" align="center">
          <table  width="100%" border="1">
            <thead>
                <tr>
                    <td style="background: #0091d9; color: #fff;" colspan="3" align="center"><b>Medidas &Oacute;sseas</b> </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="20%"><b>Biestilóide (punho):</b> </td>
                    <td width="10%" colspan="2"><?= $this->aAvaliacao['biestiloide'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Biepicondiliano do f&ecirc;mur:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['biepicondiliano_femur'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Biacromial:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['biacromial'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Biileocristal:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['biileocristal'] ?> cm</td>
                </tr>                        
                <tr>
                    <td><b>Bitrocanteriano:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['bitrocanteriano'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Biepicondiliano do úmero:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['biepicondiliano_umero'] ?> cm</td>
                </tr>
                <tr>
                    <td><b>Bimaleolar:</b> </td>
                    <td colspan="2"><?= $this->aAvaliacao['bimaleolar'] ?> cm</td>
                </tr>
            </tbody>    
        </table>
        </td>
    </tr>
</table>                    


</div> 