<?php if($this->results['total'] == 0): ?>

<?php else: ?>
    
        <?php foreach ($this->results['results'] as $i => $dado): ?>
            <tr bgColor="<?= ($i%2==0)? '#ddd' : '' ?>">
                <td width="5%" onclick="changePage('modal-aluno/id/<?= $dado['matricula'] ?>')">
                    <?php if($dado['foto']): ?>	                            	                
                       <img src="<?= $this->baseUrl() ?><?= $dado['thumbnail'] ?>" width="60" height="60" />
                    <?php else : ?>	 
                       <img src="<?= $this->baseUrl() ?>/images/fotos/default.jpg" width="60" height="60" />                           
                    <?php endif; ?> 
                </td>
                <td valign="top" onclick="changePage('modal-aluno/id/<?= $dado['matricula'] ?>')">	                                          
                     <?= utf8_encode($dado['nome']) ?><br>
                     <span style="font-size: 12px;"><?= ($dado['email']) ?></span><br>
                     <b style="font-size: 13px;">Matr&iacute;cula:</b> <span style="font-size: 13px;"><?= $dado['matricula'] ?></span><br>
                </td>
                <td valign="center" align="center" width="10%">
                    <a href="#" onclick="removerAluno(<?= $dado['matricula'] ?>)">
                      <img src="<?= $this->baseUrl() ?>/images/acao/ico_delete.gif" width="20" height="20" style="border: 1px solid #ccc; padding: 5px;" data-role="button" class="show-page-loading-msg" data-textonly="false" data-textvisible="true" data-msgtext="Aguarde, removendo..." data-inline="true" />
                      </a>
                </td>
            </tr>
        <?php endforeach; ?>
    
<?php endif; ?>    