<?php #Utils_Print::printvardie($this->sessao->perfil_id); ?>
<div class="page-content">
    <h3 class="page-header">
        <i class="ace-icon fa fa-home"></i> 
        Sistema de Gerenciamento de Treino.
    </h3>

    <div class="row">
        <div class="col-xs-12">
            <!-- Alert Sucesso -->
            <div class="alert alert-block alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <strong>
                    <i class="ace-icon fa fa-check"></i> Bem vindo <b><?php echo utf8_encode($_SESSION['usuario']->nome); ?></b>!
                </strong>
                Esta &eacute; sua &aacute;rea de administrador.
            </div>
        </div>
    </div>
</div>