<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/site/login.css" />

<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/site/Login.js"></script>

<div id="header-login">
    <a href="<?= $this->baseUrl() ?>/"></a>
</div>

<div class="tablet-notebook" style="margin: 0 1em;">

    <div class="panel panel-default" style="margin: 0 auto; width: 100%; max-width: 25em;">
        <div class="panel-heading">
            <h3>Entrar no Gtrainer</h3>
        </div>
        <div class="panel-body">
            <form id="form-login" method="post" onsubmit="entrar(this)">
                <div class="content-wrap">
                    <!--
                    <div style="margin-bottom: 2em; text-align: center;">
                    <img class="profile-img" alt="" src="<?= $this->baseUrl() ?>/images/male.png" style="width: 8em;">
                    </div>
                    -->
                    
                    <div class="input-text no-margin">
                        <label for="email">E-mail</label>
                        <input type="text" class="form-control input-lg" placeholder="Seu endereço de e-mail" name="login" id="login" required>
                    </div>
                    
                    <div class="input-text no-margin">
                        <label for="nome">Senha</label>
                        <input type="password" class="form-control input-lg" placeholder="Sua senha" id="senha" name="senha" required>
                    </div>
      
                    <button class="btn btn-primary btn-block btn-lg" type="button" id="btnEntrar">Entrar</button>

                    
            </form>
            <br>
                    <p class="texto" style="margin: 5px 0 5px 0;">Ainda não é cadastrado? 
                    <a href="<?= $this->baseUrl() ?>/index/cadastro" class="btn btn-warning btn-lg btn-block">Cadastre-se</a></p>
        </div>
    </div>
</div>

 

<!--
<div id="header-login">
        <a href="<?= $this->baseUrl() ?>/"></a>
    </div>
    <div class="bg-azul-hotsite"></div>
    <div id="content-login">
        <div class="sobre-sistema">
            <p class="destaque">O que é o GTrainer?</p>
            <p>
                O GTrainer é um aplicativo que auxilia os profissionais de academias
                (Personal Trainer) a realizarem a montagem e acompanhamento dos treinos
                dos seus alunos, dentro ou fora da academia.
            </p>
        </div>

        <div class="tablet-notebook"></div>
        <div class="box-login">
            <div class="cabecalho">Acesse sua conta</div>
            <div class="conteudo">
                <div>
                    <form id="form-login" method="post" onsubmit="entrar(this)">
                        <div class="input-text no-margin">
                            <label for="email">E-mail</label>
                            <input type="text" id="login" name="login" placeholder="Ex: contato@gtrainer.com" style="width: 315px;"  />
                        </div>
                        <div class="input-text">
                            <label for="senha">Senha</label>
                            <a tabindex="-1" class="esqueci-minha-senha" href="<?= $this->baseUrl() ?>/index/esqueci-minha-senha">(Esqueceu sua senha?)</a>
                            <input type="password" id="senha" name="senha" style="width: 315px;" />
                        </div>
                        <!--<div class="input-checkbox ui-checkbox">
                            <input type="checkbox" name="lembrar" id="lembrar" class="check" />
                            <label for="lembrar">Lí e concordo com os termos de uso</label>
                        </div>-->
<!--
                        <button type="button" id="btnEntrar" class="btn btn-primary btn-login" style="width: 315px;">Entrar</button>
                    </form>

                    <p class="texto" style="margin: 5px 0 5px 0;">Ainda não é cadastrado? <button type="button" onclick="javascript:window.location=BASE_URL+'index/cadastro'" class="btn btn-warning btn-lg btn-block">Cadastre-se</button></p>
                </div>
            </div>
        </div>
    </div>
   
<footer id="mini-rodape" class="">
    <p class="observacao"><span class="destaque">GTRAINER &copy; 2020</span> - Todos os direitos reservados</p>
</footer>
--> 

<script type="text/javascript">
    ajustarRodape(); 
    $(window).resize(function () {
        ajustarRodape(); 
    });

    function ajustarRodape() {
        $("#mini-rodape ul.links li").width($("#mini-rodape ul.links").innerWidth() / $("#mini-rodape ul.links li").length);
    }
    
    $(document).keyup(function(e){
        if(e.keyCode === 13){
            $('#btnEntrar').trigger('click');
        }
    });
</script>