<?php 
    $read = $_SESSION['usuario'];
?>
<script type="text/javascript">

function renovarPlanoAcademia() {
    var tipo_plano = $('input[name="rdTipoPlano"]:checked').val();

    if(!tipo_plano){
        alert('Selecione um plano.'); return false;
    }

    document.getElementById('aguarde').classList.remove('hidden');
    document.getElementById('btnPagSeguro').classList.add('hidden');

    $.ajax({
        type: 'post',
        url: BASE_URL+"admin/salvar-solicitacao-plano",
        data: {
            usuario_id: <?= $read->id ?>,
            perfil_id: <?= $read->perfil_id ?>,
            tipo_plano: tipo_plano
        },
        dataType: 'json',
        success: function(resp) {
            if(resp.retorno == 'sucesso') {
                //alert(resp.msg);

                if(resp.url){
                    window.location = resp.url;
                }
            }else {
                alert(resp.msg);
                return false;
            }
        }
    })
}
</script>

<div class="panel panel-default">
    <div class="panel-body">
        <h3 style="margin: 0 0 30px 0">Renovar Plano
        <div style="margin-top: 1em; font-size: 12px; color: #aaa; clear: both;">Selecione um plano abaixo e clique no botão "Pagar com PagSeguro para renovar o seu plano"</div>
        </h3>

        <a id="btnPagSeguro" href="#" onclick="renovarPlanoAcademia()">
            <img src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/184x42-pagar-assina.gif"></img>
        </a>
        <div id="aguarde" class="alert alert-warning hidden">
            Aguarde...
        </div>

        <table class="table table-hover">
            <tr bgColor="#eee">
                <th>#</th>
                <th>Plano</th>
                <th>Limite de dias</th>
                <th>Limite de alunos</th>
                <th>Valor</th>
            </tr>
            <?php foreach($this->aPlanos as $value): ?>
                <tr>
                    <td>
                        <input type="radio" name="rdTipoPlano" id="rdTipo<?= $value['nome'] ?>"
                        value="<?= $value['id'] ?>">
                    </td>
                    <td><b><?= $value['nome'] ?></b></td>
                    <td><?= !empty($value['limite_dias'])? $value['limite_dias'] : 'ilimitado' ?></td>
                    <td><?= !empty($value['limite_alunos'])? $value['limite_alunos'] : 'ilimitado' ?></td>
                    <td>R$<?= !empty($value['valor'])? $value['valor'] : '0.00' ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <h3 style="margin: 0 0 30px 0">Histórico de Planos do Usuário</h3>

        <table class="table table-hover table-striped">
            <tr>
                <th>Plano</th>
                <th>Início</th>
                <th>Término</th>
                <th>Status</th>
            </tr>
            <?php foreach($this->historicoPlanosUsuario as $value): ?>
                <tr>
                    <td><?= $value['plano'] ?></td>
                    <td><?= $value['dt_inicio'] ?></td>
                    <td><?= $value['dt_fim'] ?></td>
                    <td><label class="label <?= ($value['situacao']=='IN' || $value['situacao']=='EX'? 'label-danger' : 'label-success') ?>"><?= $value['ds_situacao'] ?></label></td>
                </tr>
            <?php endforeach; ?>
        </table>

        <form class="form-login-cad">

        </form>
    </div>
</div>