<!--
<div class="panel panel-default">
    <div class="panel-body">
        <h3 style="margin: 0 0 30px 0">Trocar senha</h3>
-->
		<form id="form-trocar-senha" action="<?= $this->baseUrl().'/admin/salvar-troca-senha' ?>" method="POST"  onsubmit="oController.salvar(event)" enctype="multipart/form-data">
	        <div class="row">
	        	<div class="col-md-12">
	        		<div class="form-group">
	        			<label>Senha atual</label>
	        			<input type="password" name="senhaAtual" id="senhaAtual" class="form-control" required>
	        		</div>
	        	</div>
	        </div>
	        <div class="row">
	        	<div class="col-md-12">
	        		<div class="form-group">
	        			<label>Nova senha</label>
	        			<input type="password" name="novaSenha" id="novaSenha" class="form-control" required>
	        		</div>
	        	</div>
	        </div>
	        <div class="row">
	        	<div class="col-md-12">
	        		<div class="form-group">
	        			<label>Confirmar senha</label>
	        			<input type="password" name="confirmaNovaSenha" id="confirmaNovaSenha" class="form-control" required>
	        		</div>
	        	</div>
	        </div>
	        <div id="aguarde" class="alert alert-warning hidden">
	            Aguarde...
	        </div>
	        <div class="row">
	        	<div class="col-md-12">
	        		<div class="form-group">
	        			<input type="submit" value="Salvar" class="btn btn-primary">
	        			<input type="button" id="btnCancelar" value="Cancelar" class="btn btn-default" data-dismiss="modal">
	        		</div>
	        	</div>
	        </div>
	    </form>
<!--
    </div>
</div>
-->
<script type="text/javascript" src="<?= $this->baseUrl().'/js/app/controllers/TrocarSenhaController.js' ?>"></script>
<script type="text/javascript">
	var oController = new TrocarSenhaController();
</script>