<style>

</style>
<div class="panel panel-default">
  <div class="panel-body">
  	<h3 style="margin: 0">Alunos
  		<?php if($this->habilitarBtnCadastro): ?>
  			<a href="<?= $this->baseUrl().'/admin/aluno-create' ?>" class="btn btn-primary btn-lg btn-circulo pull-right btn-flutuante" title="Cadastrar novo aluno"><i class="glyphicon glyphicon-plus"></i></a>
  		<?php endif; ?>
  	</h3>
  	<br>

	<div class="form-group has-default has-feedback" style="margin: 10px 0 5px 0">
	  <input type="text" class="form-control" onkeyup="lista.search(this.value)" placeholder="Pesquisar por um aluno..."  style="border-radius: 50px;">
	  <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true" style="margin-top: -1.8em;"></span>
	  <span id="inputSuccess2Status" class="sr-only">(success)</span>
	</div>

	<?php if(count($this->alunos['results']) > 0): ?>
		<div class="list-group">
		<?php foreach($this->alunos['results'] as $key => $value): ?>
		    <?php if($value['situacao'] != 3): ?>
			  <a href="<?= $this->baseUrl().'/admin/aluno-edit/id/'.$value['id'] ?>" class="list-group-item" <?= ($value['situacao']==2)? 'style="background: #f5e2e2;"' : '' ?>>
			    <img onclick="return false;" src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$value['fk_usuario'].'/foto_'.$value['filename'] ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle pull-left" height="50" width="45" style="margin-right: 10px" data-toggle="modal" data-target=".aluno_<?= $key ?>">
			    <strong><?= utf8_encode($value['nome']) ?></strong><br>
			    <p class="list-group-item-text">

			    	<?= $value['email'] ?>

					<div style="position: absolute; text-indent: 4.2em; font-size: 13px; color: #a7a7a7;">
						<?= $value['telefone'] ?>
					</div>

					<!--
			    	<div class="btn-group pull-right" role="group" style="margin-top: -2em;">
					  <button data-url="<?= $this->baseUrl().'admin/aluno/create/'.$value['matricula'] ?>" onclick="window.location=this.dataset.url" type="button" class="btn btn-warning btn-sm btn-circle"><i class="glyphicon glyphicon-pencil" title="Editar aluno"></i></button>
					</div>
					-->
			    </p>
			  </a>
		<?php endif; ?>	  
				<div class="modal aluno_<?= $key ?>" tabindex="-1" role="dialog">
				  <div class="modal-dialog modal-sm" role="document">
				    <div class="modal-content">
				    	<div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					        <h4 class="modal-title"><?= isset($value['nome'])? utf8_encode($value['nome']) : '' ?></h4>
				      	</div>
				      	<div class="modal-body">
				        	<img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$value['fk_usuario'].'/foto_'.$value['filename'] ?>" width="100%" class="img img-response">
				      	</div>
				    </div><!-- /.modal-content -->
				  </div><!-- /.modal-dialog -->
				</div><!-- /.modal -->
		<?php endforeach ?>
		</div>
	<?php else: ?>
		<div class="alert alert-warning">Nenhum aluno cadastrado!</div>
	<?php endif ?>
  </div>
</div>

<script type="text/javascript" src="<?= $this->baseUrl().'/js/app/helpers/ListGroup.js' ?>"></script>
<script type="text/javascript">
	var lista = new ListGroup();
</script>