<div class="panel panel-default">
  <div class="panel-body">
  	<h3 style="margin: 0 0 30px 0">
  		<?= $this->title ?>

	  	<a <?= isset($this->aluno['id'])? 'href="#"' : '' ?> data-toggle="modal" data-target=".fade" class="pull-right">
	  	<img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$this->aluno['fk_usuario'] ?>/<?= date('YmdHis') ?>" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error" class="img img-circle" height="70" width="65" >
	  	</a>
  	</h3>

	<form id="form" action="<?= $this->baseUrl().'/admin/salvar-aluno' ?>"  method="POST"  onsubmit="aluno.salvar(event)" enctype="multipart/form-data">

	  <input type="hidden" name="id" id="id" value="<?= isset($this->aluno['id'])? $this->aluno['id'] : '' ?>">

	  <div class="form-group">
	    <label for="nome">Nome</label>
	    <input type="text" class="form-control" id="nome" name="nm_aluno" value="<?= isset($this->aluno['nome'])? utf8_encode($this->aluno['nome']) : '' ?>" required>
	  </div>
	  <div class="form-group">
	    <label for="email">E-mail</label>
	    <input type="email" class="form-control" id="email" name="email" value="<?= isset($this->aluno['email'])? $this->aluno['email'] : '' ?>" data-url="<?= $this->baseUrl() ?>/admin/verifica-usuario-existente/email" required onblur="aluno.verificaUsuarioExistente(this)">
	  </div>
	  <div class="form-group">
	    <label for="telefone">Telefone</label>
	    <input type="text" class="form-control" id="telefone" name="telefone" value="<?= isset($this->aluno['telefone'])? $this->aluno['telefone'] : '' ?>" required oninvalid="validar(this)" title="O campo Telefone é obrigatório">
	  </div>
	
	  <div class="form-group">
	    <label for="dtNascimento">Data de Nascimento</label>
	    <input type="date" class="form-control" name="dtNascimento" id="dtNascimento" value="<?= isset($this->aluno['dt_nascimento'])? $this->aluno['dt_nascimento'] : '' ?>" required>
	  </div>

	  <div class="form-group">
	    <label for="sexo">Sexo</label>
	    <select name="sexo" id="sexo" class="form-control required">
	    	<option value="">SELECIONE...</option>
	    	<option value="M" <?= $this->aluno['sexo']=='M' ? 'selected' : '' ?>>Masculino</option>
	    	<option value="F" <?= $this->aluno['sexo']=='F' ? 'selected' : '' ?>>Feminino</option>
	    </select>
	  </div>
	
	  <div class="form-group">
	  	  <label for="nome">Senha</label>
		  <div class="input-group">
		      <span class="input-group-addon">
		        <input type="checkbox" id="chkVerSenha" onclick="aluno.mostrarSenha(this)"> &nbsp;
		      	<i class="glyphicon glyphicon-eye-open"></i>
		      </span>
		      <input type="password" class="form-control" id="senhaCad" name="senhaCad">
	     </div>
	     <small>Clique no botão acima para ver a senha</small>
	 </div>

	  <div class="form-group">
	    <label for="exampleInputFile">Foto do aluno</label>
	    <input type="file" id="foto" name="foto" class="form-control">
	  </div>
	  
	  <?php if(isset($this->aluno)): ?>
	  <div class="form-group">
	    <label>Situação</label>
	    <select class="form-control" name="situacao" id="situacao">
	        <option <?= (isset($this->aluno['situacao']) && $this->aluno['situacao']==1)? 'selected' : '' ?> value="1">Ativo</option>
	        <option <?= (isset($this->aluno['situacao']) && $this->aluno['situacao']==2)? 'selected' : '' ?> value="2">Inativo</option>
	        <!--<option <?= (isset($this->aluno['situacao']) && $this->aluno['situacao']==3)? 'selected' : '' ?> value="3">Sair da lista de alunos</option>-->
	    </select>
	  </div>
      <?php endif ?>
      
	  <div id="msg-load" class="hidden alert alert-warning">
	  	Aguarde...
	  </div>

	  <div class="form-group">
	  	<?php  if($this->habilitarBtnSalvar): ?>
	  		<button type="submit" class="btn btn-primary">Salvar</button>
	  	<?php endif; ?>
	  	
        <a href="<?= $this->baseUrl().'/admin/aluno' ?>" class="btn btn-default">Voltar</a>
        
	  	<?php if(isset($this->aluno)): ?>
		    <button type="button" id="bt-deletar" onclick="aluno.deletar(this)" data-url="<?= $this->baseUrl().'/admin/remover-aluno/id/'.$this->aluno['id'] ?>" class="btn btn-danger pull-right"><i class="glyphicon glyphicon-trash"></i></button>
	  	<?php endif ?>
	  </div>
	  
	</form>
  </div>
</div>

<?php if(isset($this->aluno['id'])): ?>
<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    	<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title"><?= isset($this->aluno['nome'])? utf8_encode($this->aluno['nome']) : '' ?></h4>
      	</div>
      	<div class="modal-body">
        	<img src="<?= $this->baseUrl().'/admin/ver-foto-usuario/id/'.$this->aluno['fk_usuario'] ?>/<?= date('YmdHis') ?>" width="100%" class="img img-response" data-error="<?= $this->baseUrl().'/images/foto_default.png' ?>" onerror="this.src=this.dataset.error">
      	</div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<?php endif; ?>

<script type="text/javascript" src="<?= $this->baseUrl().'/js/app/controllers/AlunosController.js' ?>"></script>
<script type="text/javascript">
	var aluno = new AlunosController();
</script>
